### ISSUE TITLE
GNS3 Doesn't detect that the VMware VM is started

### ISSUE THREAD

**Issue by ColdIce1** [GNS3/gns3-gui#1027]
Hello,
GNS3 doesn't detect that the GNS3 VM has started in VMware. I suspect that this is a VMware bug with the vmrun.exe.

GNS3 calls this command `output = subprocess.check_output(command, timeout=timeout)` and waits 60 seconds for it output. But `vmrun.exe` doesn't output anything. So GNS3 will fail after 60 seconds with this: `except subprocess.TimeoutExpired:
                self.error.emit("vmrun timeout expired", True)
                return`

Is there a fix for this soon?

**Comment by grossmj** [comment]
Hi,

Do you know what command was called or what action was performed?

Thanks,

**Comment by ColdIce1** [comment]
Command run from GNS3 to start the VM:
`"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" -T ws start "C:\Users\ColdIce-Desktop\Documents\Virtual Machines\GNS3 VM\GNS3 VM.vmx"
`

Command works fine command line, VM starts as expected but vmrun.exe doesn't output any status.
Running VMware 12.1.0 build-3272444

**Comment by noplay** [comment]
Are you running GNS3 as administrator? If it's that GNS3 can see the VM
imported as a user in VMware.

**Comment by ColdIce1** [comment]
I ran GNS3 as administrator, no difference.

**Comment by grossmj** [comment]
subprocess.check_output shouldn't block if the command doesn't return anything.

https://docs.python.org/3/library/subprocess.html#subprocess.check_output

Can you start the GUI with the debug param? ```gns3.exe --debug``` and give us the output.

For instance, on my Linux box I get:

```

=> GNS3 VM server initialized http://unset:8000
Executing vmrun with command: ['/usr/bin/vmrun', '-T', 'ws', 'start', '/home/grossmj/vmware/GNS3 VM/GNS3 VM.vmx']
Executing vmrun with command: ['/usr/bin/vmrun', '-T', 'ws', 'checkToolsState', '/home/grossmj/vmware/GNS3 VM/GNS3 VM.vmx']
Executing vmrun with command: ['/usr/bin/vmrun', '-T', 'ws', 'getGuestIPAddress', '/home/grossmj/vmware/GNS3 VM/GNS3 VM.vmx', '-wait']
GNS3 VM IP address set to 172.16.55.136
GNS3 VM is started and server is running on 172.16.55.136:8000
Synchronous get http://172.16.55.136:8000/v1/version with user 
GNS3 VM IP address is 172.16.55.136
Adjust local server IP address to 172.16.55.1
```

Thanks,

**Comment by grossmj** [comment]
@ColdIce1 have you tried with the latest release? (version 1.4.2).

Thanks,

**Comment by ColdIce1** [comment]
@grossmj Running 1.4.4.
Still doesn't work. Here is debug log:

`C:\Program Files\GNS3>gns3.exe --debug
GNS3 GUI version 1.4.4
Copyright (c) 2007-2016 GNS3 Technologies Inc.
2016-02-26 19:47:23 INFO logger.py:107 Log level: DEBUG
2016-02-26 19:47:24 DEBUG analytics.py:113 Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=ea93c6b3-6962-4af4-8ad3-697f355c4869&aip=1&t=screenview&an=GNS3&av=1.4.4&ua=Mozilla/5.0%20%28Windows%20NT%208%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20GNS3/1.4.4&cd=Main%20Window&ds=gns3-gui&sr=2560x1080&ul=nb_no
2016-02-26 19:47:24 INFO servers.py:102 New local server connection http://127.0.0.1:8001 registered
2016-02-26 19:47:24 INFO __init__.py:181 VPCS module reset
2016-02-26 19:47:24 INFO __init__.py:324 Dynamips module reset
2016-02-26 19:47:24 INFO __init__.py:264 IOU module reset
2016-02-26 19:47:24 INFO __init__.py:258 QEMU module reset
2016-02-26 19:47:24 INFO __init__.py:302 VirtualBox module reset
2016-02-26 19:47:24 INFO __init__.py:355 VMware module reset
2016-02-26 19:47:24 INFO __init__.py:70 Built-in module reset
2016-02-26 19:47:24 INFO topology.py:398 Topology reset
QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
2016-02-26 19:47:24 INFO servers.py:627 GNS3 VM server initialized http://unset:8000
2016-02-26 19:47:26 DEBUG gns3_vm.py:107 Executing vmrun with command: ['C:\\Program Files (x86)\\VMware\\VMware Workstation\\vmrun.exe', '-T', 'ws', 'start', 'C:\\Users\\ColdIce-Desktop\\Documents\\Virtual Machines\\GNS3 VM\\GNS3 VM.vmx']
2016-02-26 19:48:26 CRITICAL progress_dialog.py:152 Could not execute vmrun: Command '['C:\\Program Files (x86)\\VMware\\VMware Workstation\\vmrun.exe', '-T', 'ws', 'start', 'C:\\Users\\ColdIce-Desktop\\Documents\\Virtual Machines\\GNS3 VM\\GNS3 VM.vmx']' timed out after 60 seconds with output ''
2016-02-26 19:48:26 CRITICAL __init__.py:116 Could not execute vmrun: Command '['C:\\Program Files (x86)\\VMware\\VMware Workstation\\vmrun.exe', '-T', 'ws', 'start', 'C:\\Users\\ColdIce-Desktop\\Documents\\Virtual Machines\\GNS3 VM\\GNS3 VM.vmx']' timed out after 60 seconds with output ''
Stack (most recent call last):
  File "C:\Python343-64bit\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "gns3-gui/gns3/main.py", line 281, in <module>
  File "gns3-gui/gns3/main.py", line 269, in main
  File "./gns3-gui\gns3\main_window.py", line 1116, in startupLoading
  File "./gns3-gui\gns3\utils\progress_dialog.py", line 153, in _error
  File "./gns3-gui\gns3\qt\__init__.py", line 116, in critical`

**Comment by noplay** [comment]
The problem is normally the command should exit when the VM is start. If you run the command from the command line the command exit normally after a few seconds?

**Comment by ColdIce1** [comment]
@noplay Command doesn't exist from command line.

**Comment by noplay** [comment]
Can you share a screenshot of the command line?

**Comment by ColdIce1** [comment]
I don't believe that is necessary. There is literally no output, the command prompt is blinking.

**Comment by noplay** [comment]
If you start the VM from a terminal outside GNS3 your command prompt is blinking?

**Comment by grossmj** [comment]
Can you try to launch in debug mode? https://github.com/GNS3/gns3-gui/issues/1027#issuecomment-184941061

**Comment by grossmj** [comment]
Alternatively, I would be happy to remote control to your PC using TeamViewer to see what is wrong. What is your timezone?

**Comment by grossmj** [comment]
Or you can create a video to show us...

**Comment by ColdIce1** [comment]
@grossmj How can I come in personal contact with you to make an arrangement for remote control?

**Comment by noplay** [comment]
Send a mail to jeremy@gns3.net

**Comment by noplay** [comment]
Thanks!

**Comment by grossmj** [comment]
I haven't received any email. However, you could try to following:

Add the following line to ``C:\Users\ColdIce-Desktop\Documents\Virtual Machines\GNS3 VM\GNS3 VM.vmx``

```
hints.hideAll = "TRUE"
msg.noOk = "TRUE"
```

and try again.

Thanks,

**Comment by grossmj** [comment]
Must be a problem with vmrun.exe.

**Comment by kaage** [comment]
Hi all!

I have this same issue on Windows 7 and in both Workstation Pro 12 and Workstation Player 12 + VIX.

VM starts normally but vmrun.exe doesn't exit and GNS3 1.5.2 returns timeout error message after 60 seconds.

I can provide all debug information you need. Just in case we need my timezone is UTC +2.

**Comment by kaage** [comment]
I also tried to add lines:

hints.hideAll = "TRUE"
msg.noOk = "TRUE"

to the .vmx file but issue stays. Here's debug output from that situation:

![image](https://cloud.githubusercontent.com/assets/12019706/21580546/b8249a96-d007-11e6-8107-ec025091153b.png)

**Comment by babuutz** [comment]
Hello guys
same issue here, was working fine just yesterday I start machine and give me that error as the rest of the guy mention I am using gns3 vm 2.0.04a. when I run the command in CLI it says unknown file suffix.
NO UPDATE DONE IN MY MACHINE, my time zone is +3GMT. I am using vmware workstation 12 pro. gns3 vmware server IP address is 192.168.56.101 and I can ping that from PC which has IP address of 192.168.56.1 from one of the vmware interface, also I can ping that interface from GNS3 vm server.
also when open http://192.168.56.1:3080 open fine and http://192.168.56.101:3080 open fine. please advice more

**Comment by babuutz** [comment]
I checked to day, I open vmware workstation but not guest vmware gor gns3 server and then start gns3 it start the gns3 vmware server but after that it keep run not stopping what could be the issue

**Comment by babuutz** [comment]
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Hashil>cd c:\program files

c:\Program Files>cd GNS3

c:\Program Files\GNS3>gns3.exe --debug
GNS3 GUI version 1.5.3
Copyright (c) 2007-2017 GNS3 Technologies Inc.
2017-02-20 18:41:48 INFO logger.py:107 Log level: DEBUG
2017-02-20 18:41:48 DEBUG analytics.py:113 Send stats to Google Analytics: v=1&t
id=UA-55817127-3&cid=51927a71-d586-42b9-b306-d6d15bb81653&aip=1&t=screenview&an=
GNS3&av=1.5.3&ua=Mozilla/5.0%20%28Windows%20NT%208.1%29%20AppleWebKit/537.36%20%
28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20GNS3/1.5.3&cd=Main%20Window&ds=gn
s3-gui&sr=1366x768&ul=en_us
2017-02-20 18:41:49 INFO servers.py:103 New local server connection http://192.1
68.56.1:3080 registered
2017-02-20 18:41:49 INFO __init__.py:181 VPCS module reset
2017-02-20 18:41:49 INFO __init__.py:322 Dynamips module reset
2017-02-20 18:41:49 INFO __init__.py:262 IOU module reset
2017-02-20 18:41:49 INFO __init__.py:256 QEMU module reset
2017-02-20 18:41:49 INFO __init__.py:302 VirtualBox module reset
2017-02-20 18:41:49 INFO __init__.py:369 VMware module reset
2017-02-20 18:41:49 INFO __init__.py:193 Docker module reset
2017-02-20 18:41:49 INFO __init__.py:70 Built-in module reset
2017-02-20 18:41:49 INFO topology.py:408 Topology reset
2017-02-20 18:41:49 INFO servers.py:655 GNS3 VM server initialized http://unset:
3080
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method

qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
2017-02-20 18:41:49 DEBUG analytics.py:47 Error when pushing to Google Analytics
 Error creating SSL context ()
2017-02-20 18:41:51 DEBUG progress_dialog.py:98 WaitForVMWorker thread started
2017-02-20 18:41:51 DEBUG gns3_vm.py:109 Executing vmrun with command: ['C:\\Pro
gram Files (x86)\\VMware\\VMware Workstation\\vmrun.exe', '-T', 'ws', 'start', '
D:\\Virtual Machines\\GNS3 VM-1.5.3\\GNS3 VM-1.5.3.vmx']
2017-02-20 18:42:51 CRITICAL progress_dialog.py:159 WaitForVMWorker thread stopp
ing with an error: Could not execute vmrun: Command '['C:\\Program Files (x86)\\
VMware\\VMware Workstation\\vmrun.exe', '-T', 'ws', 'start', 'D:\\Virtual Machin
es\\GNS3 VM-1.5.3\\GNS3 VM-1.5.3.vmx']' timed out after 60 seconds with output '
'

Make sure the correct product (Fusion, Workstation or Player) is selected in Pre
ferences / VMware
2017-02-20 18:42:51 CRITICAL __init__.py:95 Could not execute vmrun: Command '['
C:\\Program Files (x86)\\VMware\\VMware Workstation\\vmrun.exe', '-T', 'ws', 'st
art', 'D:\\Virtual Machines\\GNS3 VM-1.5.3\\GNS3 VM-1.5.3.vmx']' timed out after
 60 seconds with output ''

Make sure the correct product (Fusion, Workstation or Player) is selected in Pre
ferences / VMware
Stack (most recent call last):
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\site-packa
ges\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "gns3-gui/gns3/main.py", line 282, in <module>
  File "gns3-gui/gns3/main.py", line 264, in main
  File "./gns3-gui\gns3\main_window.py", line 1233, in startupLoading
  File "./gns3-gui\gns3\qt\__init__.py", line 223, in func_wrapper
  File "./gns3-gui\gns3\utils\progress_dialog.py", line 160, in _error
  File "./gns3-gui\gns3\qt\__init__.py", line 95, in critical
2017-02-20 18:43:37 DEBUG progress_dialog.py:104 WaitForVMWorker thread canceled

2017-02-20 18:43:37 DEBUG progress_dialog.py:128 WaitForVMWorker thread is being
 destroyed
2017-02-20 18:43:37 DEBUG progress_dialog.py:135 WaitForVMWorker thread destroye
d
2017-02-20 18:43:38 DEBUG progress_dialog.py:104 WaitForVMWorker thread canceled

2017-02-20 18:43:38 DEBUG http_client.py:302 Synchronous get http://192.168.56.1
:3080/v1/version with user 'S3eoY2TUvHvl7zH96S9f54eZjgRUzfxM9Nsoqi4xcCIq81AdKqU4
OZMOtTCmeziL'
2017-02-20 18:43:39 DEBUG http_client.py:302 Synchronous get http://192.168.56.1
:3080/v1/version with user 'S3eoY2TUvHvl7zH96S9f54eZjgRUzfxM9Nsoqi4xcCIq81AdKqU4
OZMOtTCmeziL'
2017-02-20 18:43:40 INFO servers.py:540 Starting local server process with "C:\P
rogram Files\GNS3\gns3server.EXE" --host=192.168.56.1 --port=3080 --local --cont
roller --allow --debug --log="C:\Users\Hashil\AppData\Roaming\GNS3\gns3_server.l
og" --pid="C:\Users\Hashil\AppData\Roaming\GNS3\gns3_server.pid"
2017-02-20 18:43:40 INFO servers.py:553 Local server process has started (PID=32
32)
2017-02-20 18:43:40 DEBUG progress_dialog.py:98 WaitForConnectionWorker thread s
tarted
2017-02-20 18:43:41 DEBUG progress_dialog.py:109 WaitForConnectionWorker thread
finished
2017-02-20 18:43:41 DEBUG progress_dialog.py:128 WaitForConnectionWorker thread
is being destroyed
2017-02-20 18:43:41 DEBUG progress_dialog.py:135 WaitForConnectionWorker thread
destroyed
2017-02-20 18:43:41 DEBUG analytics.py:113 Send stats to Google Analytics: v=1&t
id=UA-55817127-3&cid=51927a71-d586-42b9-b306-d6d15bb81653&aip=1&t=screenview&an=
GNS3&av=1.5.3&ua=Mozilla/5.0%20%28Windows%20NT%208.1%29%20AppleWebKit/537.36%20%
28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20GNS3/1.5.3&cd=Setup%20Wizard&ds=g
ns3-gui&sr=1366x768&ul=en_us
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method

qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
2017-02-20 18:43:42 DEBUG analytics.py:47 Error when pushing to Google Analytics
 Error creating SSL context ()
2017-02-20 18:43:43 DEBUG local_config.py:306 Section MainWindow has not changed
. Skip saving configuration
2017-02-20 18:43:43 DEBUG analytics.py:113 Send stats to Google Analytics: v=1&t
id=UA-55817127-3&cid=51927a71-d586-42b9-b306-d6d15bb81653&aip=1&t=screenview&an=
GNS3&av=1.5.3&ua=Mozilla/5.0%20%28Windows%20NT%208.1%29%20AppleWebKit/537.36%20%
28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20GNS3/1.5.3&cd=Main%20Window&ds=gn
s3-gui&sr=1366x768&ul=en_us
2017-02-20 18:43:43 INFO __init__.py:181 VPCS module reset
2017-02-20 18:43:43 INFO __init__.py:322 Dynamips module reset
2017-02-20 18:43:43 INFO __init__.py:262 IOU module reset
2017-02-20 18:43:43 INFO __init__.py:256 QEMU module reset
2017-02-20 18:43:43 INFO __init__.py:302 VirtualBox module reset
2017-02-20 18:43:43 INFO __init__.py:369 VMware module reset
2017-02-20 18:43:43 INFO __init__.py:193 Docker module reset
2017-02-20 18:43:43 INFO __init__.py:70 Built-in module reset
2017-02-20 18:43:43 INFO topology.py:408 Topology reset
2017-02-20 18:43:43 DEBUG analytics.py:113 Send stats to Google Analytics: v=1&t
id=UA-55817127-3&cid=51927a71-d586-42b9-b306-d6d15bb81653&aip=1&t=screenview&an=
GNS3&av=1.5.3&ua=Mozilla/5.0%20%28Windows%20NT%208.1%29%20AppleWebKit/537.36%20%
28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20GNS3/1.5.3&cd=New%20Project%20Dia
log&ds=gns3-gui&sr=1366x768&ul=en_us
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method

qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
2017-02-20 18:43:43 DEBUG analytics.py:47 Error when pushing to Google Analytics
 Error creating SSL context ()
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method

qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
2017-02-20 18:43:43 DEBUG analytics.py:47 Error when pushing to Google Analytics
 Error creating SSL context ()
2017-02-20 18:43:46 DEBUG main_window.py:1115 Close the main Windows
2017-02-20 18:43:46 DEBUG analytics.py:113 Send stats to Google Analytics: v=1&t
id=UA-55817127-3&cid=51927a71-d586-42b9-b306-d6d15bb81653&aip=1&t=screenview&an=
GNS3&av=1.5.3&ua=Mozilla/5.0%20%28Windows%20NT%208.1%29%20AppleWebKit/537.36%20%
28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20GNS3/1.5.3&cd=Main%20Window&ds=gn
s3-gui&sc=end&sr=1366x768&ul=en_us
2017-02-20 18:43:46 DEBUG main_window.py:1121 Project is closed killing server a
nd closing main windows
2017-02-20 18:43:46 DEBUG main_window.py:1141 _finish_application_closing
2017-02-20 18:43:46 DEBUG local_config.py:306 Section MainWindow has not changed
. Skip saving configuration
2017-02-20 18:43:46 INFO servers.py:578 Stopping local server (PID=3232)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "./gns3-server\gns3server\server.py", line 192, in close_asyncio_loop
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\asyncio\pr
oactor_events.py", line 427, in close
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\asyncio\pr
oactor_events.py", line 537, in _stop_accept_futures
AttributeError: 'int' object has no attribute 'cancel'
Exception ignored in: <bound method BaseEventLoop.__del__ of <ProactorEventLoop
running=False closed=False debug=True>>
Traceback (most recent call last):
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\asyncio\ba
se_events.py", line 431, in __del__
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\asyncio\pr
oactor_events.py", line 427, in close
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\asyncio\pr
oactor_events.py", line 537, in _stop_accept_futures
AttributeError: 'int' object has no attribute 'cancel'
Exception ignored in: <bound method IocpProactor.__del__ of <IocpProactor overla
pped#=2 result#=0>>
Traceback (most recent call last):
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\asyncio\wi
ndows_events.py", line 749, in __del__
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\asyncio\wi
ndows_events.py", line 741, in close
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 1267, in debug
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 1415, in _log
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 1425, in handle
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 1487, in callHandlers
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 855, in handle
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 1047, in emit
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 1037, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method Task.__del__ of <Task pending coro=<IocpProa
ctor.accept.<locals>.accept_coro() running at C:\Jenkins\workspace\Release Windo
ws\Windows\python-3.5.2\lib\asyncio\windows_events.py:484> wait_for=<_Overlapped
Future cancelled created at C:\Jenkins\workspace\Release Windows\Windows\python-
3.5.2\lib\asyncio\windows_events.py:489> created at C:\Jenkins\workspace\Release
 Windows\Windows\python-3.5.2\lib\asyncio\windows_events.py:491>>
Traceback (most recent call last):
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\asyncio\ta
sks.py", line 92, in __del__
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\asyncio\ba
se_events.py", line 1177, in call_exception_handler
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 1308, in error
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 1415, in _log
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 1425, in handle
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 1487, in callHandlers
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 855, in handle
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 1047, in emit
  File "C:\Jenkins\workspace\Release Windows\Windows\python-3.5.2\lib\logging\__
init__.py", line 1037, in _open
NameError: name 'open' is not defined
2017-02-20 18:43:50 DEBUG main_window.py:1153 Time spend in the software is 121
External WM_DESTROY received for  QWidgetWindow(0xc8f1690100, name="NewProjectDi
alogWindow") , parent:  QWindow(0x0) , transient parent:  QWidgetWindow(0xc8f169
1360, name="MainWindowWindow")

c:\Program Files\GNS3>



GNS3.EXE DEBUG  output please help me out I am stuck here

**Comment by ColdIce1** [comment]
@grossmj 
Error still exist in 1.5.3 and 2.0.0 beta 4. I e-mailed you also.

**Comment by ColdIce1** [comment]
After hours of debugging, I reinstalled Windows. Issue resolved. VMrun now runs perfectly.

**Comment by noplay** [comment]
Thanks for the feedback :(
