### ISSUE TITLE
Start ASA

### ISSUE THREAD

**Issue by claytondf** [GNS3/gns3-gui#104]
GNS3 management console. Running GNS3 Early Release (ER) version 1.0beta4.dev1 on linux (64-bit).
Copyright (c) 2006-2014 GNS3 Technologies.

=> ****** Exception detected, traceback information saved in /root/.config/GNS3/exception.log ******

PLEASE REPORT ON http://forum.gns3.net/development-f14.html OR http://github.com/GNS3/gns3-gui/issues

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.0beta4.dev1-py3.4.egg/gns3/dialogs/node_configurator_dialog.py", line 96, in showConfigurationPageSlot
    self.previousPage.saveSettings(self.previousItem.settings(), self.previousItem.node())
  File "/usr/local/lib/python3.4/dist-packages/gns3_gui-1.0beta4.dev1-py3.4.egg/gns3/modules/qemu/pages/qemu_vm_configuration_page.py", line 163, in saveSettings
    server, qemu_path = self.uiQemuListComboBox.itemData(self.uiQemuListComboBox.currentIndex()).split(":", 1)
AttributeError: 'NoneType' object has no attribute 'split'



**Comment by grossmj** [comment]
This should have been fixed a long time ago now.
