### ISSUE TITLE
Package naming issue: "gns3-net-converter"

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1093]
_From @lukassup on February 27, 2016 21:28_

GNS3 won't launch with this gns3-converter fork.

Your fork has renamed the "gns3-converter" Python package to "gns3-net-converter", but GNS3 is still looking for "gns3-converter" and cannot find it.

The following change makes GNS3 work again:

```
diff -aur gns3-converter.orig/setup.py gns3-converter.new/setup.py
--- gns3-converter.orig/setup.py	2016-02-27 23:21:04.245764848 +0200
+++ gns3-converter.new/setup.py	2016-02-27 23:21:18.965826323 +0200
@@ -28,7 +28,7 @@
     }
 
 setup(
-    name='gns3-net-converter',
+    name='gns3-converter',
     version=__import__('gns3converter').__version__,
     packages=['gns3converter'],
     url='https://github.com/gns3/gns3-converter',
```

_Copied from original issue: GNS3/gns3-converter#2_

**Comment by noplay** [comment]
The fix is not working when distributed via PyPi

**Comment by noplay** [comment]
@lukassup do you have an error at launch? I try and I can launch GNS3 without issue the current fork

**Comment by lukassup** [comment]
I receive the following error on launch:

```
$ gns3
Traceback (most recent call last):
  File "/usr/bin/gns3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/user/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2912, in <module>
    @_call_aside
  File "/home/user/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2898, in _call_aside
    f(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2925, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/user/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 642, in _build_master
    ws.require(__requires__)
  File "/home/user/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/user/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 830, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gns3-converter>=1.2.0' distribution was not found and is required by gns3-gui
```

However with the patch I have provided I am able to run GNS3 fine.

**Comment by noplay** [comment]
Fixed in next GNS3 release

**Comment by eneas91** [comment]
Hello my friend!
Would you be so kind to explain more thoroughly how to apply this patch?
Thanks
