### ISSUE TITLE
1.5: Can't open console to dynamips router

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1096]
GNS3 version 1.5.0dev1 on Linux (64-bit) with Python 3.4.2 Qt 5.3.2.

Since some of the last changes in 1.5, I can't open a console to a dynamips router. I get the following exception:

```
Traceback (most recent call last):
  File "/opt/GNS3/lib/python3.4/site-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/qt/__init__.py", line 228, in partial
    return func(*args, **kwargs)
  File "/opt/GNS3/lib/python3.4/site-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/graphics_view.py", line 1016, in consoleToNode
    node.openConsole(aux=aux)
  File "/opt/GNS3/lib/python3.4/site-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/vm.py", line 481, in openConsole
    if console_type == "telnet":
UnboundLocalError: local variable 'console_type' referenced before assignment
```

**Comment by noplay** [comment]
Fixed thanks!

**Comment by ehlers** [comment]
Currently the things got worse, I can get no console at all, tested with dynamips, qemu and docker.

I get the following traceback:
```
Traceback (most recent call last):
  File "/opt/GNS3/lib/python3.4/site-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/qt/__init__.py", line 228, in partial
    return func(*args, **kwargs)
  File "/opt/GNS3/lib/python3.4/site-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/graphics_view.py", line 1016, in consoleToNode
    node.openConsole(aux=aux)
  File "/opt/GNS3/lib/python3.4/site-packages/gns3_gui-1.5.0dev1-py3.4.egg/gns3/vm.py", line 462, in openConsole
    console_type == "telnet"
UnboundLocalError: local variable 'console_type' referenced before assignment
```

**Comment by noplay** [comment]
Fixed late night commit is not a good thing :(
