### ISSUE TITLE
 Couldn't connect to hypervisor on 127.0.0.1:xxxxx

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#1104]
With any kind of Dynamips image/node, GNS3 server cannot connect; for example, with MGT-Switch-11 which is a 3725:

Response error: Error downloading http://AnIIj0n3Bq3DOgGy065HevlfGu4DKKxMqGG64wysNHM21pC8AtEgpAGA92VASTez@127.0.0.1:8000/v1/projects/d3f1b32d-60af-4481-b8d7-66a875013624/dynamips/vms - server replied: Conflict (error: 206)
error while setting up MGT-Switch-11: Couldn't connect to hypervisor on 127.0.0.1:59890 :[Errno 111] Connect call failed ('127.0.0.1', 59890)
Server error from http://127.0.0.1:8000: MGT-Switch-11: Couldn't connect to hypervisor on 127.0.0.1:59890 :[Errno 111] Connect call failed ('127.0.0.1', 59890)

Everything worked fine with 1.4.4; I don't know what has been changed in the meantime.

**Comment by jean-christophe-manciot** [comment]
I tried to downgrade to 1.4.3: exact same issue.
Looking at gns3_server.log:
2016-03-07 20:21:08 ERROR route.py:189 VM error detected: <class 'gns3server.modules.dynamips.dynamips_error.DynamipsError'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.3-py3.4.egg/gns3server/web/route.py", line 179, in control_schema
    yield from func(request, response)
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.3-py3.4.egg/gns3server/handlers/api/dynamips_vm_handler.py", line 75, in create
    chassis=request.json.pop("chassis", default_chassis))
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.3-py3.4.egg/gns3server/modules/base_manager.py", line 235, in create_vm
    yield from vm.create()
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.3-py3.4.egg/gns3server/modules/dynamips/nodes/router.py", line 184, in create
    self._hypervisor = yield from self.manager.start_new_hypervisor(working_dir=module_workdir)
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.3-py3.4.egg/gns3server/modules/dynamips/__init__.py", line 394, in start_new_hypervisor
    yield from hypervisor.connect()
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.3-py3.4.egg/gns3server/modules/dynamips/dynamips_hypervisor.py", line 92, in connect
    raise DynamipsError("Couldn't connect to hypervisor on {}:{} :{}".format(host, self._port, last_exception))
gns3server.modules.dynamips.dynamips_error.DynamipsError: Couldn't connect to hypervisor on 127.0.0.1:42752 :[Errno 111] Connect call failed ('127.0.0.1', 42752)

**Comment by noplay** [comment]
Do you have ghost dynamips process? It can explain the problem if a dynamips is still running.

**Comment by jean-christophe-manciot** [comment]
Starting GNS3 with the --debug option:
...
2016-03-07 20:32:51 INFO http_client.py:658 Response error: Error downloading http://AnIIj0n3Bq3DOgGy065HevlfGu4DKKxMqGG64wysNHM21pC8AtEgpAGA92VASTez@127.0.0.1:8000/v1/projects/d3f1b32d-60af-4481-b8d7-66a875013624/dynamips/vms - server replied: Conflict (error: 206)
Response error: Error downloading http://AnIIj0n3Bq3DOgGy065HevlfGu4DKKxMqGG64wysNHM21pC8AtEgpAGA92VASTez@127.0.0.1:8000/v1/projects/d3f1b32d-60af-4481-b8d7-66a875013624/dynamips/vms - server replied: Conflict (error: 206)
2016-03-07 20:32:51 DEBUG http_client.py:681 {
    "message": "Couldn't connect to hypervisor on 127.0.0.1:60595 :[Errno 111] Connect call failed ('127.0.0.1', 60595)",
    "status": 409
}
{
    "message": "Couldn't connect to hypervisor on 127.0.0.1:60595 :[Errno 111] Connect call failed ('127.0.0.1', 60595)",
    "status": 409
}
2016-03-07 20:32:51 ERROR vm.py:161 error while setting up MGT-Switch-11: Couldn't connect to hypervisor on 127.0.0.1:60595 :[Errno 111] Connect call failed ('127.0.0.1', 60595)
error while setting up MGT-Switch-11: Couldn't connect to hypervisor on 127.0.0.1:60595 :[Errno 111] Connect call failed ('127.0.0.1', 60595)

**Comment by jean-christophe-manciot** [comment]
No dynamips process running; only one gns3-server at 127.0.0.1:8000

**Comment by jean-christophe-manciot** [comment]
gns3-server has only 1 connection established with /usr/bin/gns3

**Comment by jean-christophe-manciot** [comment]
There is something special about how gns3-server handles Dynamips nodes, because I have multiple Qemu nodes in the same lab without any issue.

**Comment by noplay** [comment]
It's possible that a dynamips crash can explain this. It's work when you put a generic switch?

**Comment by jean-christophe-manciot** [comment]
No, same issue.

**Comment by jean-christophe-manciot** [comment]
I tried to build 1.4.5-dev, but for GUI:
error: Could not find suitable distribution for Requirement.parse('gns3-net-converter>=1.3.0')

**Comment by jean-christophe-manciot** [comment]
You can dismiss my last post: I was still using "dlintott" repo. Sorry. and I was able to build all 1.4.5 packages.
But it is impossible to start gns3-server 1.4.5:
![1 4 5 - no connection](https://cloud.githubusercontent.com/assets/13176858/13598050/092618e8-e51c-11e5-93ef-24a14388297b.jpg)

**Comment by noplay** [comment]
If you start the server by hand:
```
gns3-server --local
```

What do you have?

**Comment by jean-christophe-manciot** [comment]
gns3-server --local
gns3-server: command not found
root@samsung-ubuntu:/home/actionmystique/Downloads# gns3server --local
Traceback (most recent call last):
  File "/usr/local/bin/gns3server", line 9, in <module>
    load_entry_point('gns3-server==1.4.5.dev1', 'console_scripts', 'gns3server')()
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.5.dev1-py3.4.egg/gns3server/main.py", line 71, in main
    from gns3server.run import run
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.5.dev1-py3.4.egg/gns3server/run.py", line 31, in <module>
    from gns3server.server import Server
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.5.dev1-py3.4.egg/gns3server/server.py", line 32, in <module>
    from .web.route import Route
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.5.dev1-py3.4.egg/gns3server/web/route.py", line 28, in <module>
    from ..modules.vm_error import VMError
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.5.dev1-py3.4.egg/gns3server/modules/__init__.py", line 20, in <module>
    from .vpcs import VPCS
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.5.dev1-py3.4.egg/gns3server/modules/vpcs/__init__.py", line 25, in <module>
    from ..base_manager import BaseManager
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.5.dev1-py3.4.egg/gns3server/modules/base_manager.py", line 32, in <module>
    from gns3server.utils.interfaces import is_interface_up
  File "/usr/local/lib/python3.4/dist-packages/gns3_server-1.4.5.dev1-py3.4.egg/gns3server/utils/interfaces.py", line 26, in <module>
    raise Exception("psutil version should >= 3.0.0. If you are under ubuntu/debian install gns3 via apt instead of pip")
Exception: psutil version should >= 3.0.0. If you are under ubuntu/debian install gns3 via apt instead of pip

**Comment by noplay** [comment]
It's a know issue. The psutil from pip conflict with the Python installed. 

You need the ubuntu version of psutil:
``` 
sudo pip3 uninstall psutil
sudo apt-get install python3-psutil
```

The GNS3 package don't have this problem because we install the dependencies via apt.

**Comment by jean-christophe-manciot** [comment]
I have both versions, I have no idea how the pip one got installed.

**Comment by jean-christophe-manciot** [comment]
Yes, now I know how:
gns3server --local
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (psutil 2.2.1 (/usr/lib/python3/dist-packages), Requirement.parse('psutil>=3.0.0'), {'gns3-server'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gns3server", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3093, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psutil>=3.0.0' distribution was not found and is required by gns3-server

The python3-psutil apt release is ... 2.2.1-3. So, what next?

**Comment by noplay** [comment]
Or try:
```
sudo pip3 install psutil
sudo apt-get remove python3-psutil
```

But it will not solve the issue we didn't touch to dynamips since a long time. 1.4.5 will work like 1.4.4.

How dynamips is installed via our apt repository or by hand?

**Comment by jean-christophe-manciot** [comment]
Uninstalling apt version of python3-psutil, removing dependency in my home-brewed gns3-server_1.4.5 deb package, rebuilding the whole package, launching gns3, and ... it works. 
psutil 4.0.0 has been downloaded from pypi.python.org during the building process.

**Comment by noplay** [comment]
You still have issues with dynamips?

You are using the PPA build of dynamips?

**Comment by jean-christophe-manciot** [comment]
No, everything works fine now.
I built Dynamips with the latest commit 4ba6b2153a356bffd3f7aaa7c6130ab32497c5ff.

**Comment by noplay** [comment]
Thanks for the feedback
