### ISSUE TITLE
Exception, if docker image is missing

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#1153]
GNS3 version 1.5.0dev1 (latest) on Darwin (64-bit) with Python 3.5.1 Qt 5.6.0, docker on GNS3VM.

I decided to change the name of a docker container. When  opened a project, which uses the old name, I get this error message:
```
****** Exception detected, traceback information saved in /Users/behlers/.config/GNS3/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gns3_gui-1.5.0.dev1-py3.5.egg/gns3/modules/docker/pages/docker_vm_preferences_page.py", line 133, in _dockerImageEditSlot
    name=docker_image["name"])
KeyError: 'image'
```

I assume, I get the same message, when the docker container is deleted in the docker preference.

Getting an error message is absolutely fine, but maybe it could explain better, what's wrong.

**Comment by noplay** [comment]
I don't see how to replicate. If the image is missing GNS3 try to pull the image and  I see the error if it's not possible:
=> Server error from http://127.0.0.1:8001: iou-1: Docker has returned an error: 404 b'No such image: iou:latest\n'

**Comment by ehlers** [comment]
I tried to reproduce. I managed it, but it is really an obscure sequence:
- create new project (test in my case)
- move a docker container into this project (alpine in my case)
- save project
- enter docker preference, edit the docker container and change the template name (alpinexyz in my case)  
![bildschirmfoto 2016-04-05 um 17 40 10](https://cloud.githubusercontent.com/assets/896406/14288100/99bb0fb8-fb55-11e5-8429-4554db688620.png)
- reload the project  
  now the exception is shown

Here the debug log:
```
/Users/behlers# gns3 --debug
GNS3 GUI version 1.5.0dev1
Copyright (c) 2007-2016 GNS3 Technologies Inc.
2016-04-05 17:29:05 INFO logger.py:107 Log level: DEBUG
2016-04-05 17:29:05 DEBUG analytics.py:77 Stats is turn off ignore call Main Window
2016-04-05 17:29:06 INFO servers.py:102 New local server connection http://192.168.1.10:3080 registered
2016-04-05 17:29:06 INFO __init__.py:181 VPCS module reset
2016-04-05 17:29:06 INFO __init__.py:322 Dynamips module reset
2016-04-05 17:29:06 INFO __init__.py:262 IOU module reset
2016-04-05 17:29:06 INFO __init__.py:256 QEMU module reset
2016-04-05 17:29:06 INFO __init__.py:302 VirtualBox module reset
2016-04-05 17:29:06 INFO __init__.py:363 VMware module reset
2016-04-05 17:29:06 INFO __init__.py:193 Docker module reset
2016-04-05 17:29:06 INFO __init__.py:70 Built-in module reset
2016-04-05 17:29:06 INFO topology.py:408 Topology reset
2016-04-05 17:29:06 INFO servers.py:640 GNS3 VM server initialized http://unset:3080
2016-04-05 17:29:06 DEBUG progress_dialog.py:97 WaitForVMWorker thread started
2016-04-05 17:29:06 DEBUG gns3_vm.py:109 Executing vmrun with command: ['/Applications/VMware Fusion.app/Contents/Library/vmrun', '-T', 'fusion', 'start', '/Users/behlers/Documents/Virtual Machines.localized/GNS3.vmwarevm/GNS3.vmx', 'nogui']
2016-04-05 17:29:06 DEBUG gns3_vm.py:109 Executing vmrun with command: ['/Applications/VMware Fusion.app/Contents/Library/vmrun', '-T', 'fusion', 'checkToolsState', '/Users/behlers/Documents/Virtual Machines.localized/GNS3.vmwarevm/GNS3.vmx']
2016-04-05 17:29:06 DEBUG gns3_vm.py:109 Executing vmrun with command: ['/Applications/VMware Fusion.app/Contents/Library/vmrun', '-T', 'fusion', 'getGuestIPAddress', '/Users/behlers/Documents/Virtual Machines.localized/GNS3.vmwarevm/GNS3.vmx', '-wait']
2016-04-05 17:29:07 INFO wait_for_vm_worker.py:238 GNS3 VM IP address set to 192.168.1.99
2016-04-05 17:29:07 INFO wait_for_vm_worker.py:179 GNS3 VM is started and server is running on 192.168.1.99:3080
2016-04-05 17:29:07 DEBUG http_client.py:301 Synchronous get http://192.168.1.99:3080/v1/version with user
2016-04-05 17:29:07 DEBUG progress_dialog.py:110 WaitForVMWorker thread finished
2016-04-05 17:29:07 DEBUG progress_dialog.py:131 WaitForVMWorker thread is being destroyed
2016-04-05 17:29:07 DEBUG progress_dialog.py:138 WaitForVMWorker thread destroyed
2016-04-05 17:29:07 DEBUG http_client.py:301 Synchronous get http://192.168.1.10:3080/v1/version with user bGLTSCln7yq0Z98DYeFzEGALFHqePZnUQVwsakCvXYDUcQj8bU53KDeXojKV7zeD
2016-04-05 17:29:07 DEBUG http_client.py:301 Synchronous get http://192.168.1.10:3080/v1/version with user bGLTSCln7yq0Z98DYeFzEGALFHqePZnUQVwsakCvXYDUcQj8bU53KDeXojKV7zeD
2016-04-05 17:29:07 INFO servers.py:528 Starting local server process with "/usr/local/bin/gns3server" --host=192.168.1.10 --port=3080 --local --controller --debug --log="/Users/behlers/.config/GNS3/gns3_server.log" --pid="/Users/behlers/.config/GNS3/gns3_server.pid"
2016-04-05 17:29:07 INFO servers.py:541 Local server process has started (PID=988)
2016-04-05 17:29:07 DEBUG progress_dialog.py:97 WaitForConnectionWorker thread started
2016-04-05 17:29:07 DEBUG progress_dialog.py:110 WaitForConnectionWorker thread finished
2016-04-05 17:29:07 DEBUG progress_dialog.py:131 WaitForConnectionWorker thread is being destroyed
2016-04-05 17:29:07 DEBUG progress_dialog.py:138 WaitForConnectionWorker thread destroyed
2016-04-05 17:29:08 DEBUG analytics.py:77 Stats is turn off ignore call Main Window
2016-04-05 17:29:08 INFO __init__.py:181 VPCS module reset
2016-04-05 17:29:08 INFO __init__.py:322 Dynamips module reset
2016-04-05 17:29:08 INFO __init__.py:262 IOU module reset
2016-04-05 17:29:08 INFO __init__.py:256 QEMU module reset
2016-04-05 17:29:08 INFO __init__.py:302 VirtualBox module reset
2016-04-05 17:29:08 INFO __init__.py:363 VMware module reset
2016-04-05 17:29:08 INFO __init__.py:193 Docker module reset
2016-04-05 17:29:08 INFO __init__.py:70 Built-in module reset
2016-04-05 17:29:08 INFO topology.py:408 Topology reset
2016-04-05 17:29:16 DEBUG analytics.py:77 Stats is turn off ignore call New Project Dialog
2016-04-05 17:29:21 INFO __init__.py:181 VPCS module reset
2016-04-05 17:29:21 INFO __init__.py:322 Dynamips module reset
2016-04-05 17:29:21 INFO __init__.py:262 IOU module reset
2016-04-05 17:29:21 INFO __init__.py:256 QEMU module reset
2016-04-05 17:29:21 INFO __init__.py:302 VirtualBox module reset
2016-04-05 17:29:21 INFO __init__.py:363 VMware module reset
2016-04-05 17:29:21 INFO __init__.py:193 Docker module reset
2016-04-05 17:29:21 INFO __init__.py:70 Built-in module reset
2016-04-05 17:29:21 INFO topology.py:408 Topology reset
2016-04-05 17:29:21 INFO topology.py:498 Starting to save the topology (version 1.5.0dev1)
2016-04-05 17:29:21 INFO main_window.py:1321 Saving project: /Users/behlers/GNS3/projects/test/test.gns3
2016-04-05 17:29:21 DEBUG local_config.py:297 Section MainWindow has not changed. Skip saving configuration
2016-04-05 17:29:21 DEBUG analytics.py:70 Ignore call Main Window to Google Analytics because of rate limiting
Could not resolve property : ag
Could not resolve property : ak
2016-04-05 17:29:29 INFO __init__.py:137 creating node <class 'gns3.modules.docker.docker_vm.DockerVM'>
2016-04-05 17:29:29 INFO docker_vm.py:48 Docker image instance is being created
2016-04-05 17:29:29 INFO __init__.py:147 configuring node Docker container with id 1
2016-04-05 17:29:29 INFO http_client.py:419 Connection to http://192.168.1.99:3080
2016-04-05 17:29:29 DEBUG http_client.py:574 GET http://192.168.1.99:3080/v1/version {}
2016-04-05 17:29:29 DEBUG http_client.py:708 Decoding response from http://192.168.1.99:3080/v1/version response 200
2016-04-05 17:29:29 DEBUG http_client.py:715 {
    "local": false,
    "version": "1.5.0dev1"
}
2016-04-05 17:29:29 DEBUG http_client.py:574 POST http://192.168.1.99:3080/v1/projects {'name': 'test', 'project_id': None, 'temporary': False}
2016-04-05 17:29:29 DEBUG http_client.py:708 Decoding response from http://192.168.1.99:3080/v1/projects response 201
2016-04-05 17:29:29 DEBUG http_client.py:715 {
    "location": "/opt/gns3/projects",
    "name": "test",
    "path": "/opt/gns3/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4",
    "project_id": "3c1caae3-58d3-4362-9e28-9b3d1980e3f4",
    "temporary": false
}
2016-04-05 17:29:29 DEBUG http_client.py:574 GET http://192.168.1.99:3080/v1/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4/notifications {}
2016-04-05 17:29:29 DEBUG http_client.py:574 POST http://192.168.1.99:3080/v1/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4/docker/vms {'name': 'alpine-1', 'adapters': 1, 'console_type': 'telnet', 'image': 'alpine:3.3'}
2016-04-05 17:29:29 DEBUG http_client.py:708 Decoding response from http://192.168.1.99:3080/v1/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4/docker/vms response 201
2016-04-05 17:29:29 DEBUG http_client.py:715 {
    "adapters": 1,
    "aux": 5001,
    "console": 5000,
    "console_type": "telnet",
    "container_id": "62121df56bb2b4531037189988eed52ee30bb3db04c0791b55b148a82e051c76",
    "environment": null,
    "image": "alpine:3.3",
    "name": "alpine-1",
    "project_id": "3c1caae3-58d3-4362-9e28-9b3d1980e3f4",
    "start_command": null,
    "vm_directory": "/opt/gns3/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4/project-files/docker/9b4c33c1-11cc-4dcd-b86e-005cdc564ffb",
    "vm_id": "9b4c33c1-11cc-4dcd-b86e-005cdc564ffb"
}
2016-04-05 17:29:29 INFO vm.py:184 alpine-1 setting up and updating console from 'None' to '5000'
2016-04-05 17:29:29 INFO vm.py:184 alpine-1 setting up and updating aux from 'None' to '5001'
2016-04-05 17:29:29 INFO vm.py:184 alpine-1 setting up and updating start_command from '' to 'None'
2016-04-05 17:29:29 INFO vm.py:184 alpine-1 setting up and updating environment from '' to 'None'
2016-04-05 17:29:29 DEBUG docker_vm.py:74 Adapter Ethernet0 has been added
2016-04-05 17:29:29 INFO docker_vm.py:120 Docker container alpine-1 has been created
2016-04-05 17:29:29 DEBUG project.py:382 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 2.0, 'cpu_usage_percent': 0.1}}
2016-04-05 17:29:34 DEBUG project.py:382 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 2.0, 'cpu_usage_percent': 0.1}}
2016-04-05 17:29:35 DEBUG http_client.py:574 POST http://192.168.1.99:3080/v1/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4/commit {}
2016-04-05 17:29:35 INFO topology.py:498 Starting to save the topology (version 1.5.0dev1)
2016-04-05 17:29:35 INFO topology.py:518 Saving node: alpine-1
2016-04-05 17:29:35 INFO topology.py:532 Saving server: http://192.168.1.99:3080
2016-04-05 17:29:35 INFO main_window.py:1321 Saving project: /Users/behlers/GNS3/projects/test/test.gns3
2016-04-05 17:29:35 DEBUG local_config.py:297 Section MainWindow has not changed. Skip saving configuration
2016-04-05 17:29:35 DEBUG analytics.py:70 Ignore call Main Window to Google Analytics because of rate limiting
2016-04-05 17:29:35 DEBUG http_client.py:708 Decoding response from http://192.168.1.99:3080/v1/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4/commit response 204
2016-04-05 17:29:35 DEBUG http_client.py:715
2016-04-05 17:29:38 DEBUG analytics.py:77 Stats is turn off ignore call Preferences Dialog
2016-04-05 17:29:38 INFO http_client.py:419 Connection to http://192.168.1.10:3080
2016-04-05 17:29:38 DEBUG http_client.py:574 GET http://192.168.1.10:3080/v1/version {}
Could not resolve property : ag
Could not resolve property : ak
Could not resolve property : ag
Could not resolve property : ak
Could not resolve property : ag
Could not resolve property : ak
2016-04-05 17:29:38 DEBUG http_client.py:708 Decoding response from http://bGLTSCln7yq0Z98DYeFzEGALFHqePZnUQVwsakCvXYDUcQj8bU53KDeXojKV7zeD@192.168.1.10:3080/v1/version response 200
2016-04-05 17:29:38 DEBUG http_client.py:715 {
    "local": true,
    "version": "1.5.0dev1"
}
2016-04-05 17:29:38 DEBUG http_client.py:574 GET http://192.168.1.10:3080/v1/vmware/vms {}
2016-04-05 17:29:38 DEBUG http_client.py:708 Decoding response from http://bGLTSCln7yq0Z98DYeFzEGALFHqePZnUQVwsakCvXYDUcQj8bU53KDeXojKV7zeD@192.168.1.10:3080/v1/vmware/vms response 200
2016-04-05 17:29:38 DEBUG http_client.py:715 [
    {
        "vmname": "GNS3",
        "vmx_path": "/Users/behlers/Documents/Virtual Machines.localized/GNS3.vmwarevm/GNS3.vmx"
    },
    {
        "vmname": "jessie",
        "vmx_path": "/Users/behlers/Documents/Virtual Machines.localized/jessie.vmwarevm/jessie.vmx"
    },
    {
        "vmname": "vSRX",
        "vmx_path": "/Users/behlers/Documents/Virtual Machines.localized/vSRX.vmwarevm/vSRX.vmx"
    },
    {
        "vmname": "Windows7",
        "vmx_path": "/Users/behlers/Documents/Virtual Machines.localized/Windows7.vmwarevm/Windows7.vmx"
    }
]
2016-04-05 17:29:39 DEBUG project.py:382 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 2.0, 'cpu_usage_percent': 0.1}}
2016-04-05 17:29:43 DEBUG analytics.py:77 Stats is turn off ignore call Configuration Dialog
2016-04-05 17:29:44 DEBUG project.py:382 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 2.0, 'cpu_usage_percent': 0.0}}
2016-04-05 17:29:49 DEBUG project.py:382 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 2.0, 'cpu_usage_percent': 0.1}}
2016-04-05 17:29:54 DEBUG project.py:382 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 2.0, 'cpu_usage_percent': 0.1}}
****** Exception detected, traceback information saved in /Users/behlers/.config/GNS3/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gns3_gui-1.5.0.dev1-py3.5.egg/gns3/modules/docker/pages/docker_vm_preferences_page.py", line 133, in _dockerImageEditSlot
    name=docker_image["name"])
KeyError: 'image'

2016-04-05 17:29:58 DEBUG local_config.py:297 Section MainWindow has not changed. Skip saving configuration
2016-04-05 17:29:58 DEBUG local_config.py:297 Section GraphicsView has not changed. Skip saving configuration
2016-04-05 17:29:58 DEBUG local_config.py:297 Section Servers has not changed. Skip saving configuration
2016-04-05 17:29:58 DEBUG http_client.py:574 POST http://192.168.1.10:3080/v1/config/reload {}
2016-04-05 17:29:58 DEBUG local_config.py:297 Section PacketCapture has not changed. Skip saving configuration
2016-04-05 17:29:58 DEBUG local_config.py:297 Section VPCS has not changed. Skip saving configuration
2016-04-05 17:29:58 DEBUG local_config.py:297 Section Dynamips has not changed. Skip saving configuration
2016-04-05 17:29:58 INFO local_config.py:294 Section Dynamips has changed. Saving configuration
2016-04-05 17:29:58 INFO local_config.py:190 Configuration save to /Users/behlers/.config/GNS3/gns3_gui.conf
2016-04-05 17:29:58 DEBUG local_config.py:297 Section IOU has not changed. Skip saving configuration
2016-04-05 17:29:58 DEBUG local_config.py:297 Section IOU has not changed. Skip saving configuration
2016-04-05 17:29:58 DEBUG local_config.py:297 Section Qemu has not changed. Skip saving configuration
2016-04-05 17:29:58 INFO local_config.py:294 Section Qemu has changed. Saving configuration
2016-04-05 17:29:58 INFO local_config.py:190 Configuration save to /Users/behlers/.config/GNS3/gns3_gui.conf
2016-04-05 17:29:58 DEBUG local_config.py:297 Section VirtualBox has not changed. Skip saving configuration
2016-04-05 17:29:58 DEBUG local_config.py:297 Section VirtualBox has not changed. Skip saving configuration
2016-04-05 17:29:58 DEBUG local_config.py:297 Section VMware has not changed. Skip saving configuration
2016-04-05 17:29:58 DEBUG local_config.py:297 Section VMware has not changed. Skip saving configuration
2016-04-05 17:29:58 DEBUG local_config.py:297 Section Docker has not changed. Skip saving configuration
2016-04-05 17:29:58 INFO local_config.py:294 Section Docker has changed. Saving configuration
2016-04-05 17:29:58 INFO local_config.py:190 Configuration save to /Users/behlers/.config/GNS3/gns3_gui.conf
2016-04-05 17:29:58 DEBUG local_config.py:297 Section MainWindow has not changed. Skip saving configuration
2016-04-05 17:29:58 DEBUG http_client.py:708 Decoding response from http://bGLTSCln7yq0Z98DYeFzEGALFHqePZnUQVwsakCvXYDUcQj8bU53KDeXojKV7zeD@192.168.1.10:3080/v1/config/reload response 201
2016-04-05 17:29:58 DEBUG http_client.py:715
2016-04-05 17:29:59 DEBUG project.py:382 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 2.0, 'cpu_usage_percent': 0.0}}
2016-04-05 17:30:04 DEBUG project.py:382 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 2.0, 'cpu_usage_percent': 0.0}}
2016-04-05 17:30:06 DEBUG http_client.py:574 POST http://192.168.1.99:3080/v1/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4/close {}
2016-04-05 17:30:06 DEBUG http_client.py:708 Decoding response from http://192.168.1.99:3080/v1/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4/close response 204
2016-04-05 17:30:06 DEBUG http_client.py:715
2016-04-05 17:30:06 INFO project.py:345 Project 3c1caae3-58d3-4362-9e28-9b3d1980e3f4 closed
2016-04-05 17:30:06 INFO __init__.py:181 VPCS module reset
2016-04-05 17:30:06 INFO __init__.py:322 Dynamips module reset
2016-04-05 17:30:06 INFO __init__.py:262 IOU module reset
2016-04-05 17:30:06 INFO __init__.py:256 QEMU module reset
2016-04-05 17:30:06 INFO __init__.py:302 VirtualBox module reset
2016-04-05 17:30:06 INFO __init__.py:363 VMware module reset
2016-04-05 17:30:06 INFO __init__.py:193 Docker module reset
2016-04-05 17:30:06 INFO __init__.py:70 Built-in module reset
2016-04-05 17:30:06 INFO topology.py:408 Topology reset
2016-04-05 17:30:06 DEBUG topology.py:577 Start loading topology
2016-04-05 17:30:06 INFO topology.py:581 loading project: /Users/behlers/GNS3/projects/test/test.gns3
2016-04-05 17:30:06 DEBUG local_config.py:297 Section MainWindow has not changed. Skip saving configuration
2016-04-05 17:30:06 DEBUG topology.py:704 loading node with ID 1
2016-04-05 17:30:06 INFO __init__.py:137 creating node <class 'gns3.modules.docker.docker_vm.DockerVM'>
2016-04-05 17:30:06 INFO docker_vm.py:48 Docker image instance is being created
2016-04-05 17:30:06 INFO docker_vm.py:266 Docker container alpine-1 is loading
2016-04-05 17:30:06 DEBUG http_client.py:574 POST http://192.168.1.99:3080/v1/projects {'name': 'test', 'project_id': '3c1caae3-58d3-4362-9e28-9b3d1980e3f4', 'temporary': False}
2016-04-05 17:30:06 DEBUG topology.py:825 Finish loading topology
2016-04-05 17:30:06 DEBUG local_config.py:297 Section MainWindow has not changed. Skip saving configuration
2016-04-05 17:30:06 DEBUG http_client.py:708 Decoding response from http://192.168.1.99:3080/v1/projects response 201
2016-04-05 17:30:06 DEBUG http_client.py:715 {
    "location": "/opt/gns3/projects",
    "name": "test",
    "path": "/opt/gns3/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4",
    "project_id": "3c1caae3-58d3-4362-9e28-9b3d1980e3f4",
    "temporary": false
}
2016-04-05 17:30:06 DEBUG http_client.py:574 GET http://192.168.1.99:3080/v1/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4/notifications {}
2016-04-05 17:30:06 DEBUG http_client.py:574 POST http://192.168.1.99:3080/v1/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4/docker/vms {'vm_id': '9b4c33c1-11cc-4dcd-b86e-005cdc564ffb', 'name': 'alpine-1', 'console': 5000, 'adapters': 1, 'console_type': 'telnet', 'image': 'alpine:3.3', 'aux': 5001}
2016-04-05 17:30:06 DEBUG http_client.py:708 Decoding response from http://192.168.1.99:3080/v1/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4/docker/vms response 201
2016-04-05 17:30:06 DEBUG http_client.py:715 {
    "adapters": 1,
    "aux": 5001,
    "console": 5000,
    "console_type": "telnet",
    "container_id": "e455049a58adc71e0a5bf24ac74ebe1d01804b03ed153719e5c8a4b4aeec0f2f",
    "environment": null,
    "image": "alpine:3.3",
    "name": "alpine-1",
    "project_id": "3c1caae3-58d3-4362-9e28-9b3d1980e3f4",
    "start_command": null,
    "vm_directory": "/opt/gns3/projects/3c1caae3-58d3-4362-9e28-9b3d1980e3f4/project-files/docker/9b4c33c1-11cc-4dcd-b86e-005cdc564ffb",
    "vm_id": "9b4c33c1-11cc-4dcd-b86e-005cdc564ffb"
}
2016-04-05 17:30:06 INFO vm.py:184 alpine-1 setting up and updating console from 'None' to '5000'
2016-04-05 17:30:06 INFO vm.py:184 alpine-1 setting up and updating aux from 'None' to '5001'
2016-04-05 17:30:06 INFO vm.py:184 alpine-1 setting up and updating start_command from '' to 'None'
2016-04-05 17:30:06 INFO vm.py:184 alpine-1 setting up and updating environment from '' to 'None'
2016-04-05 17:30:06 DEBUG docker_vm.py:74 Adapter Ethernet0 has been added
2016-04-05 17:30:06 INFO docker_vm.py:288 Docker container alpine-1 has been loaded
2016-04-05 17:30:06 DEBUG topology.py:885 node alpine-1 has initialized
2016-04-05 17:30:06 INFO topology.py:959 Topology initialized
2016-04-05 17:30:06 DEBUG project.py:382 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 2.0, 'cpu_usage_percent': 0.7}}
2016-04-05 17:30:11 DEBUG project.py:382 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 2.0, 'cpu_usage_percent': 0.1}}
2016-04-05 17:30:16 DEBUG project.py:382 Event received: {'action': 'ping', 'event': {'memory_usage_percent': 2.0, 'cpu_usage_percent': 0.0}}
```

**Comment by ehlers** [comment]
It's much simpler:
- start GNS3
- open preference and edit the docker container and change the template name (alpinexyz in my case)
- exit preference with OK

It has nothing to do with the server, it's just an preference editing issue.

**Comment by noplay** [comment]
Thanks for the instructions it's fixed
