### ISSUE TITLE
TypeError: join() argument must be str or bytes, not 'NoneType' when importing config

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1355]
https://app.getsentry.com/gns3/gns3-gui/issues/132560105/

```
TypeError: join() argument must be str or bytes, not 'NoneType'
  File "./gns3-gui\gns3\graphics_view.py", line 1138, in importConfigActionSlot
  File "C:\Users\noplay\AppData\Local\Programs\Python\Python35\lib\ntpath.py", line 113, in join
  File "C:\Users\noplay\AppData\Local\Programs\Python\Python35\lib\genericpath.py", line 143, in _check_arg_types

TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Comment by noplay** [comment]
I'm sure this bug is related to temporary project but I don't see how

**Comment by noplay** [comment]
I added a warning for user asking them to post step to reproduce

**Comment by chandan4raj4** [comment]
trying to upload a zip file using flask-restplus as I did't find any way to upload multiple files at a time.
here is the error : 
Traceback (most recent call last):
  File "/home/chandan/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chandan/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chandan/anaconda3/lib/python3.6/site-packages/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/chandan/anaconda3/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/chandan/anaconda3/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/chandan/workspace/next_get_tooling/zeus/ingestion/python/apis/uploadapp.py", line 55, in post
    f.save(os.path.join('received_data',f))
  File "/home/chandan/anaconda3/lib/python3.6/posixpath.py", line 92, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/chandan/anaconda3/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'FileStorage'

and here is the part of code : 
....
parser.add_argument('file', location='files',type=FileStorage, required=True, help='Upload .zip files')
...
f = flask.request.files['file'] 
#        f.save(os.path.join('received_data',f.filename)) //it is saving zip file without any data inside it

        if (zipfile.is_zipfile(f)):
             f.save(os.path.join('received_data',f)) //error
...

**Comment by grossmj** [comment]
Please open a new issue and tell us what version of GNS3 you have used.

Thanks!

**Comment by gaoyacui** [comment]
D:\anaconda\envs\tensorflow-gpu\lib\site-packages\cwru\__init__.py in __init__(self, exp, rpm, length)
     22                             'Datasets/CWRU',
     23                             'exp',
---> 24                             'rpm')
     25 
     26         fmeta = os.path.join(os.path.dirname(__file__), 'metadata.txt')

TypeError: join() argument must be str or bytes, not 'list'

This complete code of error reporting, I have no problem in pycharm running alone, and in Jupyter call running will report such an error...For your advice. Thank you.
