### ISSUE TITLE
error when remove a cloud interface - GNS3 1.5.2dev1 

### ISSUE THREAD

**Issue by jcmartins** [GNS3/gns3-gui#1383]
.config/GNS3/exceptions.log
=== GNS3 1.5.2dev1 traceback on 13 Jul 2016 17:05:54 ===
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/gns3_gui-1.5.2.dev1-py3.5.egg/gns3/modules/builtin/pages/cloud_configuration_page.py", line 185, in _linuxEthernetDeleteSlot
    self._nios.remove(nio)
KeyError: 'nio_gen_linux:wlp2s0'
=== GNS3 1.5.2dev1 traceback on 13 Jul 2016 17:05:54 ===
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/gns3_gui-1.5.2.dev1-py3.5.egg/gns3/modules/builtin/pages/cloud_configuration_page.py", line 185, in _linuxEthernetDeleteSlot
    self._nios.remove(nio)
KeyError: 'nio_gen_linux:wlp2s0'

**Comment by noplay** [comment]
The interface wlp2s0 exists on your system?

Thanks
