### ISSUE TITLE
Check if port_name_format is not broken in 2.0

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1400]
I didn't test but I have doubt that the port_name_format is not send to the controller and not managed.

Emulators using it:
* [x] Qemu
* [x] VMware
* [x] VirtualBox

**Comment by grossmj** [comment]
Looks like it is project. This is what happens when opening a project containing Qemu VMs:

```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/qt/__init__.py", line 208, in partial
    return func(*args, **kwargs)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/http_client.py", line 553, in _processResponse
    callback(params, server=server, context=context, raw_body=raw_body)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/qt/__init__.py", line 208, in partial
    return func(*args, **kwargs)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/project.py", line 336, in _listNodesCallback
    topo.createNode(node)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/topology.py", line 455, in createNode
    node.createNodeCallback(node_data)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/node.py", line 259, in createNodeCallback
    self._createCallback(result)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/modules/qemu/qemu_vm.py", line 146, in _createCallback
    self._addAdapters(self._settings.get("adapters", 0))
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/modules/qemu/qemu_vm.py", line 102, in _addAdapters
    port_name = self._port_name_format.format(
AttributeError: 'NoneType' object has no attribute 'format'
```
