### ISSUE TITLE
Exception detected with 1.5

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1424]
Hi

When I start GNS3 (even with an empty config) :

```
=== GNS3 1.5.2dev1 traceback on 18 août 2016 08:50:04 ===
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gns3/main_window.py", line 1247, in startupLoading
    "Cancel", busy=True, parent=self)
  File "/usr/local/lib/python3.4/dist-packages/gns3/utils/progress_dialog.py", line 65, in __init__
    self._worker.updated.connect(self._updateProgress)
AttributeError: 'ProgressDialog' object has no attribute '_updateProgress'
```

**Comment by noplay** [comment]
Should be good now. A merge issue
