### ISSUE TITLE
Exception in Project dialog

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1431]
```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/main_window.py", line 1003, in startupLoading
    self._newProjectActionSlot()
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/main_window.py", line 308, in _newProjectActionSlot
    self._project_dialog = ProjectDialog(self)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/dialogs/project_dialog.py", line 43, in __init__
    self.setupUi(self)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/ui/project_dialog_ui.py", line 22, in setupUi
    self.uiProjectTabWidget.setTabBarAutoHide(False)
AttributeError: 'QTabWidget' object has no attribute 'setTabBarAutoHide'
```

setTabBarAutoHide does not exist in Qt 5.2.1 (the one installed on my Ubuntu system). http://doc.qt.io/qt-5/qtabwidget.html#tabBarAutoHide-prop

It has been introduced in Qt 5.4. I think pyuic automatically generated this.

See https://app.getsentry.com/gns3/gns3-gui/issues/151378120/

**Comment by grossmj** [comment]
I removed it for now but we are likely to see it back when the Ui file is build.
