### ISSUE TITLE
Exception if no project created

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1432]
```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/graphics_view.py", line 669, in dropEvent
    self.createNode(node_data, event.pos())
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/graphics_view.py", line 1468, in createNode
    node = node_module.instantiateNode(node_class, self.allocateCompute(node_data, instance), self._topology.project())
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/modules/dynamips/__init__.py", line 250, in instantiateNode
    return node_class(self, server, project)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/modules/dynamips/nodes/c3725.py", line 37, in __init__
    super().__init__(module, server, project, platform="c3725")
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/modules/dynamips/nodes/router.py", line 52, in __init__
    super().__init__(module, server, project)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/node.py", line 35, in __init__
    super().__init__(module, compute, project)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/base_node.py", line 75, in __init__
    assert project is not None
AssertionError
```

Start GNS3, cancel the project dialog, drop a node on the drawing area.

**Comment by noplay** [comment]
Seem to have been fixed by a previous commit.
