### ISSUE TITLE
Can't start a capture when a project is reload

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1457]
```
=> Error while starting capture on link: Port 0 is not connected

**Comment by noplay** [comment]
```
2016-09-02 08:59:58 ERROR route.py:215 Node error detected: VPCSError
Traceback (most recent call last):
  File "/gns3-server/gns3server/web/route.py", line 200, in control_schema
    yield from func(request, response)
  File "/gns3-server/gns3server/handlers/api/compute/vpcs_handler.py", line 251, in start_capture
    yield from vm.start_capture(port_number, pcap_file_path)
  File "/gns3-server/gns3server/compute/vpcs/vpcs_vm.py", line 437, in start_capture
    raise VPCSError("Port {} is not connected".format(port_number))
gns3server.compute.vpcs.vpcs_error.VPCSError: Port 0 is not connected

**Comment by noplay** [comment]
The problem was worst the link nio was not send when the project was reloaded. It's fix now
