### ISSUE TITLE
Exception when drag & drop a node

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1477]
```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/graphics_view.py", line 669, in dropEvent
    self.createNode(node_data, event.pos())
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/graphics_view.py", line 1477, in createNode
    node_item = self.createNodeItem(node, node_data["symbol"], pos.x(), pos.y())
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/graphics_view.py", line 1485, in createNodeItem
    node_item = NodeItem(node)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/items/node_item.py", line 61, in __init__
    self.setZValue(self._node.z())
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/items/node_item.py", line 497, in setZValue
    super().setZValue(value)
TypeError: QGraphicsItem.setZValue(float): argument 1 has unexpected type 'NoneType'
```

**Comment by taurus8** [comment]
i have the same issue for IOU node
![errrrrrr](https://cloud.githubusercontent.com/assets/8465075/18303469/793617d0-74f2-11e6-8943-5bb70ad4ec66.png)

**Comment by noplay** [comment]
Fixed
