### ISSUE TITLE
[Linux/1.5.2] Cannot connect to remote server - no VPN

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#1505]
![remote gns3 server added](https://cloud.githubusercontent.com/assets/13176858/18411598/ef95e89e-777a-11e6-9bf7-a621b0b7c2d5.jpg)
![cannot connect to remote gns3 server](https://cloud.githubusercontent.com/assets/13176858/18411602/fb105b3c-777a-11e6-966e-11f8f6b8399f.jpg)

Despite the fact that the port is open on the remote server & gns3-server is running on that port:
- **gns3-server is running**: 
![gns3-server is running](https://cloud.githubusercontent.com/assets/13176858/18411513/02e3a2f8-7779-11e6-9bf4-96a9f3d2e932.jpg)
- **with that command line**:
/usr/bin/python3 /usr/local/bin/gns3server --host=127.0.0.1 --port=8000 --local --controller --log=/root/.config/GNS3/gns3_server.log --pid=/root/.config/GNS3/gns3_server.pid 
- and that **Gufw rule**:
![gufw gns3 rule](https://cloud.githubusercontent.com/assets/13176858/18411617/4950ed20-777b-11e6-847b-86a70eef9a36.jpg)

**Comment by jean-christophe-manciot** [comment]
**TCP request** from GNS3 to remote GNS3 server: SYN
![tcp request to gns3 server](https://cloud.githubusercontent.com/assets/13176858/18411683/a5c11c3c-777c-11e6-8f41-6225c3d522ef.jpg)
**TCP response** from remote GNS3 server: RESET
![tcp response from gns3 server](https://cloud.githubusercontent.com/assets/13176858/18411691/c483d268-777c-11e6-8fde-6384d05d3291.jpg)

**Comment by noplay** [comment]
Your server listen only on localhost:
> with that command line: /usr/bin/python3 /usr/local/bin/gns3server **--host=127.0.0.1** --port=8000 --local --controller --log=/root/.config/GNS3/gns3_server.log --pid=/root/.config/GNS3/gns3_server.pid

If the remote is started via the GNS3 gui you need to go to server preference and bind the GNS3 server to 0.0.0.0 or an ip in the network. Also in the same page you can turn off auth.

**Comment by jean-christophe-manciot** [comment]
- 0.0.0.0 is not among the choices.
- if I choose to listen on the LAN address, there's the same connection error, even with no authentication and no encryption.
- there is no way to enter any credential if I choose "protect server with password", or is it the local user's password?

**Comment by noplay** [comment]
For 0.0.0.0 your are right we should add it in the list it seem only possible when started from the cli #1506. 

When you bind to an ip does it work if you open it in a browser?

Their is no way to change the password from the interface you need to edit the gns3_server.conf configuration file if you want to replace auto generated.

**Comment by jean-christophe-manciot** [comment]
No, no response from the remote side when accessed from the browser.
Isn't there a GUI way to save the credentials?

**Comment by noplay** [comment]
And from the machine where the remote server run it's work from a browser?

No GUI way to save password.

**Comment by jean-christophe-manciot** [comment]
It's a symmetrical setup.

**Comment by noplay** [comment]
It doesn't seem to listen on the correct ip.

Can you share the content of /root/.config/GNS3/gns3_server.log and on which IP GNS3 need to listen (you can change it in the log if you need to keep it private).

**Comment by jean-christophe-manciot** [comment]
GNS3 server listens on the right IP address, but there is an exception "**Error on transport creation for incoming connection**":
```
2016-09-15 11:05:32 INFO run.py:215 GNS3 server version 1.5.2
2016-09-15 11:05:32 INFO run.py:217 Copyright (c) 2007-2016 GNS3 Technologies Inc.
2016-09-15 11:05:32 INFO run.py:220 Config file /root/.config/GNS3/gns3_server.conf loaded
2016-09-15 11:05:32 INFO run.py:225 Controller mode is enabled.
2016-09-15 11:05:32 WARNING run.py:228 Local mode is enabled. Beware, clients will have full control on your filesystem
2016-09-15 11:05:32 INFO run.py:236 Running with Python 3.5.2 and has PID 20906
2016-09-15 11:05:32 INFO run.py:79 Current locale is en_US.UTF-8
2016-09-15 11:05:32 WARNING port_manager.py:60 Remote console connections are allowed
2016-09-15 11:05:32 INFO server.py:169 SSL is enabled
2016-09-15 11:05:32 INFO server.py:241 Starting server on right_IP_address:right_port
2016-09-15 11:05:32 ERROR base_events.py:1148 Error on transport creation for incoming connection
handle_traceback: Handle created at (most recent call last):
  File "/usr/local/bin/gns3server", line 9, in <module>
    load_entry_point('gns3-server==1.5.2', 'console_scripts', 'gns3server')()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.2-py3.5.egg/gns3server/main.py", line 72, in main
    run()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.2-py3.5.egg/gns3server/run.py", line 255, in run
    server.run()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.5.2-py3.5.egg/gns3server/server.py", line 256, in run
    self._loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1304, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 673, in _read_ready
    keep_open = self._protocol.eof_received()
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 523, in eof_received
    self._wakeup_waiter(ConnectionResetError)
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 446, in _wakeup_waiter
    self._waiter.set_exception(exc)
  File "/usr/lib/python3.5/asyncio/futures.py", line 349, in set_exception
    self._schedule_callbacks()
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
    self._loop.call_soon(callback, self)
protocol: <RequestHandler none:none disconnected>
transport: <asyncio.sslproto._SSLProtocolTransport object at 0x7f07cf954898>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 210, in _accept_connection2
    yield from waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
ConnectionResetError
2016-09-15 13:32:18 WARNING server.py:110 Server has got signal SIGINT, exiting...
2016-09-15 13:32:18 INFO run.py:266 Remove PID file /root/.config/GNS3/gns3_server.pid
```

**Comment by noplay** [comment]
It seem ssl is enable on one side and not on other side

**Comment by jean-christophe-manciot** [comment]
No, as I said, both setup are identical, I just made a test with SSL (rather TLS since SSL is obsolete) on both sides.
As a summary, **no connection with or without 'SSL** on both sides':
1) **no connection without 'SSL' on both sides**:
```
2016-09-16 09:55:30 INFO run.py:215 GNS3 server version 1.5.2
2016-09-16 09:55:30 INFO run.py:217 Copyright (c) 2007-2016 GNS3 Technologies Inc.
2016-09-16 09:55:30 INFO run.py:220 Config file /root/.config/GNS3/gns3_server.conf loaded
2016-09-16 09:55:30 INFO run.py:225 Controller mode is enabled.
2016-09-16 09:55:30 WARNING run.py:228 Local mode is enabled. Beware, clients will have full control on your filesystem
2016-09-16 09:55:30 INFO run.py:236 Running with Python 3.5.2 and has PID 17413
2016-09-16 09:55:30 INFO run.py:79 Current locale is en_US.UTF-8
2016-09-16 09:55:30 WARNING port_manager.py:60 Remote console connections are allowed
2016-09-16 09:55:30 INFO server.py:241 Starting server on correct_IP_address:correct_port
```
2) **no connection with 'SSL' on both sides**:
Same error log (as described on previous post) **on both sides**.
**The exception occurs even though ***only one side is running*****
It seems that the exception has nothing to do with the connection, but with 'SSL' feature.

**Comment by noplay** [comment]
I have no explanation for the 1 and we don't reproduce it on any of our machines.
If the log display the correct IP and port, and firewall are OK, I  don't see why it could fail. Did you try with a different port?

For 2) I reproduce the issue of SSL error if the client communicate over HTTP and not over HTTPS. But SSL errors are pretty obscure, I suspect this could arrive also if OS refuse error due to unsigned certificate.

**Comment by jean-christophe-manciot** [comment]
1) **Without "SSL"**
I've made some progress: 
I had 2 remote servers definitions for the same remote host:
- 1 for http IPv4 port 8000
- 1 for https same IPv4 port 8000

If I remove the second definition and apply the change, and then try to create a new qemu VM definition on that remote host, the error changes to:
![local server error](https://cloud.githubusercontent.com/assets/13176858/18628918/cc83b540-7e62-11e6-8b33-8a9e271e845e.jpg)
The remote gns3_server.log has changed: [gns3_server.log.txt](https://github.com/GNS3/gns3-gui/files/479739/gns3_server.log.txt)

If I delete the first http definition and recreate it with authentication with the remote server credentials (**we should be able to edit it to avoid delete/add**), I get the same error as above.

2) **With "SSL"**
The certificates are self-signed with a local CA.

**Comment by noplay** [comment]
Oh yeah for 1) you need to remove --local from the command line. When removed you can only create project in GNS3 project directory. This is because your are not supposed to open your whole file system to remote access.

It's not common to share a server where a gui is running. Most of the time user dedicate a server to that and start GNS3 server with systemd or upstart.

**Comment by jean-christophe-manciot** [comment]
OK, the connection is done, the image is transferred to the remote server. And I can locally start the node which runs on the remote server. Fantastic  :) Great Job.
Since we can modify its qemu settings once all that is done, it would be a very nice enhancement to be able to done the same for an **already locally defined qemu VM**, i.e. add a line or server tab in edit -> Qemu VM configuration to modify the **server localization: local or remote** with the same parameters as when we define a fresh remote qemu VM.

**Comment by noplay** [comment]
Totaly agree about the localization we should solve that one day in order to make life easier.
