### ISSUE TITLE
Default (hard-coded) VPCS template broken

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1531]
```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/graphics_view.py", line 668, in dropEvent
    self.createNode(node_data, event.pos())
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/graphics_view.py", line 1478, in createNode
    node_module.createNode(node, node_data["name"])
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/modules/vpcs/__init__.py", line 205, in createNode
    "base_script_file": self._settings["base_script_file"]
KeyError: 'base_script_file'
```

**Comment by noplay** [comment]
I do not reproduce the issue. 

I drag the default VPCS to the topology and it's work. I have secured the line but don't see why you have the error. Perhaps something broke in your GNS3 configuration files (I reset mine recently).
