### ISSUE TITLE
[2.0.0dev2] Client Exception

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-gui#1580]
Was just making random changes to my settings and got this. 

Update: actually happens as soon as i opened the settings page. (This was upgrade from 1.5.2 to 2.0.0)

> ****** Exception detected, traceback information saved in C:\Users\Gian-Luca Casella\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\modules\iou\pages\iou_device_preferences_page.py", line 118, in _iouDeviceChangedSlot
>   File "./gns3-gui\gns3\modules\iou\pages\iou_device_preferences_page.py", line 78, in _refreshInfo
>   File "./gns3-gui\gns3\compute_manager.py", line 142, in getCompute
> KeyError: 'Compute http://gns3.casella.local:3080 is missing.'
> 
> ****** Exception detected, traceback information saved in C:\Users\Gian-Luca Casella\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\modules\qemu\pages\qemu_vm_preferences_page.py", line 156, in _qemuVMChangedSlot
>   File "./gns3-gui\gns3\modules\qemu\pages\qemu_vm_preferences_page.py", line 75, in _refreshInfo
>   File "./gns3-gui\gns3\compute_manager.py", line 142, in getCompute
> KeyError: 'Compute http://gns3.casella.local:3080 is missing.'
> 
> ****** Exception detected, traceback information saved in C:\Users\Gian-Luca Casella\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\modules\docker\pages\docker_vm_preferences_page.py", line 97, in _dockerImageChangedSlot
>   File "./gns3-gui\gns3\modules\docker\pages\docker_vm_preferences_page.py", line 70, in _refreshInfo
>   File "./gns3-gui\gns3\compute_manager.py", line 142, in getCompute
> KeyError: 'Compute http://gns3.casella.local:3080 is missing.'

I then get this traceback when dragging an IOU/QEMU (all) images to the topology;

> ****** Exception detected, traceback information saved in C:\Users\Gian-Luca Casella\AppData\Roaming\GNS3\exceptions.log ******
> 
> PLEASE REPORT ON https://www.gns3.com
> 
> Traceback (most recent call last):
>   File "./gns3-gui\gns3\graphics_view.py", line 646, in dropEvent
>   File "./gns3-gui\gns3\graphics_view.py", line 1447, in createNode
>   File "./gns3-gui\gns3\graphics_view.py", line 1415, in allocateCompute
>   File "./gns3-gui\gns3\compute_manager.py", line 142, in getCompute
> KeyError: 'Compute http://gns3.casella.local:3080 is missing.'

**Comment by gcasella** [comment]
Actually, this can be closed, what I did was the following;

1) Took my old config that got converted from 1.5.2 to 2.0.0 
2) Modified each instance of **"server": "http://servername:3080"**, with **"server": "local"**,
3) Imported new config and all worked. 

Will keep testing
