### ISSUE TITLE
AttributeError: 'str' object has no attribute 'id'

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#1594]
https://sentry.io/gns3/gns3-gui/issues/172340856/

```
AttributeError: 'str' object has no attribute 'id'
  File "./gns3-gui/gns3/modules/iou/pages/iou_device_configuration_page.py", line 80, in _iouImageBrowserSlot
  File "./gns3-gui/gns3/modules/iou/pages/iou_device_preferences_page.py", line 267, in getIOUImage
  File "./gns3-gui/gns3/image_manager.py", line 50, in askCopyUploadImage
  File "./gns3-gui/gns3/image_manager.py", line 100, in _uploadImageToRemoteServer

AttributeError: 'str' object has no attribute 'id'
```

**Comment by realfriend** [comment]
I receive the same error when I try to add a QEMU VM in Preferences.

=== GNS3 2.0.0a2 traceback on 21 Oct 2016 18:51:45 ===
Traceback (most recent call last):
  File "./gns3-gui\gns3\dialogs\vm_with_images_wizard.py", line 81, in <lambda>
  File "./gns3-gui\gns3\dialogs\vm_with_images_wizard.py", line 101, in _imageBrowserSlot
  File "./gns3-gui\gns3\modules\qemu\pages\qemu_vm_configuration_page.py", line 154, in getDiskImage
  File "./gns3-gui\gns3\image_manager.py", line 50, in askCopyUploadImage
  File "./gns3-gui\gns3\image_manager.py", line 100, in _uploadImageToRemoteServer
AttributeError: 'str' object has no attribute 'id'

**Comment by noplay** [comment]
Thanks for the reports. This build should fix the issue:
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-10-25/2.0/GNS3-2.0.2016-10-25-all-in-one.exe/download
