### ISSUE TITLE
Qemu image upload in 2.0 Alpha 2 errors out

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-gui#1611]
While attempting to upload a Qemu image using 2.0 Alpha 2, the GUI errors out and image upload is not possible. 

2.0 Alpha 2

![image](https://cloud.githubusercontent.com/assets/6335629/19686319/91a8ce22-9a8e-11e6-9703-9323c2f012b7.png)

``` GNS3 management console.
Running GNS3 version 2.0.0a2 on Windows (64-bit) with Python 3.5.1 Qt 5.7.0 and PyQt 5.7.
Copyright (c) 2006-2016 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Project untitled already exists, overwrite it?
****** Exception detected, traceback information saved in C:\Users\Ariel\AppData\Roaming\GNS3\exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
File "./gns3-gui\gns3\dialogs\vm_with_images_wizard.py", line 81, in 
File "./gns3-gui\gns3\dialogs\vm_with_images_wizard.py", line 101, in _imageBrowserSlot
File "./gns3-gui\gns3\modules\qemu\pages\qemu_vm_configuration_page.py", line 154, in getDiskImage
File "./gns3-gui\gns3\image_manager.py", line 50, in askCopyUploadImage
File "./gns3-gui\gns3\image_manager.py", line 100, in _uploadImageToRemoteServer
AttributeError: 'str' object has no attribute 'id' ```

In 1.5.2, this error is not present.

![image](https://cloud.githubusercontent.com/assets/6335629/19686256/52e68b8e-9a8e-11e6-95cb-97f217e84cb4.png)

**Comment by noplay** [comment]
Thanks it's fixed
https://github.com/GNS3/gns3-gui/issues/1594

You can test this with this build:
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-10-25/2.0/GNS3-2.0.2016-10-25-all-in-one.exe/download

**Comment by codeassassin** [comment]
Thanks. I should do a better job search for dupes before I post, my apologies.

**Comment by noplay** [comment]
No no no. The dupe was not obvious. Honestly I prefer managing dupes than missing something.
