### ISSUE TITLE
GNS3 2.0.0 alpha 3 error running virtual machine (XP)

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#1632]
Windows 10 Prof x64 with 28gig RAM, all latest updates.  VMWare Workstation 12.5.1.  GNS3 2.0.0 alpha 3.  Running all networks object in GNS3 VM created with GNS3 2.0.0 alpha 3 GNS3.ova.
All network objects (IOU, IOS, ASAv, IOSv, etc.) load and configure without problems.  So far IOU, IOS and ASAv run without problems as does the GNS3 VM.

However, I can add a VMWare virtual machine (in this case XP) to a topology but when I start the VMware virtual machine within the topology it starts and is accessible but the following error appears as the virtual machines is starting.

![untitled](https://cloud.githubusercontent.com/assets/10285348/19829669/e6ded308-9db5-11e6-9b6e-1f115b6fcea6.png)

**Comment by jtorri** [comment]
Trying same topology.  GNS3 now simply displays the error message above and does not start the virtual machine, in this case XP.

**Comment by noplay** [comment]
Could you test with this build?
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-11-02/2.0/GNS3-2.0.2016-11-02-all-in-one.exe/download

**Comment by jtorri** [comment]
GNS3-2.0.2016-11-02-all-in-one.exe  GNS3 VM 2.0.0dev4  
Added VMWare Workstation 12.5.1 virtual machine, Lubuntu.  All seemed to be working until I started the network objects.  Then got this.

=> Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 197, in control_schema
  File "./gns3-server\gns3server\handlers\api\controller\node_handler.py", line 124, in start_all
  File "./gns3-server\gns3server\controller\project.py", line 722, in start_all
  File "./gns3-server\gns3server\utils\asyncio\pool.py", line 46, in join
  File "C:\Jenkins\workspace\Nightly Branch Build Windows\Windows\python-3.5.1\lib\asyncio\tasks.py", line 241, in _step
  File "./gns3-server\gns3server\controller\node.py", line 389, in start
  File "./gns3-server\gns3server\controller\node.py", line 424, in post
  File "./gns3-server\gns3server\controller\compute.py", line 524, in post
  File "./gns3-server\gns3server\controller\compute.py", line 354, in http_query
  File "./gns3-server\gns3server\controller\compute.py", line 468, in _run_http_query
  File "C:\Jenkins\workspace\Nightly Branch Build Windows\Windows\python-3.5.1\lib\site-packages\aiohttp\client.py", line 555, in __iter__
  File "C:\Jenkins\workspace\Nightly Branch Build Windows\Windows\python-3.5.1\lib\site-packages\aiohttp\client.py", line 202, in _request
  File "C:\Jenkins\workspace\Nightly Branch Build Windows\Windows\python-3.5.1\lib\site-packages\aiohttp\client_reqrep.py", line 640, in start
  File "C:\Jenkins\workspace\Nightly Branch Build Windows\Windows\python-3.5.1\lib\site-packages\async_timeout\__init__.py", line 44, in __exit__
concurrent.futures._base.TimeoutError

**Comment by noplay** [comment]
Could you test this:
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-11-04/2.0/GNS3-2.0.2016-11-04-all-in-one.exe/download

I'm sorry but we don't reproduce that on our own VMware VMs. But you are not alone.

**Comment by codeassassin** [comment]
@noplay , I am also having issues running VMware VMs inside GNS3. I experienced two issues. 

1)When I go to run the VM, GNS3 appears to dry, unsuccessfully, to install Virtual NICs. However, after losing internet access to my host workstation, I discovered that not only had GNS3 installed a motherload of vnet nic cards, VMware Worstation doesn't recognize the addition of said nvet cards, and it appears that the vnet interfaces I had configured for my other VMware VMs has been overwritten. Major bummer and major headache. 

![gns3networkbug](https://cloud.githubusercontent.com/assets/6335629/20006551/65a44210-a26e-11e6-9fe7-f8d670df4af5.jpg)

![gns3networkbug2](https://cloud.githubusercontent.com/assets/6335629/20006630/d5df7194-a26e-11e6-9fa8-1db1ed72788c.jpg)

2) After cycling through 19 error windows for the vnet nics I really didn't want created, and certainly didn't want overwritten, I right-clicked and attempted to start the VM again. This time, VMware Workstation does begin to start the VM. However, GNS3 waits what appears to be 5 seconds and throws an error that the VM didn't start. Even with an SSD, it's not going to start that fast.

![image](https://cloud.githubusercontent.com/assets/6335629/20006696/2dff94e4-a26f-11e6-8d16-1a94947cf629.png)

**Comment by codeassassin** [comment]
Oh, and I'm running nightly, latest build

**Comment by noplay** [comment]
Can you open a separate issue for the missing DLL. vnetlib64.exe is not a GNS3 program we need to understand if your VMware install is broken or if it's a side  effect of running it from GNS3.

**Comment by jtorri** [comment]
I'm happy to try GNS3-2.0.2016-11-04-all-in-one.exe.  Will let you know ASAP.
I am largely guessing but I am beginning to believe the reason I generate errors you do not has to do with the difference in the way we are configuring GNS3.  But, as I said, it's a guess.

**Comment by jtorri** [comment]
Using GNS3-2.0.2016-11-04-all-in-one.exe
Sorry to say same as before.  Able to add a VMware virtual machine but as soon as I start the network objects get the error.  As I mentioned I suspect I am configuring GNS3 2.0.0 alpha 3 incorrectly.

Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 197, in control_schema
  File "./gns3-server\gns3server\handlers\api\controller\node_handler.py", line 124, in start_all
  File "./gns3-server\gns3server\controller\project.py", line 722, in start_all
  File "./gns3-server\gns3server\utils\asyncio\pool.py", line 46, in join
  File "C:\Jenkins\workspace\Nightly Branch Build Windows\Windows\python-3.5.1\lib\asyncio\tasks.py", line 241, in _step
  File "./gns3-server\gns3server\controller\node.py", line 389, in start
  File "./gns3-server\gns3server\controller\node.py", line 424, in post
  File "./gns3-server\gns3server\controller\compute.py", line 524, in post
  File "./gns3-server\gns3server\controller\compute.py", line 354, in http_query
  File "./gns3-server\gns3server\controller\compute.py", line 468, in _run_http_query
  File "C:\Jenkins\workspace\Nightly Branch Build Windows\Windows\python-3.5.1\lib\site-packages\aiohttp\client.py", line 555, in __iter__
  File "C:\Jenkins\workspace\Nightly Branch Build Windows\Windows\python-3.5.1\lib\site-packages\aiohttp\client.py", line 202, in _request
  File "C:\Jenkins\workspace\Nightly Branch Build Windows\Windows\python-3.5.1\lib\site-packages\aiohttp\client_reqrep.py", line 640, in start
  File "C:\Jenkins\workspace\Nightly Branch Build Windows\Windows\python-3.5.1\lib\site-packages\async_timeout\__init__.py", line 44, in __exit__
concurrent.futures._base.TimeoutError

**Comment by jtorri** [comment]
Again, doubt I'm being much help but.....
Windows 10 Prof 64 bit, all latest OS updates.  Went back to GNS3 2.0.0 alpha 3 and the GNS3 VM.ova 
from that release.  VMWare Workstation 12.5.1
In the topology below the error messages do not appear until I start the Window 7 virtual machine.  If I merely "ignore" the error messages and keep going all seems to work.  Curious?

![topology](https://cloud.githubusercontent.com/assets/10285348/20042764/83ae93b0-a44d-11e6-88e6-1820385a77f9.png)

These are the error messages (there are two "sets").

[ErrorMsg.txt](https://github.com/GNS3/gns3-gui/files/574197/ErrorMsg.txt)

**Comment by jtorri** [comment]
Error msg when Windows virtual machine above is stopped from within GNS3.

[ErrorMsg2.txt](https://github.com/GNS3/gns3-gui/files/574230/ErrorMsg2.txt)

**Comment by jtorri** [comment]
Well, never mind.  I closed the above topology by closing GNS3 and then started GNS3 and opened that topology.  GNS3 did start the GNS3 VM but not the VMware virtual machines.  Back where I was with GNS3 2.0.0 alpha 3

**Comment by jtorri** [comment]
Here's a very similar topology run on the same OS and version of VMWare but with GNS3 1.5.1.  It all works as expected.

![topology151](https://cloud.githubusercontent.com/assets/10285348/20044034/e87de876-a462-11e6-817c-874a49078680.png)

**Comment by jtorri** [comment]
Windows 10 Prof x64. VMWare Workstation 12.5.1.  GNS3-2.0.2016-11-07-all-in-one.exe   GNS3 VM version dev4.  As before all network objects run from inside GNS3 VM.  Windows virtual machines run in VMWare Workstation.  Here's the thing, THIS TOPOLOGY ALL WORKS!  None of the errors I list in previous post on this particular issue occurred.

![topology1172016](https://cloud.githubusercontent.com/assets/10285348/20086558/48829730-a53f-11e6-9afd-48451ebb6ae8.png)

**Comment by noplay** [comment]
Thanks a lot for the help
