### ISSUE TITLE
IdlePC can't be found during setup wizard

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-gui#1693]
2.0.0dev5 on OSX.

Start GNS3 with a blank configuration and use the setup wizard.
Select remote server and enter connection details.
Choose IOS router using Dynamips.
Upload your favorite dynamips image.
Choose any image settings.
Click Idle-PC finder.

Receive an error message "You need to create a project before computing Idle PC".

**Comment by CapnCheapo** [comment]
FYI, same result for running with local server.

**Comment by noplay** [comment]
Fixed, not easy but fixed

**Comment by CapnCheapo** [comment]
When trying this out with 2.0.0dev6, I get the following error:

Server side:
2016-12-12 20:59:17 ERROR route.py:236 Uncaught exception detected: <class 'TypeError'>
Traceback (most recent call last):
  File "/home/moores/gns3-server/gns3server/web/route.py", line 197, in control_schema
    yield from func(request, response)
  File "/home/moores/gns3-server/gns3server/handlers/api/compute/dynamips_vm_handler.py", line 80, in create
    node_type="dynamips")
  File "/home/moores/gns3-server/gns3server/compute/base_manager.py", line 250, in create_node
    node = self._NODE_CLASS(name, node_id, project, self, *args, **kwargs)
TypeError: __new__() got multiple values for argument 'node_type'

Client Side:
2016-12-12 20:59:19 CRITICAL __init__.py:106 Could not create IOS router: Error while setting up node: Internal server error http://192.168.192.10:3080/v2/compute/projects/f34955b5-1562-447c-a327-d4618bb84f89/dynamips/nodes
Stack (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/moores/dev/gns3-gui/gns3/__main__.py", line 20, in <module>
    main()
  File "/Users/moores/dev/gns3-gui/gns3/main.py", line 286, in main
    exit_code = app.exec_()
  File "/Users/moores/dev/gns3-gui/gns3/main_window.py", line 1021, in startupLoading
    self._setupWizardActionSlot()
  File "/Users/moores/dev/gns3-gui/gns3/main_window.py", line 774, in _setupWizardActionSlot
    self._newApplianceActionSlot()
  File "/Users/moores/dev/gns3-gui/gns3/main_window.py", line 330, in _newApplianceActionSlot
    dialog.exec_()
  File "/Users/moores/dev/gns3-gui/gns3/dialogs/new_appliance_dialog.py", line 53, in _okButtonClickedSlot
    self._setPreferencesPane(dialog, "Dynamips").uiNewIOSRouterPushButton.clicked.emit(False)
  File "/Users/moores/dev/gns3-gui/gns3/qt/__init__.py", line 236, in func_wrapper
    return func(*args, **kwargs)
  File "/Users/moores/dev/gns3-gui/gns3/modules/dynamips/pages/ios_router_preferences_page.py", line 99, in _iosRouterNewSlot
    if wizard.exec_():
  File "/Users/moores/dev/gns3-gui/gns3/qt/__init__.py", line 221, in partial
    return func(*args, **kwargs)
  File "/Users/moores/dev/gns3-gui/gns3/http_client.py", line 560, in _processResponse
    callback(json.loads(body), error=True, server=server, context=context)
  File "/Users/moores/dev/gns3-gui/gns3/qt/__init__.py", line 221, in partial
    return func(*args, **kwargs)
  File "/Users/moores/dev/gns3-gui/gns3/node.py", line 259, in createNodeCallback
    self.server_error_signal.emit(self.id(), "Error while setting up node: {}".format(result["message"]))
  File "/Users/moores/dev/gns3-gui/gns3/modules/dynamips/dialogs/ios_router_wizard.py", line 279, in serverErrorSlot
    QtWidgets.QMessageBox.critical(self, "Idle-PC finder", "Could not create IOS router: {}".format(message))
  File "/Users/moores/dev/gns3-gui/gns3/qt/__init__.py", line 106, in critical
    log.critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())

**Comment by noplay** [comment]
Sorry I fix that: https://github.com/gns3/gns3-server/issues/827

On Tue, Dec 13, 2016 at 4:04 AM Stephen C. Moore <notifications@github.com>
wrote:

When trying this out with 2.0.0dev6, I get the following error:

Server side:
2016-12-12 20:59:17 ERROR route.py:236 Uncaught exception detected: <class
'TypeError'>
Traceback (most recent call last):
File "/home/moores/gns3-server/gns3server/web/route.py", line 197, in
control_schema
yield from func(request, response)
File
"/home/moores/gns3-server/gns3server/handlers/api/compute/dynamips_vm_handler.py",
line 80, in create
node_type="dynamips")
File "/home/moores/gns3-server/gns3server/compute/base_manager.py", line
250, in create_node
node = self._NODE_CLASS(name, node_id, project, self, *args, **kwargs)
TypeError: *new*() got multiple values for argument 'node_type'

Client Side:
2016-12-12 20:59:19 CRITICAL *init*.py:106 Could not create IOS router:
Error while setting up node: Internal server error
http://192.168.192.10:3080/v2/compute/projects/f34955b5-1562-447c-a327-d4618bb84f89/dynamips/nodes
Stack (most recent call last):
File
"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py",
line 184, in _run_module_as_main
"*main*", mod_spec)
File
"/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py",
line 85, in




*run_code exec(code, run_globals) File
"/Users/moores/dev/gns3-gui/gns3/main.py", line 20, in main() File
"/Users/moores/dev/gns3-gui/gns3/main.py", line 286, in main exit_code =
app.exec*()
File "/Users/moores/dev/gns3-gui/gns3/main_window.py", line 1021, in
startupLoading
self._setupWizardActionSlot()
File "/Users/moores/dev/gns3-gui/gns3/main_window.py", line 774, in
_setupWizardActionSlot
self._newApplianceActionSlot()
File "/Users/moores/dev/gns3-gui/gns3/main_window.py", line 330, in
*newApplianceActionSlot dialog.exec*()
File "/Users/moores/dev/gns3-gui/gns3/dialogs/new_appliance_dialog.py",
line 53, in _okButtonClickedSlot
self._setPreferencesPane(dialog,
"Dynamips").uiNewIOSRouterPushButton.clicked.emit(False)
File "/Users/moores/dev/gns3-gui/gns3/qt/*init*.py", line 236, in
func_wrapper
return func(*args, **kwargs)
File
"/Users/moores/dev/gns3-gui/gns3/modules/dynamips/pages/ios_router_preferences_page.py",
line 99, in
*iosRouterNewSlot if wizard.exec*():
File "/Users/moores/dev/gns3-gui/gns3/qt/*init*.py", line 221, in partial
return func(*args, **kwargs)
File "/Users/moores/dev/gns3-gui/gns3/http_client.py", line 560, in
_processResponse
callback(json.loads(body), error=True, server=server, context=context)
File "/Users/moores/dev/gns3-gui/gns3/qt/*init*.py", line 221, in partial
return func(*args, **kwargs)
File "/Users/moores/dev/gns3-gui/gns3/node.py", line 259, in
createNodeCallback
self.server_error_signal.emit(self.id(), "Error while setting up node:
{}".format(result["message"]))
File
"/Users/moores/dev/gns3-gui/gns3/modules/dynamips/dialogs/ios_router_wizard.py",
line 279, in serverErrorSlot
QtWidgets.QMessageBox.critical(self, "Idle-PC finder", "Could not create
IOS router: {}".format(message))
File "/Users/moores/dev/gns3-gui/gns3/qt/*init*.py", line 106, in critical
log.critical(re.sub(r"<[^<]+?>", "", message),
stack_info=LogQMessageBox.stack_info())

—
You are receiving this because you modified the open/close state.


Reply to this email directly, view it on GitHub
<https://github.com/GNS3/gns3-gui/issues/1693#issuecomment-266623123>, or mute
the thread
