### ISSUE TITLE
[2.0.0b2] Compute <server> is missing with remote main server

### ISSUE THREAD

**Issue by dmfigol** [GNS3/gns3-gui#1741]
Hi,
I have tried remote main server today with no luck.
My settings:

Enable local server - no
Host: gns3server
Port: 3080 TCP
Enable GNS3 VM - no

Now my previously created IOL nodes are displayed in the routers tabs but they are not working: whenever I drag one of them on the workspace, I see the following traceback in the logs.

```
=== GNS3 2.0.0b2 traceback on 24 Dec 2016 22:34:56 ===
Traceback (most recent call last):
  File "./gns3-gui/gns3/graphics_view.py", line 646, in dropEvent
  File "./gns3-gui/gns3/graphics_view.py", line 1455, in createNode
  File "./gns3-gui/gns3/graphics_view.py", line 1427, in allocateCompute
  File "./gns3-gui/gns3/compute_manager.py", line 165, in getCompute
KeyError: 'Compute http://gns3server:3080 is missing.'
```

**Comment by noplay** [comment]
Hi,

Thanks for the report. What do you have in the remote servers tab in settings?
