### ISSUE TITLE
Exception when adding module to c3600

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#1774]
When adding to slot1 of an existing c3600 node.

```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/dialogs/node_properties_dialog.py", line 159, in on_uiButtonBox_clicked
    self.applySettings()
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/dialogs/node_properties_dialog.py", line 182, in applySettings
    settings = page.saveSettings({}, node, group=True)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/modules/dynamips/pages/ios_router_configuration_page.py", line 605, in saveSettings
    elif settings["slot" + str(slot_number)]:
KeyError: 'slot2'
```

![c3600_bug](https://cloud.githubusercontent.com/assets/4752614/21881706/592d5530-d8e2-11e6-9a79-caf461c14de7.png)

**Comment by grossmj** [comment]
I can't reproduce it anymore... maybe a race condition somewhere?

**Comment by noplay** [comment]
I already seen error like that with 1.5 but not able to reproduce
