### ISSUE TITLE
Unable to create QEMU VM from GNS3 GUI

### ISSUE THREAD

**Issue by ianc1215** [GNS3/gns3-gui#1826]
I am running GNS3 GUI on Windows and the GNS3 VM in VMware Workstation. When I try to create a new QEMU VM in the beta version of GNS3 I am able to get through the initial configuration until I get to the part where QEMU want to provision disk space for the new VM. When I do so GNS3 returns this error to me and tells me to report it.

```
=== GNS3 2.0.0b3 traceback on 30 Jan 2017 17:03:36 ===
Traceback (most recent call last):
  File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
  File "./gns3-gui\gns3\http_client.py", line 599, in _processResponse
gns3.http_client.HttpBadRequest: {
    "message": "Bad request http://192.168.75.2:3080/v2/compute/qemu/img {\n    \"message\": \"Invalid JSON: 'qemu_img' is a required property in schema: {\\\"required\\\": [\\\"qemu_img\\\", \\\"path\\\", \\\"format\\\", \\\"size\\\"], \\\"$schema\\\": \\\"http://json-schema.org/draft-04/schema#\\\", \\\"additionalProperties\\\": false, \\\"type\\\": \\\"object\\\", \\\"description\\\": \\\"Create a new QEMU image. Options can be specific to a format. Read qemu-img manual for more information\\\", \\\"properties\\\": {\\\"subformat\\\": {\\\"enum\\\": [\\\"dynamic\\\", \\\"fixed\\\", \\\"streamOptimized\\\", \\\"twoGbMaxExtentSparse\\\", \\\"twoGbMaxExtentFlat\\\", \\\"monolithicSparse\\\", \\\"monolithicFlat\\\"]}, \\\"preallocation\\\": {\\\"enum\\\": [\\\"off\\\", \\\"metadata\\\", \\\"falloc\\\", \\\"full\\\"]}, \\\"cluster_size\\\": {\\\"type\\\": \\\"integer\\\"}, \\\"size\\\": {\\\"type\\\": \\\"integer\\\", \\\"description\\\": \\\"Image size in Megabytes\\\"}, \\\"lazy_refcounts\\\": {\\\"enum\\\": [\\\"on\\\", \\\"off\\\"]}, \\\"adapter_type\\\": {\\\"enum\\\": [\\\"ide\\\", \\\"lsilogic\\\", \\\"buslogic\\\", \\\"legacyESX\\\"]}, \\\"refcount_bits\\\": {\\\"type\\\": \\\"integer\\\"}, \\\"format\\\": {\\\"description\\\": \\\"Image format type\\\", \\\"enum\\\": [\\\"qcow2\\\", \\\"qcow\\\", \\\"vpc\\\", \\\"vdi\\\", \\\"vmdk\\\", \\\"raw\\\"]}, \\\"static\\\": {\\\"enum\\\": [\\\"on\\\", \\\"off\\\"]}, \\\"path\\\": {\\\"type\\\": \\\"string\\\", \\\"description\\\": \\\"Absolute or relative path of the image\\\"}, \\\"zeroed_grain\\\": {\\\"enum\\\": [\\\"on\\\", \\\"off\\\"]}, \\\"qemu_img\\\": {\\\"type\\\": \\\"string\\\", \\\"description\\\": \\\"Path to the qemu-img binary\\\"}}}\",\n    \"method\": \"POST\",\n    \"path\": \"/v2/compute/qemu/img\",\n    \"request\": {},\n    \"status\": 400\n}",
    "method": "POST",
    "path": "/v2/computes/{compute_id}/{emulator}/{action:.+}",
    "request": {},
    "status": 400
}
```

If any more info is needed I can try to provide whatever is needed.

**Comment by noplay** [comment]
Fixed thanks a lot for the report
