### ISSUE TITLE
IOU - FR Switch Connectors Error

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-gui#1854]
While attempting to set up a frame relay lab, I ran into an issue applying connectors from the FR switch to the IOU devices.

![image](https://cloud.githubusercontent.com/assets/6335629/22953736/7808f802-f2e0-11e6-8299-12b6ea866223.png)

```
GNS3 management console.
Running GNS3 version 2.0.0dev8 on Windows (64-bit) with Python 3.5.2 Qt 5.7.1 and PyQt 5.7.1.
Copyright (c) 2006-2017 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Error while getting settings : Unknown error
You have unsaved preferences in IOU Devices.

Continue without saving?
You have unsaved preferences in IOU Devices.

Continue without saving?
You have unsaved preferences in Server.

Continue without saving?
You have unsaved preferences in IOU Devices.

Continue without saving?
****** Exception detected, traceback information saved in C:\Users\Trent\AppData\Roaming\GNS3\exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
  File "./gns3-gui\gns3\http_client.py", line 587, in _processResponse
  File "./gns3-gui\gns3\qt\__init__.py", line 225, in partial
  File "./gns3-gui\gns3\pages\gns3_vm_preferences_page.py", line 110, in _listEnginesCallback
RuntimeError: wrapped C/C++ object of type QComboBox has been deleted

Error while updating link: Unknown error
Unknown error
Error while getting compute list: Unknown error
Error while creating link: Port 2 is not allocated
Error while creating link: Dynamips error when running command 'frsw create_vc "FR1" udp-ce2bd3f0-fde2-46aa-a6ad-0ff45ffcab36 201 udp-27a4a1dd-b560-44e3-8536-daac5dc38684 102
': unable to create VC

```

**Comment by codeassassin** [comment]
I saved the debug, let me know if you want me to email it to you. Thanks

**Comment by noplay** [comment]
You have always the error whith framerelay or just this time?

**Comment by codeassassin** [comment]
I know there has been a time where I had been able to connect IOU instance to FR switch. Only the IOU and Dynamips have the serial functionality to practice frame relay.

**Comment by codeassassin** [comment]
[ioudebug.zip](https://github.com/GNS3/gns3-gui/files/777527/ioudebug.zip)

**Comment by noplay** [comment]
Can you try the last build ? Because it seem to be fixed:
https://github.com/GNS3/gns3-gui/releases/tag/v2.0.0b4

**Comment by codeassassin** [comment]
I installed the latest nightly build and can confirm that this issue has been successfully resolved. Thank you.

**Comment by noplay** [comment]
Thanks!
