### ISSUE TITLE
Problem when I start GNS3 on Debian 

### ISSUE THREAD

**Issue by elisur3** [GNS3/gns3-gui#1882]
Hi, i have a problem when beginning GNS3 from debian jessie :
elisur@debian:~$ gns3
Traceback (most recent call last):
  File "/usr/local/bin/gns3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cryptography>=1.1
elisur@debian:~$ 
from the terminal gives me that; I hope that you can help me. thanks

**Comment by noplay** [comment]
Hi,

You should install GNS3 using the packages:
https://docs.gns3.com/1QXVIihk7dsOL7Xr7Bmz4zRzTsJ02wklfImGuHwTlaA4/index.html#h.jjmw63r8ciql

**Comment by elisur3** [comment]
Hi
And now, what do you recommend me, uninstall all ??? ...
I hope that you help me.

**Comment by noplay** [comment]
Uninstall all stuff from /usr/local/bin and install the package should solve your issue
