### ISSUE TITLE
[2.0.0rc3] GNS3server startup errros

### ISSUE THREAD

**Issue by MoD01** [GNS3/gns3-gui#1972]
With the current version 2.0.0dev12 or rc3 I get the following errors when running gns3server:
```
sndf@ubuntu:/srv/gns3_installation$ gns3server 
2017-03-31 12:33:32 INFO run.py:215 GNS3 server version 2.0.0dev12
2017-03-31 12:33:32 INFO run.py:217 Copyright (c) 2007-2017 GNS3 Technologies Inc.
2017-03-31 12:33:32 INFO run.py:220 Config file /etc/xdg/GNS3/gns3_server.conf loaded
2017-03-31 12:33:32 INFO run.py:220 Config file /home/sndf/.config/GNS3.conf loaded
2017-03-31 12:33:32 INFO run.py:220 Config file /etc/xdg/GNS3.conf loaded
2017-03-31 12:33:32 INFO run.py:220 Config file /etc/gns3/gns3_server.conf loaded
2017-03-31 12:33:32 INFO run.py:220 Config file /srv/gns3_installation/gns3_server.conf loaded
2017-03-31 12:33:32 INFO run.py:220 Config file /home/sndf/.config/GNS3/gns3_server.conf loaded
2017-03-31 12:33:32 INFO run.py:229 uBridge will be used to handle node connections
2017-03-31 12:33:32 INFO run.py:239 Running with Python 3.5.2 and has PID 2681
2017-03-31 12:33:32 INFO run.py:79 Current locale is de_DE.UTF-8
2017-03-31 12:33:32 INFO web_server.py:257 Starting server on 127.0.0.1:3001
2017-03-31 12:33:32 INFO __init__.py:53 Load controller configuration file /home/sndf/.config/GNS3/gns3_controller.conf
2017-03-31 12:33:32 INFO __init__.py:57 Start controller
2017-03-31 12:33:32 INFO compute.py:78 Create compute local
2017-03-31 12:33:32 CRITICAL run.py:267 Critical error while running the server: 'type'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 686, in _create_direct_connection
    local_addr=self._local_addr)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 695, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.5/asyncio/base_events.py", line 682, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 402, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 432, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 3001)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0dev12_b92f881-py3.5.egg/gns3server/run.py", line 261, in run
    server.run()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0dev12_b92f881-py3.5.egg/gns3server/web/web_server.py", line 260, in run
    if self._run_application(self._handler, ssl_context) is False:
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0dev12_b92f881-py3.5.egg/gns3server/web/web_server.py", line 77, in _run_application
    self._server, startup_res = self._loop.run_until_complete(asyncio.gather(srv, self._app.startup(), loop=self._loop))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/web.py", line 212, in startup
    yield from self.on_startup.send(self)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/signals.py", line 48, in send
    yield from self._send(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/signals.py", line 16, in _send
    yield from res
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0dev12_b92f881-py3.5.egg/gns3server/web/web_server.py", line 194, in _on_startup
    yield from Controller.instance().start()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0dev12_b92f881-py3.5.egg/gns3server/controller/__init__.py", line 92, in start
    yield from self.load_projects()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0dev12_b92f881-py3.5.egg/gns3server/controller/__init__.py", line 190, in load_projects
    yield from self.load_project(os.path.join(project_dir, file), load=False)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0dev12_b92f881-py3.5.egg/gns3server/controller/__init__.py", line 418, in load_project
    topo_data = load_topology(path)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0dev12_b92f881-py3.5.egg/gns3server/controller/topology.py", line 132, in load_topology
    topo = _convert_1_3_later(topo, path)
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-2.0.0dev12_b92f881-py3.5.egg/gns3server/controller/topology.py", line 283, in _convert_1_3_later
    if old_node["type"] == "VPCSDevice":
KeyError: 'type'
/usr/local/lib/python3.5/dist-packages/raven-6.0.0-py3.5.egg/raven/conf/remote.py:88: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
  warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')
2017-03-31 12:33:33 INFO crash_report.py:111 Crash report sent with event ID: 95c28390ecbc4e47931b043d3af600bf

```

**Comment by noplay** [comment]
It seem a problem with one of your old topology  with a unexpected node
type. Try to empty your projects directory before. And readd project one by
one to isolate the culprit.

**Comment by noplay** [comment]
I'm very curious to know which topology create the problem. You can send me by email if you want all your .gns3 file from the project directory I will check the file manually.

**Comment by noplay** [comment]
We have receive a crash report with more details, I think from you:
https://sentry.io/gns3/gns3-server/issues/244875183/ (not public)

The problem seem to be in:
Task1Re.gns3

Could you send me this file to julien@gns3.net?

**Comment by grossmj** [comment]
@MoD01 have you sent the file to Julien?

Thanks,

**Comment by noplay** [comment]
I didn't get anything

**Comment by noplay** [comment]
Seem fixed
