### ISSUE TITLE
[2.0] BUG : ugly message when connect to already connected port

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#1973]
Hi

I connect a device to a ethernet switch

I try to connect an other device to the same port of this ethernet switch.

```
GNS3 shows this message in log console :
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gns3/graphics_view.py", line 420, in mousePressEvent
    self._userNodeLinking(event, item)
  File "/usr/local/lib/python3.4/dist-packages/gns3/graphics_view.py", line 355, in _userNodeLinking
    QtWidgets.QMessageBox.warning(self, "Create link", "Can't create the link the destination port is not free")
  File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 116, in warning
    LogQMessageBox._get_logger().warning(re.sub(r"<[^<]+?>", "", message))
  File "/usr/local/lib/python3.4/dist-packages/gns3/qt/__init__.py", line 128, in _get_logger
    location = "{}:{}".format(os.path.basename(caller.filename), caller.lineno)
AttributeError: 'tuple' object has no attribute 'filename'

```

**Comment by noplay** [comment]
Which version of python are you using?

**Comment by Raizo62** [comment]
python --version
Python 3.4.2

from Debian Jessie Backport

**Comment by noplay** [comment]
Right the function changed in 3.5

**Comment by noplay** [comment]
Fixed
