### ISSUE TITLE
Bug with python before 3.4.3

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2035]
Hi

Sorry, perhaps already corrected, and i don't find it.

With version of yesterday : 

when i start GNS3 on Linux : 

```
=> ****** Exception detected, traceback information saved in /home/user/.config/GNS3/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gns3/main_window.py", line 1032, in startupLoading
    LocalServer.instance().localServerAutoStartIfRequire()
  File "/usr/local/lib/python3.4/dist-packages/gns3/local_server.py", line 319, in localServerAutoStartIfRequire
    if self.isLocalServerRunning() and self._server_started_by_me:
  File "/usr/local/lib/python3.4/dist-packages/gns3/local_server.py", line 514, in isLocalServerRunning
    timeout=2, user=self._settings["user"], password=self._settings["password"])
  File "/usr/local/lib/python3.4/dist-packages/gns3/utils/http.py", line 50, in getSynchronous
    response = urllib.request.urlopen(url, timeout=timeout, context=ctx)
TypeError: urlopen() got an unexpected keyword argument 'context'
 
```

**Comment by noplay** [comment]
Changed in version 3.4.3: context was added.

It's not supported by your version of python we will need to test the version :(

**Comment by noplay** [comment]
Should be fixed

**Comment by Raizo62** [comment]
it works :-)
