### ISSUE TITLE
Auto IdlePC crash

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2103]
```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-venv/lib/python3.5/site-packages/gns3_gui-2.1.0dev1_6a16bce-py3.5.egg/gns3/modules/dynamips/dialogs/ios_router_wizard.py", line 225, in _idlePCFinderSlot
    self._projectCreatedSlot()
  File "/home/grossmj/PycharmProjects/gns3-venv/lib/python3.5/site-packages/gns3_gui-2.1.0dev1_6a16bce-py3.5.egg/gns3/qt/__init__.py", line 256, in func_wrapper
    return func(*args, **kwargs)
  File "/home/grossmj/PycharmProjects/gns3-venv/lib/python3.5/site-packages/gns3_gui-2.1.0dev1_6a16bce-py3.5.egg/gns3/modules/dynamips/dialogs/ios_router_wizard.py", line 244, in _projectCreatedSlot
    self._router.create(ios_image, ram, name="AUTOIDLEPC")
  File "/home/grossmj/PycharmProjects/gns3-venv/lib/python3.5/site-packages/gns3_gui-2.1.0dev1_6a16bce-py3.5.egg/gns3/modules/dynamips/nodes/router.py", line 116, in create
    self._create(name, node_id, params, default_name_format)
AttributeError: 'C3725' object has no attribute '_create'

```

**Comment by noplay** [comment]
Confirmed the bug is still here and easy to reproduce
