### ISSUE TITLE
[Mac gns 2.0.3] when running GNS3.app ,it crashed .

### ISSUE THREAD

**Issue by sdnsalon** [GNS3/gns3-gui#2131]
`mac os version :Sierra 10.12.5`

**[log information]** 
``` bash
soul@souls-MacBook-Pro:~/.config/GNS3$ /Applications/GNS3.app/Contents/MacOS/gns3
2017-06-27 22:47:42 INFO root:126 Log level: INFO
2017-06-27 22:47:42 INFO __main__:252 GNS3 GUI version 2.0.3
2017-06-27 22:47:42 INFO __main__:253 Copyright (c) 2007-2017 GNS3 Technologies Inc.
2017-06-27 22:47:42 INFO __main__:255 Application started with /Applications/GNS3.app/Contents/MacOS/gns3
****** Exception detected, traceback information saved in /Users/soul/.config/GNS3/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com


Traceback (most recent call last):
  File "./gns3-gui/gns3/main_window.py", line 1025, in startupLoading
  File "./gns3-gui/gns3/local_server.py", line 323, in localServerAutoStartIfRequire
  File "./gns3-gui/gns3/local_server.py", line 518, in isLocalServerRunning
  File "./gns3-gui/gns3/utils/http.py", line 48, in getSynchronous
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 466, in open
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 484, in _open
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1282, in http_open
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1257, in do_open
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 319, in begin
http.client.UnknownProtocol: HTTP/0.0

/Applications/GNS3.app/Contents/MacOS/library.zip/raven/conf/remote.py:88: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
2017-06-27 22:47:44 INFO crash_report:107 Crash report sent with event ID: b6ce0f1a21b7485da072d034b12bc9ff

```

> plus :if running gns3server firstly  in terminal ,then run gns3 it can work.

**Comment by noplay** [comment]
Do you have something already listening on the port 3080?

**Comment by sdnsalon** [comment]
> Do you have something already listening on the port 3080?

no ,I change the tcp port 3080 to 3081 or others ,It can not work

**Comment by grossmj** [comment]
Do you have any antivirus or other security suite running on your Mac?

**Comment by sdnsalon** [comment]
@grossmj  thanks for your hints.

I installed lantern when system booted. 
Close the lantern ,it work .

**Comment by grossmj** [comment]
@sdnsalon thanks for the feedback

@julien do you think we can have a less scary crash?

**Comment by noplay** [comment]
Yeah we already have an issue:
https://github.com/GNS3/gns3-gui/issues/2120

But I understand why lantern will listen on all ports and reply to us. We will need to make a clear message that VPN like application could have an impact. This could also explain some trouble of users

**Comment by noplay** [comment]
Duplicate #2120
