### ISSUE TITLE
Error when loading project with Qt 5.8

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2142]
Exception:

```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-venv/lib/python3.5/site-packages/gns3_gui-2.1.0dev1_6a16bce-py3.5.egg/gns3/qt/__init__.py", line 241, in partial
    return func(*args, **kwargs)
  File "/home/grossmj/PycharmProjects/gns3-venv/lib/python3.5/site-packages/gns3_gui-2.1.0dev1_6a16bce-py3.5.egg/gns3/http_client.py", line 649, in _processResponse
    callback(params, server=server, context=context, raw_body=raw_body)
  File "/home/grossmj/PycharmProjects/gns3-venv/lib/python3.5/site-packages/gns3_gui-2.1.0dev1_6a16bce-py3.5.egg/gns3/qt/__init__.py", line 241, in partial
    return func(*args, **kwargs)
  File "/home/grossmj/PycharmProjects/gns3-venv/lib/python3.5/site-packages/gns3_gui-2.1.0dev1_6a16bce-py3.5.egg/gns3/controller.py", line 261, in _getStaticCallback
    callback(path)
  File "/home/grossmj/PycharmProjects/gns3-venv/lib/python3.5/site-packages/gns3_gui-2.1.0dev1_6a16bce-py3.5.egg/gns3/items/node_item.py", line 152, in _symbolLoadedCallback
    self._showLabel()
  File "/home/grossmj/PycharmProjects/gns3-venv/lib/python3.5/site-packages/gns3_gui-2.1.0dev1_6a16bce-py3.5.egg/gns3/items/node_item.py", line 362, in _showLabel
    self._updateLabel()
  File "/home/grossmj/PycharmProjects/gns3-venv/lib/python3.5/site-packages/gns3_gui-2.1.0dev1_6a16bce-py3.5.egg/gns3/items/node_item.py", line 376, in _updateLabel
    self._node_label.setStyle(label_data["style"])
  File "/home/grossmj/PycharmProjects/gns3-venv/lib/python3.5/site-packages/gns3_gui-2.1.0dev1_6a16bce-py3.5.egg/gns3/items/note_item.py", line 204, in setStyle
    font.setPointSize(int(val))
ValueError: invalid literal for int() with base 10: '10.0'
```
Project file:

```
{
    "auto_close": true,
    "auto_open": false,
    "auto_start": false,
    "name": "uBridge_TEST",
    "project_id": "400dfd16-f17e-4314-ba1b-efe98bd735bc",
    "revision": 8,
    "scene_height": 1000,
    "scene_width": 2000,
    "show_grid": false,
    "show_interface_labels": false,
    "show_layers": false,
    "snap_to_grid": false,
    "topology": {
        "computes": [],
        "drawings": [
            {
                "drawing_id": "2ce98a44-5d89-4755-9221-e473ec3ba1f3",
                "rotation": 4,
                "svg": "<svg height=\"28\" width=\"27\"><text fill=\"#000000\" fill-opacity=\"1.0\" font-family=\"Ubuntu\" font-size=\"10\">TEST\n</text></svg>",
                "x": -42,
                "y": -65,
                "z": 1
            }
        ],
        "links": [
            {
                "link_id": "160f9124-9c0f-4564-9b82-70e847deb785",
                "nodes": [
                    {
                        "adapter_number": 0,
                        "label": {
                            "rotation": 0,
                            "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                            "text": "e0",
                            "x": 71,
                            "y": 37
                        },
                        "node_id": "adcb53f6-4962-4d39-9597-2c77a06cf5f4",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 0,
                        "label": {
                            "rotation": 0,
                            "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                            "text": "VPCS1",
                            "x": -8,
                            "y": 17
                        },
                        "node_id": "600b97a4-4260-44a1-b7e5-e30577a6f22a",
                        "port_number": 1
                    }
                ]
            },
            {
                "link_id": "bfde281a-0bf1-446f-9435-9e7e17ea27c4",
                "nodes": [
                    {
                        "adapter_number": 0,
                        "label": {
                            "rotation": 0,
                            "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                            "text": "e0",
                            "x": -7,
                            "y": 34
                        },
                        "node_id": "18420299-6218-4ff8-84ac-52b21d84cce3",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 0,
                        "label": {
                            "rotation": 0,
                            "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                            "text": "VPCS2",
                            "x": 168,
                            "y": 23
                        },
                        "node_id": "600b97a4-4260-44a1-b7e5-e30577a6f22a",
                        "port_number": 2
                    }
                ]
            }
        ],
        "nodes": [
            {
                "compute_id": "local",
                "console": null,
                "console_type": null,
                "first_port_name": null,
                "height": 32,
                "label": {
                    "rotation": 0,
                    "style": "font-family: Ubuntu;font-size: 16.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "Ethernethub-1",
                    "x": 72,
                    "y": -20
                },
                "name": "Ethernethub-1",
                "node_id": "4c9da62c-7588-433a-bbe3-e39f6ccafab5",
                "node_type": "ethernet_hub",
                "port_name_format": "Ethernet{0}",
                "port_segment_size": 0,
                "properties": {
                    "ports_mapping": [
                        {
                            "name": "Ethernet0",
                            "port_number": 0
                        },
                        {
                            "name": "Ethernet1",
                            "port_number": 1
                        },
                        {
                            "name": "Ethernet2",
                            "port_number": 2
                        },
                        {
                            "name": "Ethernet3",
                            "port_number": 3
                        },
                        {
                            "name": "Ethernet4",
                            "port_number": 4
                        },
                        {
                            "name": "Ethernet5",
                            "port_number": 5
                        },
                        {
                            "name": "Ethernet6",
                            "port_number": 6
                        },
                        {
                            "name": "Ethernet7",
                            "port_number": 7
                        }
                    ]
                },
                "symbol": ":/symbols/hub.svg",
                "width": 72,
                "x": -119,
                "y": -11,
                "z": 0
            },
            {
                "compute_id": "local",
                "console": 5005,
                "console_type": "telnet",
                "first_port_name": null,
                "height": 59,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "VPCS-2",
                    "x": -26,
                    "y": -38
                },
                "name": "VPCS-2",
                "node_id": "18420299-6218-4ff8-84ac-52b21d84cce3",
                "node_type": "vpcs",
                "port_name_format": "Ethernet{0}",
                "port_segment_size": 0,
                "properties": {},
                "symbol": ":/symbols/vpcs_guest.svg",
                "width": 65,
                "x": 93,
                "y": -215,
                "z": 0
            },
            {
                "compute_id": "local",
                "console": null,
                "console_type": null,
                "first_port_name": null,
                "height": 71,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "Cloud-1",
                    "x": 14,
                    "y": -47
                },
                "name": "Cloud-1",
                "node_id": "600b97a4-4260-44a1-b7e5-e30577a6f22a",
                "node_type": "cloud",
                "port_name_format": "Ethernet{0}",
                "port_segment_size": 0,
                "properties": {
                    "interfaces": [
                        {
                            "name": "lo",
                            "special": true,
                            "type": "ethernet"
                        },
                        {
                            "name": "vmnet1",
                            "special": true,
                            "type": "ethernet"
                        },
                        {
                            "name": "vmnet2",
                            "special": true,
                            "type": "ethernet"
                        },
                        {
                            "name": "vmnet3",
                            "special": true,
                            "type": "ethernet"
                        },
                        {
                            "name": "vmnet4",
                            "special": true,
                            "type": "ethernet"
                        },
                        {
                            "name": "vmnet8",
                            "special": true,
                            "type": "ethernet"
                        },
                        {
                            "name": "wlp58s0",
                            "special": false,
                            "type": "ethernet"
                        }
                    ],
                    "ports_mapping": [
                        {
                            "interface": "wlp58s0",
                            "name": "wlp58s0",
                            "port_number": 0,
                            "type": "ethernet"
                        },
                        {
                            "lport": 30000,
                            "name": "VPCS1",
                            "port_number": 1,
                            "rhost": "127.0.0.1",
                            "rport": 20000,
                            "type": "udp"
                        },
                        {
                            "lport": 30001,
                            "name": "VPCS2",
                            "port_number": 2,
                            "rhost": "127.0.0.1",
                            "rport": 20001,
                            "type": "udp"
                        }
                    ]
                },
                "symbol": ":/symbols/cloud.svg",
                "width": 159,
                "x": -358,
                "y": -168,
                "z": 0
            },
            {
                "compute_id": "local",
                "console": 5002,
                "console_type": "telnet",
                "first_port_name": null,
                "height": 59,
                "label": {
                    "rotation": 0,
                    "style": "font-family: TypeWriter;font-size: 10.0;font-weight: bold;fill: #000000;fill-opacity: 1.0;",
                    "text": "VPCS-1",
                    "x": -28,
                    "y": -40
                },
                "name": "VPCS-1",
                "node_id": "adcb53f6-4962-4d39-9597-2c77a06cf5f4",
                "node_type": "vpcs",
                "port_name_format": "Ethernet{0}",
                "port_segment_size": 0,
                "properties": {},
                "symbol": ":/symbols/vpcs_guest.svg",
                "width": 65,
                "x": -639,
                "y": -227,
                "z": 0
            }
        ]
    },
    "type": "topology",
    "version": "2.1.0dev1-dab7569",
    "zoom": 100
}
```

**Comment by grossmj** [comment]
This has been fixed already.
