### ISSUE TITLE
Runnig gns3 failed

### ISSUE THREAD

**Issue by jssbbonilla** [GNS3/gns3-gui#2268]
i've tried to install gns3 several times....but never work! any help? arch linux by the way...

using pip3 , yaourt , zip files...

`Traceback (most recent call last):
  File "/usr/bin/gns3", line 11, in <module>
    load_entry_point('gns3-gui==2.0.3', 'gui_scripts', 'gns3')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/gns3/main.py", line 57, in <module>
    from gns3.crash_report import CrashReport
  File "/usr/lib/python3.6/site-packages/gns3/crash_report.py", line 25, in <module>
    import raven
  File "/usr/lib/python3.6/site-packages/raven/__init__.py", line 54, in <module>
    from raven.base import *  # NOQA
  File "/usr/lib/python3.6/site-packages/raven/base.py", line 31, in <module>
    from thread import get_ident as get_thread_ident
  File "/usr/lib/python3.6/site-packages/thread.py", line 3
    print('This is ultran00b's package - thread')
                             ^
SyntaxError: invalid syntax
`

**Comment by grossmj** [comment]
Can you start Python command line and type `import thread`? Please post the output here.

Thanks!

**Comment by jssbbonilla** [comment]
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/thread.py", line 3
    print('This is ultran00b's package - thread')
                             ^
SyntaxError: invalid syntax
`

**Comment by jssbbonilla** [comment]
with this :  pip3 uninstall thread .......everything seems to go well.....but I think that is not the best solution.

**Comment by grossmj** [comment]
Can you try the following command instead `sudo pip3 install raven==6.1.0`?

**Comment by jssbbonilla** [comment]
Requirement already satisfied: raven==6.1.0 in /usr/lib/python3.6/site-packages....

**Comment by grossmj** [comment]
Can you manually start the Python 3.6 command line (python3 or python3.6) and type `import raven`?

**Comment by jssbbonilla** [comment]
everything seems to go well......`>>> import raven
>>> 
`

**Comment by jssbbonilla** [comment]
i am no sure ....but may i have installed ( with pip) some stuff that get "bad" with raven for example.....as i said before, i have used `pip3 uninstall thread` and gns3 is working now.....

**Comment by grossmj** [comment]
Ok, thank you!

**Comment by jssbbonilla** [comment]
Thank you!
