### ISSUE TITLE
gns3server error during startup

### ISSUE THREAD

**Issue by DuNd3** [GNS3/gns3-gui#2278]
Running Kali linux as main OS. Latest version of GNS3 and dependency files.
When i try running GNS3 it tries to connect to 127.0.0.1 port 8000 and fails. Tried changing it to 9000 still fails. Been trying different methods from others, tried looking deeper into the error it showed but dont have a decent enough understanding to workout why its failing. Ran gns3server and this was the result:

root@conbox:~# gns3server
2017-09-29 21:04:10 INFO main.py:157 GNS3 server version 1.3.13
2017-09-29 21:04:10 INFO main.py:159 Copyright (c) 2007-2017 GNS3 Technologies Inc.
2017-09-29 21:04:10 INFO main.py:162 Config file /root/.config/GNS3/gns3_server.conf loaded
2017-09-29 21:04:10 INFO main.py:175 Running with Python 3.5.4 and has PID 3714
2017-09-29 21:04:10 INFO main.py:82 Current locale is en_AU.UTF-8
2017-09-29 21:04:10 INFO server.py:231 Starting server on 127.0.0.1:9000
2017-09-29 21:04:10 CRITICAL main.py:205 Critical error while running the server: __init__() got multiple values for argument 'handler'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.3.13-py3.5.egg/gns3server/main.py", line 199, in main
    server.run()
  File "/usr/local/lib/python3.5/dist-packages/gns3_server-1.3.13-py3.5.egg/gns3server/server.py", line 232, in run
    self._handler = app.make_handler(handler=RequestHandler)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp-2.2.5-py3.5-linux-x86_64.egg/aiohttp/web.py", line 251, in make_handler
    loop=self.loop, **kwargs)
TypeError: __init__() got multiple values for argument 'handler'
/usr/local/lib/python3.5/dist-packages/raven-6.2.1-py3.5.egg/raven/conf/remote.py:88: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
  warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')
2017-09-29 21:04:11 ERROR crash_report.py:98 Can't send crash report to Sentry: ('API key is disabled', 401)

**Comment by grossmj** [comment]
I see you have used an old GNS3 version: `GNS3 server version 1.3.13`

Can you try with version 2.0.3 (stable) or 2.1 rc1 (unstable)?

Thanks,

**Comment by DuNd3** [comment]
Issue fixed. 

When trying to update it wouldn't show the new version when running. So uninstalled and was still able to run it. Turns out the files in /usr/bin were running independently in some way. So once manually removed and reinstalled everything worked.

**Comment by grossmj** [comment]
Thanks for the feedback :)
