### ISSUE TITLE
Exception when adding image

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#2285]
As reported on https://gns3.com/qa/not-able-to-insert-picture-in-gn

```
Traceback (most recent call last): 
File "./gns3-gui\gns3\qt\__init__.py", line 241, in partial 
File "./gns3-gui\gns3\http_client.py", line 652, in _processResponse 
File "./gns3-gui\gns3\qt\__init__.py", line 241, in partial 
File "./gns3-gui\gns3\project.py", line 399, in _listDrawingsCallback 
File "./gns3-gui\gns3\topology.py", line 550, in createDrawing 
File "./gns3-gui\gns3\graphics_view.py", line 1486, in createDrawingItem 
File "./gns3-gui\gns3\items\image_item.py", line 53, in __init__ 
File "./gns3-gui\gns3\items\image_item.py", line 68, in fromSvg 
File "./gns3-gui\gns3\qt\qimage_svg_renderer.py", line 41, in __init__ 
File "./gns3-gui\gns3\qt\qimage_svg_renderer.py", line 56, in load 
File "C:\Python36-x64\lib\genericpath.py", line 19, in exists 
ValueError: stat: path too long for Windows 
```

**Comment by grossmj** [comment]
We have fixed that issue already: https://github.com/GNS3/gns3-gui/issues/2129
