### ISSUE TITLE
Not able to start GNS3

### ISSUE THREAD

**Issue by sachinsebastian** [GNS3/gns3-gui#2323]
HI Team,

I am new to kali linux, i am a network enigneer who loves to learn kali linux,i have installed kali on my pc and i was trying to install gns3,but i am not able to start now.the local server connection fails.
I have installed my gns3 using https://gns3.com/discussions/how-install-gns3-on-kali-linux
and later 
tried installing 

sudo pip3 install gns3-server
sudo pip3 install gns3-server

Seems like my gns3 got upgraded by still not able to connect to my local server:
it seems i have messed up my gns3 completely

This is what i am getting::
Please help :(
oot@kali:~# gns3
your locale en_IN.ISO8859-1 encoding is not UTF-8, switching to the UTF-8 version...
2017-11-04 11:03:10 INFO root:126 Log level: INFO
2017-11-04 11:03:10 INFO main:252 GNS3 GUI version 2.0.3
2017-11-04 11:03:10 INFO main:253 Copyright (c) 2007-2017 GNS3 Technologies Inc.
2017-11-04 11:03:10 INFO main:255 Application started with /usr/local/bin/gns3
2017-11-04 11:03:11 WARNING main_window.py:1004 Running GNS3 as root is not recommended and could be dangerous
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
2017-11-04 11:03:46 INFO local_server:470 Starting local server process with "/usr/local/bin/gns3server" --local --log="/root/.config/GNS3/gns3_server.log" --pid="/root/.config/GNS3/gns3_server.pid"
2017-11-04 11:03:46 INFO local_server:483 Local server process has started (PID=32312)
2017-11-04 11:03:50 ERROR local_server:489 Local server process has stopped
2017-11-04 11:03:50 ERROR local_server:491 /usr/local/lib/python3.6/dist-packages/raven-6.3.0-py3.6.egg/raven/conf/remote.py:88: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
  warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')

2017-11-04 11:04:16 CRITICAL utils.progress_dialog:172 WaitForConnectionWorker thread stopping with an error: Could not connect to 127.0.0.1 on port 8000: [Errno 111] Connection refused
2017-11-04 11:04:17 CRITICAL progress_dialog.py:173 Could not connect to 127.0.0.1 on port 8000: [Errno 111] Connection refused
2017-11-04 11:09:31 INFO http_client:312 Connection to http://127.0.0.1:8000
2017-11-04 11:09:31 INFO local_server:470 Starting local server process with "/usr/local/bin/gns3server" --local --log="/root/.config/GNS3/gns3_server.log" --pid="/root/.config/GNS3/gns3_server.pid"
2017-11-04 11:09:31 INFO local_server:483 Local server process has started (PID=32412)
2017-11-04 11:09:34 INFO local_server:470 Starting local server process with "/usr/local/bin/gns3server" --local --log="/root/.config/GNS3/gns3_server.log" --pid="/root/.config/GNS3/gns3_server.pid"
2017-11-04 11:09:34 INFO local_server:483 Local server process has started (PID=32418)
2017-11-04 11:09:35 INFO local_config:423 Section MainWindow has changed. Saving configuration
2017-11-04 11:09:35 INFO local_config:299 Configuration save to /root/.config/GNS3/gns3_gui.conf
2017-11-04 11:09:40 ERROR local_server:489 Local server process has stopped
2017-11-04 11:09:40 ERROR local_server:491 GNS3 is already running pid: 32412

2017-11-04 11:09:42 INFO http_client:312 Connection to http://127.0.0.1:8000
2017-11-04 11:09:42 INFO local_config:423 Section MainWindow has changed. Saving configuration
2017-11-04 11:09:42 INFO local_config:299 Configuration save to /root/.config/GNS3/gns3_gui.conf
root@kali:~# ^C
oot@kali:~# gns3
your locale en_IN.ISO8859-1 encoding is not UTF-8, switching to the UTF-8 version...
2017-11-04 11:03:10 INFO root:126 Log level: INFO
2017-11-04 11:03:10 INFO main:252 GNS3 GUI version 2.0.3
2017-11-04 11:03:10 INFO main:253 Copyright (c) 2007-2017 GNS3 Technologies Inc.
2017-11-04 11:03:10 INFO main:255 Application started with /usr/local/bin/gns3
2017-11-04 11:03:11 WARNING main_window.py:1004 Running GNS3 as root is not recommended and could be dangerous
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
2017-11-04 11:03:46 INFO local_server:470 Starting local server process with "/usr/local/bin/gns3server" --local --log="/root/.config/GNS3/gns3_server.log" --pid="/root/.config/GNS3/gns3_server.pid"
2017-11-04 11:03:46 INFO local_server:483 Local server process has started (PID=32312)
2017-11-04 11:03:50 ERROR local_server:489 Local server process has stopped
2017-11-04 11:03:50 ERROR local_server:491 /usr/local/lib/python3.6/dist-packages/raven-6.3.0-py3.6.egg/raven/conf/remote.py:88: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
  warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')

2017-11-04 11:04:16 CRITICAL utils.progress_dialog:172 WaitForConnectionWorker thread stopping with an error: Could not connect to 127.0.0.1 on port 8000: [Errno 111] Connection refused
2017-11-04 11:04:17 CRITICAL progress_dialog.py:173 Could not connect to 127.0.0.1 on port 8000: [Errno 111] Connection refused
2017-11-04 11:09:31 INFO http_client:312 Connection to http://127.0.0.1:8000
2017-11-04 11:09:31 INFO local_server:470 Starting local server process with "/usr/local/bin/gns3server" --local --log="/root/.config/GNS3/gns3_server.log" --pid="/root/.config/GNS3/gns3_server.pid"
2017-11-04 11:09:31 INFO local_server:483 Local server process has started (PID=32412)
2017-11-04 11:09:34 INFO local_server:470 Starting local server process with "/usr/local/bin/gns3server" --local --log="/root/.config/GNS3/gns3_server.log" --pid="/root/.config/GNS3/gns3_server.pid"
2017-11-04 11:09:34 INFO local_server:483 Local server process has started (PID=32418)
2017-11-04 11:09:35 INFO local_config:423 Section MainWindow has changed. Saving configuration
2017-11-04 11:09:35 INFO local_config:299 Configuration save to /root/.config/GNS3/gns3_gui.conf
2017-11-04 11:09:40 ERROR local_server:489 Local server process has stopped
2017-11-04 11:09:40 ERROR local_server:491 GNS3 is already running pid: 32412

2017-11-04 11:09:42 INFO http_client:312 Connection to http://127.0.0.1:8000
2017-11-04 11:09:42 INFO local_config:423 Section MainWindow has changed. Saving configuration
2017-11-04 11:09:42 INFO local_config:299 Configuration save to /root/.config/GNS3/gns3_gui.conf
root@kali:~# ^C

**Comment by WhiteWinterWolf** [comment]
The GNS3 server seems to fail to start, you can try to check if there is some more information in the server log (*~/.config/GNS3/gns3_server.log*), but I don't like this message:

    2017-11-04 11:03:50 ERROR local_server:491 /usr/local/lib/python3.6/dist-packages/raven-6.3.0-py3.6.egg/raven/conf/remote.py:88: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.

This message however is not clear, as it says that the feature is *deprecated*, but at the same it is raised as an *ERROR* instead of a *WARNING*, but most chances are that this message is just a consequence (the root error occurred, then Raven tried to report it but also failed).

**Comment by sachinsebastian** [comment]
Hi White winter wolf thanks for commending,is there any way to fix this ? i was having this issue when i was using 2017.1 ver so i upgraded my os to 2017.2 but issue still remains...please let me know how to fix this...



root@kali:~# ~/.config/GNS3/gns3_server.log
bash: /root/.config/GNS3/gns3_server.log: Permission denied

**Comment by WhiteWinterWolf** [comment]
Hi,

*gns3_server.log* is a log file, you must open it with a text editor (it is not executable).

The discussion you are pointing to is rather old. The issue you encounter *may* come from the fact that different version of some Python libraries is installed on Kali than the one expected by GNS3.

If this is indeed the case, you have the choice between:

- Rollbacking some libraries to the version expected by GNS3 system-wide, but this is likely to break other things on your system.

- Using Python virtual environments to properly solve the dependencies issues.

- Use a general purpose system as GNS3 host.

Personally, I don't see how GNS3 may fit as part of a penetration testing or forensic tool, so I would go for the third solution (it will be both easier and more secure, `2017-11-04 11:03:11 WARNING main_window.py:1004 Running GNS3 as root is not recommended and could be dangerous`). Feel free then to use Kali as a guest inside your GNS3 topologies to train your pentesting skills.

**Comment by sachinsebastian** [comment]
So you are recommending me to leave Kali and get windows ? My aim was to just practice my networking labs on linux learn kali linux..i was not planning to do practice penetration testing with GNS3..windows kills my cpu and ram too much....is there any way to run GNS3 on my kali linux?can you please guide me ?

**Comment by sachinsebastian** [comment]
This is the output 

root@kali:~# leafpad ~/.config/GNS3/gns3_server.log

2017-11-04 12:28:27 INFO run.py:195 GNS3 server version 1.4.0beta1
2017-11-04 12:28:27 INFO run.py:197 Copyright (c) 2007-2017 GNS3 Technologies Inc.
2017-11-04 12:28:27 INFO run.py:200 Config file /root/.config/GNS3/gns3_server.conf loaded
2017-11-04 12:28:27 WARNING run.py:205 Local mode is enabled. Beware, clients will have full control on your filesystem
2017-11-04 12:28:27 INFO run.py:213 Running with Python 3.6.3 and has PID 2079
2017-11-04 12:28:27 WARNING run.py:71 Your locale en_IN.ISO8859-1 encoding is not UTF-8, switching to the UTF-8 version...
2017-11-04 12:28:27 INFO server.py:233 Starting server on 127.0.0.1:8000
2017-11-04 12:28:27 CRITICAL run.py:238 Critical error while running the server: __init__() got multiple values for argument 'handler'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gns3_server-1.4.0b1-py3.6.egg/gns3server/run.py", line 232, in run
    server.run()
  File "/usr/local/lib/python3.6/dist-packages/gns3_server-1.4.0b1-py3.6.egg/gns3server/server.py", line 234, in run
    self._handler = app.make_handler(handler=RequestHandler)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp-2.3.2-py3.6-linux-x86_64.egg/aiohttp/web.py", line 255, in make_handler
    loop=self.loop, **kwargs)
TypeError: __init__() got multiple values for argument 'handler'
2017-11-04 12:28:29 ERROR crash_report.py:106 Can't send crash report to Sentry: ('API key is disabled', 401)

**Comment by sachinsebastian** [comment]
oot@kali:~# gns3 --debug
your locale en_IN.ISO8859-1 encoding is not UTF-8, switching to the UTF-8 version...
2017-11-07 17:39:20 INFO root:126 Log level: DEBUG
2017-11-07 17:39:20 INFO main:252 GNS3 GUI version 2.0.3
2017-11-07 17:39:20 INFO main:253 Copyright (c) 2007-2017 GNS3 Technologies Inc.
2017-11-07 17:39:20 INFO main:255 Application started with /usr/local/bin/gns3--debug
2017-11-07 17:39:20 DEBUG utils.analytics:123 Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=f609aa91-e3ba-41a6-a862-4a9e93d40002&aip=1&t=screenview&an=GNS3&av=2.0.3&ua=Mozilla/5.0%20%28X11%3B%20Linux%20x86_64%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20%20GNS3/2.0.3&cd=Main%20Window&ds=gns3-gui&sr=1366x768&ul=en_in
2017-11-07 17:39:20 WARNING main_window.py:1004 Running GNS3 as root is not recommended and could be dangerous
2017-11-07 17:39:22 DEBUG utils.analytics:123 Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=f609aa91-e3ba-41a6-a862-4a9e93d40002&aip=1&t=screenview&an=GNS3&av=2.0.3&ua=Mozilla/5.0%20%28X11%3B%20Linux%20x86_64%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20%20GNS3/2.0.3&cd=Main%20Window&ds=gns3-gui&sr=1366x768&ul=en_in
2017-11-07 17:39:22 DEBUG utils.analytics:123 Send stats to Google Analytics: v=1&tid=UA-55817127-3&cid=f609aa91-e3ba-41a6-a862-4a9e93d40002&aip=1&t=screenview&an=GNS3&av=2.0.3&ua=Mozilla/5.0%20%28X11%3B%20Linux%20x86_64%29%20AppleWebKit/537.36%20%28KHTML%2C%20like%20Gecko%29%20Safari/537.36%20%20GNS3/2.0.3&cd=Setup%20Wizard&ds=gns3-gui&sr=1366x768&ul=en_in
2017-11-07 17:39:33 DEBUG utils.http:38 Synchronous get http://127.0.0.1:8000/v2/version with user 'Di6inQT2v9OpvH3mtubcdIHQg1Va5bStCDtEBhMbyGezLrU5NovFneeg4NGxIYTp'
2017-11-07 17:39:33 DEBUG utils.http:38 Synchronous get http://127.0.0.1:8000/v2/version with user 'Di6inQT2v9OpvH3mtubcdIHQg1Va5bStCDtEBhMbyGezLrU5NovFneeg4NGxIYTp'
2017-11-07 17:39:33 DEBUG utils.http:38 Synchronous get http://127.0.0.1:8000/v2/version with user 'Di6inQT2v9OpvH3mtubcdIHQg1Va5bStCDtEBhMbyGezLrU5NovFneeg4NGxIYTp'
2017-11-07 17:39:33 INFO local_server:470 Starting local server process with "/usr/local/bin/gns3server" --local --debug --log="/root/.config/GNS3/gns3_server.log" --pid="/root/.config/GNS3/gns3_server.pid"
2017-11-07 17:39:33 INFO local_server:483 Local server process has started (PID=9231)
2017-11-07 17:39:33 DEBUG utils.progress_dialog:106 WaitForConnectionWorker thread started
2017-11-07 17:39:40 ERROR local_server:489 Local server process has stopped
2017-11-07 17:39:40 ERROR local_server:491 /usr/local/lib/python3.6/dist-packages/raven-6.3.0-py3.6.egg/raven/conf/remote.py:88: UserWarning: Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.
  warnings.warn('Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead.')

2017-11-07 17:40:03 CRITICAL utils.progress_dialog:172 WaitForConnectionWorker thread stopping with an error: Could not connect to 127.0.0.1 on port 8000: [Errno 111] Connection refused
2017-11-07 17:40:03 CRITICAL progress_dialog.py:173 Could not connect to 127.0.0.1 on port 8000: [Errno 111] Connection refused
Stack (most recent call last):
  File "/usr/local/bin/gns3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/gns3/main.py", line 287, in main
    exit_code = app.exec_()
  File "/usr/local/lib/python3.6/dist-packages/gns3/main_window.py", line 1022, in startupLoading
    self._setupWizardActionSlot()
  File "/usr/local/lib/python3.6/dist-packages/gns3/main_window.py", line 782, in _setupWizardActionSlot
    res = setup_wizard.exec_()
  File "/usr/local/lib/python3.6/dist-packages/gns3/dialogs/setup_wizard.py", line 327, in validateCurrentPage
    LocalServer.instance().localServerAutoStartIfRequire()
  File "/usr/local/lib/python3.6/dist-packages/gns3/local_server.py", line 355, in localServerAutoStartIfRequire
    if not progress_dialog.exec_():
  File "/usr/local/lib/python3.6/dist-packages/gns3/qt/__init__.py", line 256, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/gns3/utils/progress_dialog.py", line 173, in _error
    QtWidgets.QMessageBox.critical(self.parentWidget(), "Error", "{}".format(message))
  File "/usr/local/lib/python3.6/dist-packages/gns3/qt/__init__.py", line 109, in critical
    LogQMessageBox._get_logger().critical(re.sub(r"<[^<]+?>", "", message), stack_info=LogQMessageBox.stack_info())
2017-11-07 17:40:07 DEBUG utils.progress_dialog:115 WaitForConnectionWorker thread canceled
2017-11-07 17:40:07 DEBUG utils.progress_dialog:140 WaitForConnectionWorker thread is being destroyed
2017-11-07 17:40:07 DEBUG utils.progress_dialog:147 WaitForConnectionWorker thread destroyed

**Comment by WhiteWinterWolf** [comment]
> So you are recommending me to leave Kali and get windows ? My aim was to just practice my networking labs on linux learn kali linux..i was not planning to do practice penetration testing with GNS3..windows kills my cpu and ram too much....is there any way to run GNS3 on my kali linux?can you please guide me ?

While I'm indeed recommending to leave Kali as a GNS3 host, I'm not recommending to leave Linux altogether.

Kali is a pentesting and forensic tool, and has been designed and modified precisely toward these goals. Trying to use it for anything else is like trying to use a hammer to put in a screw: you can still ask people how to achieve this, but the most sensible advice you will get is to use a screwdriver instead.

There are hundreds of active Linux distributions out-there, each with a different spirit and targeting different goals. A good place to start is the Distrowatch website, and in particular their selection of distributions tagged [Beginners](https://distrowatch.com/search.php?category=Beginners#simple) or [Desktop](https://distrowatch.com/search.php?category=Desktop#simple). It should provide you the names of popular, general-purpose Linux distributions with appropriate links and reviews.

Also check the [official GNS3 installation guide](http://docs.gns3.com/1QXVIihk7dsOL7Xr7Bmz4zRzTsJ02wklfImGuHwTlaA4/). You should get the most trouble-free experience using one of the Unbuntu flavors (Xubuntu and Lubuntu are the most indicated for resource limited systems), Debian or Linux Mint as their GNS3 packages do not rely on third-party work.

At last, I have a whole section on [my website](https://www.whitewinterwolf.com/tags/lab/) dedicated to guides on how to setup and operate GNS3-based labs. It is security oriented, but it covers general networking as well. Maybe you will find some information there useful.
