### ISSUE TITLE
Can't use VirtualBox VM when an interface is managed by VirtualBox

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#2335]
GNS3 version 2.1.1dev1 on Darwin (64-bit) with Python 3.6.3 Qt 5.9.2 and PyQt 5.9.1, VirtualBox V5.1.14

https://www.gns3.com/qa/gns3-2-1-interface-already-confi

Having a VirtualBox image with the first adapter managed by VirtualBox and starting it gives error message `Attachment (nat) already configured on adapter 1. Please set it to 'Not attached' to allow GNS3 to use it.`.

Even using it alone without any connection gives that result.
![virtualbox-project](https://user-images.githubusercontent.com/896406/32745593-765a6c30-c8b3-11e7-86ec-deb21f7fb3cd.png)

Here the VirtualBox network configuration, adapter 1 is connected to NAT, the other 3 adapters are not connected:
![virtualbox-network](https://user-images.githubusercontent.com/896406/32745614-81d98730-c8b3-11e7-9960-a662a4f95165.png)

And here the VM configuration in GNS3, nothing special:
![vm-config](https://user-images.githubusercontent.com/896406/32745629-8b96afa0-c8b3-11e7-9a1e-267aed8fe8c9.png)

The same sort of network configuration (one interface not managed by GNS3) works with VMware.

Here the GNS3 server log:
```
2017-11-13 20:38:31 INFO helpers.py:508 192.168.1.10 - - [13/Nov/2017:19:38:31 +0000] "GET /v2/appliances HTTP/1.1" 200 17274 "-" "GNS3 QT Client v2.1.1dev1"
2017-11-13 20:38:31 INFO helpers.py:508 192.168.1.10 - - [13/Nov/2017:19:38:31 +0000] "GET /v2/appliances/templates HTTP/1.1" 200 443674 "-" "GNS3 QT Client v2.1.1dev1"
2017-11-13 20:38:31 INFO project.py:80 Project 36af8060-0696-4416-baa0-df6622a37dba with path '/Users/behlers/GNS3/projects/untitled' created
2017-11-13 20:38:31 INFO helpers.py:508 192.168.1.10 - - [13/Nov/2017:19:38:31 +0000] "POST /v2/compute/projects HTTP/1.1" 201 282 "-" "Python/3.6 aiohttp/2.2.5"
2017-11-13 20:38:31 INFO __init__.py:102 Executing VBoxManage with command: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage --nologo list systemproperties
2017-11-13 20:38:31 INFO virtualbox_vm.py:190 VirtualBox VM 'Ostinato-1' [694f39b3-2c00-4467-a122-56df4c2adfd4] created
2017-11-13 20:38:31 INFO __init__.py:102 Executing VBoxManage with command: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage --nologo showvminfo Ostinato --machinereadable
2017-11-13 20:38:31 INFO virtualbox_vm.py:685 VirtualBox VM 'Ostinato-1' [694f39b3-2c00-4467-a122-56df4c2adfd4] can have a maximum of 8 network adapters for chipset PIIX3
2017-11-13 20:38:31 INFO virtualbox_vm.py:697 VirtualBox VM 'Ostinato-1' [694f39b3-2c00-4467-a122-56df4c2adfd4] has changed the number of Ethernet adapters to 4
2017-11-13 20:38:31 INFO __init__.py:102 Executing VBoxManage with command: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage --nologo showvminfo Ostinato --machinereadable
2017-11-13 20:38:31 INFO helpers.py:508 192.168.1.10 - - [13/Nov/2017:19:38:31 +0000] "POST /v2/compute/projects/36af8060-0696-4416-baa0-df6622a37dba/virtualbox/nodes HTTP/1.1" 201 702 "-" "Python/3.6 aiohttp/2.2.5"
2017-11-13 20:38:31 INFO helpers.py:508 192.168.1.10 - - [13/Nov/2017:19:38:31 +0000] "POST /v2/projects/36af8060-0696-4416-baa0-df6622a37dba/appliances/0918df2a-8436-485d-9a65-8565ae541497 HTTP/1.1" 201 236 "-" "GNS3 QT Client v2.1.1dev1"
2017-11-13 20:38:34 INFO __init__.py:102 Executing VBoxManage with command: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage --nologo showvminfo Ostinato --machinereadable
2017-11-13 20:38:34 INFO __init__.py:102 Executing VBoxManage with command: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage --nologo showvminfo Ostinato --machinereadable
2017-11-13 20:38:34 INFO __init__.py:102 Executing VBoxManage with command: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage --nologo showvminfo Ostinato --machinereadable
2017-11-13 20:38:34 INFO base_node.py:699 VirtualBox: 'Ostinato-1' [694f39b3-2c00-4467-a122-56df4c2adfd4]:local UDP tunnel created between port 10000 and 10001
2017-11-13 20:38:34 ERROR route.py:210 Node error detected: VirtualBoxError
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gns3_server-2.1.1dev1_135c529-py3.6.egg/gns3server/web/route.py", line 195, in control_schema
    yield from func(request, response)
  File "/usr/local/lib/python3.6/site-packages/gns3_server-2.1.1dev1_135c529-py3.6.egg/gns3server/handlers/api/compute/virtualbox_handler.py", line 186, in start
    yield from vm.start()
  File "/usr/local/lib/python3.6/site-packages/gns3_server-2.1.1dev1_135c529-py3.6.egg/gns3server/compute/virtualbox/virtualbox_vm.py", line 267, in start
    yield from self._set_network_options()
  File "/usr/local/lib/python3.6/site-packages/gns3_server-2.1.1dev1_135c529-py3.6.egg/gns3server/compute/virtualbox/virtualbox_vm.py", line 852, in _set_network_options
    adapter_number + 1))
gns3server.compute.virtualbox.virtualbox_error.VirtualBoxError: Attachment (nat) already configured on adapter 1. Please set it to 'Not attached' to allow GNS3 to use it.
2017-11-13 20:38:34 INFO helpers.py:508 192.168.1.10 - - [13/Nov/2017:19:38:34 +0000] "POST /v2/compute/projects/36af8060-0696-4416-baa0-df6622a37dba/virtualbox/nodes/694f39b3-2c00-4467-a122-56df4c2adfd4/start HTTP/1.1" 409 428 "-" "Python/3.6 aiohttp/2.2.5"
2017-11-13 20:38:34 INFO helpers.py:508 192.168.1.10 - - [13/Nov/2017:19:38:34 +0000] "POST /v2/projects/36af8060-0696-4416-baa0-df6622a37dba/nodes/start HTTP/1.1" 409 363 "-" "GNS3 QT Client v2.1.1dev1"
```

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/b14e2e73eda871b16206a92c0a0585ed6a04b26c
