### ISSUE TITLE
[Linux/2.1.2] GNS3 GUI 2.1.2 requests server 1.5.2 when the latter is uninstalled or installed

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-gui#2390]
Ubuntu 17.10
GNS3 GUI 2.1.2
GNS3 Server uninstalled

Major issue:
![gns3 gui 2 1 2 requesting gns3 server 1 5 2](https://user-images.githubusercontent.com/13176858/34999222-7d859628-fae1-11e7-89b5-57c254260db4.png)
[gns3-gui.log](https://github.com/GNS3/gns3-gui/files/1635914/gns3_gui.log.txt)

**Comment by jean-christophe-manciot** [comment]
Same issue when gns3-server 2.1.2 is installed, with an additional very strange exception:
![gns3-server exception](https://user-images.githubusercontent.com/13176858/35001957-69d5242a-fae8-11e7-8eeb-568950b7ef2a.png)

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gns3server", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gns3-server==1.5.2' distribution was not found and is required by the application
```

**Comment by jean-christophe-manciot** [comment]
Same issue with gui/server 2.1.1 requesting server 1.5.2.

**Comment by jean-christophe-manciot** [comment]
If I uninstall apache2, this issue is gone.
The latter was running on 8080 for http & 8443 for https.

**Comment by grossmj** [comment]
Strange, maybe caused because the default port was 8080 for older versions of GNS3. We are going to focus on the other issue.

**Comment by jean-christophe-manciot** [comment]
I have found 2 references to ```1.5.2``` in the sources:
- 1 comment in ```git-gns3-gui/gns3/local_config.py```
- 1 code line in ```git-gns3-gui/tests/test_local_config.py```
You may want to take a look.

**Comment by grossmj** [comment]
I had a look and these are harmless.
