### ISSUE TITLE
bug : cannot import name 'WordCompleter'

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2509]
Hi

Since Monday, i can't start a fresh install of GNS3 2.2

> 2018-06-05 16:47:42 ERROR local_server.py:487 Local server process has stopped
> 2018-06-05 16:47:42 ERROR local_server.py:489 Traceback (most recent call last):
>   File "/usr/bin/gns3server", line 11, in <module>
>     load_entry_point('gns3-server==2.2.0.dev2', 'console_scripts', 'gns3server')()
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/main.py", line 82, in main
>     from gns3server.run import run
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/run.py", line 32, in <module>
>     from gns3server.web.web_server import WebServer
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/web/web_server.py", line 32, in <module>
>     from .route import Route
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/web/route.py", line 30, in <module>
>     from ..compute.error import NodeError, ImageMissingError
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/compute/__init__.py", line 24, in <module>
>     from .dynamips import Dynamips
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/compute/dynamips/__init__.py", line 45, in <module>
>     from .dynamips_factory import DynamipsFactory
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/compute/dynamips/dynamips_factory.py", line 28, in <module>
>     from .nodes.ethernet_switch import EthernetSwitch
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/compute/dynamips/nodes/ethernet_switch.py", line 25, in <module>
>     from gns3server.utils.asyncio.embed_shell import EmbedShell, create_telnet_shell
>   File "/usr/local/lib/python3.5/dist-packages/gns3server/utils/asyncio/embed_shell.py", line 26, in <module>
>     from prompt_toolkit.contrib.completers import WordCompleter
> ImportError: cannot import name 'WordCompleter'
> 
> 2018-06-05 16:48:07 CRITICAL progress_dialog.py:181 WaitForConnectionWorker thread stopping with an error: Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connexion refusée
> 2018-06-05 16:48:08 CRITICAL __init__.py:183 Could not connect to 127.0.0.1 on port 3080: [Errno 111] Connexion refusée
>

**Comment by n3oxmind** [comment]
@Raizo62 , I don't recommend using `gns3 v2.2` yet, its a development branch and not released yet. the latest stable release is `gns3 v2.1.6`.

**Comment by grossmj** [comment]
@Raizo62 I've updated requirements.txt https://github.com/GNS3/gns3-server/commit/7f27cb70150a7163f636cbdede064550d72d289b, can you try again please?

**Comment by Raizo62** [comment]
@grossmj : it is good. thanks :-)

@n3oxmind : sometimes, we need functionalities in last dev version....and so, we test also this dev branch ;-)

**Comment by vincenod** [comment]
hello,

I have the same error.
I have install GNS3 2.1.6
and prompt_toolkit 2.0.3

Could you please help me?

 File "/home/xxxxx/.local/bin/gns3server", line 11, in <module>
    load_entry_point('gns3-server==2.1.6', 'console_scripts', 'gns3server')()
  File "/home/xxxxx/.local/lib/python3.6/site-packages/gns3server/main.py", line 82, in main
    from gns3server.run import run
  File "/home/xxxxxx/.local/lib/python3.6/site-packages/gns3server/run.py", line 32, in <module>
    from gns3server.web.web_server import WebServer
  File "/home/xxxxx/.local/lib/python3.6/site-packages/gns3server/web/web_server.py", line 32, in <module>
    from .route import Route
  File "/home/xxxxx/.local/lib/python3.6/site-packages/gns3server/web/route.py", line 30, in <module>
    from ..compute.error import NodeError, ImageMissingError
  File "/home/xxxxx/.local/lib/python3.6/site-packages/gns3server/compute/__init__.py", line 24, in <module>
    from .dynamips import Dynamips
  File "/home/xxxxx/.local/lib/python3.6/site-packages/gns3server/compute/dynamips/__init__.py", line 45, in <module>
    from .dynamips_factory import DynamipsFactory
  File "/home/xxxxxx/.local/lib/python3.6/site-packages/gns3server/compute/dynamips/dynamips_factory.py", line 28, in <module>
    from .nodes.ethernet_switch import EthernetSwitch
  File "/home/xxxxx/.local/lib/python3.6/site-packages/gns3server/compute/dynamips/nodes/ethernet_switch.py", line 25, in <module>
    from gns3server.utils.asyncio.embed_shell import EmbedShell, create_telnet_shell
  File "/home/xxxxx/.local/lib/python3.6/site-packages/gns3server/utils/asyncio/embed_shell.py", line 26, in <module>
    from prompt_toolkit.contrib.completers import WordCompleter
ImportError: cannot import name 'WordCompleter'

**Comment by bplessis** [comment]
@vincenod : had the same issue, your prompt-toolkit is too new, as you can see in the previous reply gns3 2.2 require prompt-toolkit v 1.0.15 and it is the same for 2.1

> pip3 install -U prompt-toolkit==1.0.15

did the trick for me.

**Comment by alexandrecorso** [comment]
Works for me too.

**Comment by zakywu** [comment]
now i am unsing 
import asn1tools 
and already install the old version of prompt-toolkit
pip3 install -U prompt-toolkit==1.0.15
but still faceing an issue:
from prompt_toolkit.completion import WordCompleter
Traceback (most recent call last):

  File "<ipython-input-6-f1eff2dbcb3d>", line 1, in <module>
    from prompt_toolkit.completion import WordCompleter

ImportError: cannot import name 'WordCompleter' from 'prompt_toolkit.completion' (D:\Program Files\Anaconda\lib\site-packages\prompt_toolkit\completion.py)

**Comment by zakywu** [comment]
i delete two lines and it works
file name: 
*\asntools\__init__.py
change to：
#from prompt_toolkit.completion import WordCompleter
#from prompt_toolkit import PromptSession
