### ISSUE TITLE
gns3serveur not start

### ISSUE THREAD

**Issue by vincenod** [GNS3/gns3-gui#2515]
Hello,

I try to start gns3server local server but i have some errors (see-below)
I have already install prompt_toolkit 2.0.3

Could you please help me?
best Regards

14:19:59 ERROR local_server:487 Local server process has stopped
2018-06-10 14:19:59 ERROR local_server:489 Traceback (most recent call last):
  File "/home/vincebod/.local/bin/gns3server", line 11, in <module>
    load_entry_point('gns3-server==2.1.6', 'console_scripts', 'gns3server')()
  File "/home/vincebod/.local/lib/python3.6/site-packages/gns3server/main.py", line 82, in main
    from gns3server.run import run
  File "/home/vincebod/.local/lib/python3.6/site-packages/gns3server/run.py", line 32, in <module>
    from gns3server.web.web_server import WebServer
  File "/home/vincebod/.local/lib/python3.6/site-packages/gns3server/web/web_server.py", line 32, in <module>
    from .route import Route
  File "/home/vincebod/.local/lib/python3.6/site-packages/gns3server/web/route.py", line 30, in <module>
    from ..compute.error import NodeError, ImageMissingError
  File "/home/vincebod/.local/lib/python3.6/site-packages/gns3server/compute/__init__.py", line 24, in <module>
    from .dynamips import Dynamips
  File "/home/vincebod/.local/lib/python3.6/site-packages/gns3server/compute/dynamips/__init__.py", line 45, in <module>
    from .dynamips_factory import DynamipsFactory
  File "/home/vincebod/.local/lib/python3.6/site-packages/gns3server/compute/dynamips/dynamips_factory.py", line 28, in <module>
    from .nodes.ethernet_switch import EthernetSwitch
  File "/home/vincebod/.local/lib/python3.6/site-packages/gns3server/compute/dynamips/nodes/ethernet_switch.py", line 25, in <module>
    from gns3server.utils.asyncio.embed_shell import EmbedShell, create_telnet_shell
  File "/home/vincebod/.local/lib/python3.6/site-packages/gns3server/utils/asyncio/embed_shell.py", line 26, in <module>
    from prompt_toolkit.contrib.completers import WordCompleter
ImportError: cannot import name 'WordCompleter'

**Comment by grossmj** [comment]
Hi,

Just revert to prompt-toolkit version 1.0.15 like this:

`sudo pip3 install prompt-toolkit==1.0.15`

**Comment by vincenod** [comment]
Hi,

Perfect, 
Thank you
Vincent
