### ISSUE TITLE
AttributeError: 'DockerVMConfigurationPage' object has no attribute 'uiExtraHostsTextEdit'

### ISSUE THREAD

**Issue by acaudwell** [GNS3/gns3-gui#2516]
On the 2.2 branch, clicking configure on a Docker node I'm presented with this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gns3_gui-2.2.0dev2_a5f3164f-py3.6.egg/gns3/graphics_view.py", line 990, in configureActionSlot
    self.configureSlot(items)
  File "/usr/local/lib/python3.6/dist-packages/gns3_gui-2.2.0dev2_a5f3164f-py3.6.egg/gns3/graphics_view.py", line 652, in configureSlot
    node_properties = NodePropertiesDialog(items, self._main_window)
  File "/usr/local/lib/python3.6/dist-packages/gns3_gui-2.2.0dev2_a5f3164f-py3.6.egg/gns3/dialogs/node_properties_dialog.py", line 54, in __init__
    self._loadNodeItems()
  File "/usr/local/lib/python3.6/dist-packages/gns3_gui-2.2.0dev2_a5f3164f-py3.6.egg/gns3/dialogs/node_properties_dialog.py", line 94, in _loadNodeItems
    self.showConfigurationPageSlot(item, 0)
  File "/usr/local/lib/python3.6/dist-packages/gns3_gui-2.2.0dev2_a5f3164f-py3.6.egg/gns3/dialogs/node_properties_dialog.py", line 132, in showConfigurationPageSlot
    page.loadSettings(item.settings(), item.node())
  File "/usr/local/lib/python3.6/dist-packages/gns3_gui-2.2.0dev2_a5f3164f-py3.6.egg/gns3/modules/docker/pages/docker_vm_configuration_page.py", line 101, in loadSettings
    self.uiExtraHostsTextEdit.setText(settings["extra_hosts"])
AttributeError: 'DockerVMConfigurationPage' object has no attribute 'uiExtraHostsTextEdit'
```

I think the UI change might've been missed resolving this merge conflict https://github.com/GNS3/gns3-gui/commit/7c1af696b9c837c4e577446917c1b09c9d7de4b7

**Comment by grossmj** [comment]
Fixed, thanks for catching this! :+1:
