### ISSUE TITLE
When zooming or making any other visual changes in the interface, GNS3 crashes.

### ISSUE THREAD

**Issue by AJNOURI** [GNS3/gns3-gui#2533]
From the community forum:
https://gns3.com/qa/when-zooming-or-making-any-other

---------------------

OS Version: Windows 10 Pro - Build 10.0.17134 

GNS3 2.1.1 to GNS3 2.1.8 

Current GNS3 VM: 0.10.14 

---------------------
When zooming or making any other visual changes in the GNS3 interface, it immidetly crahses. This started occuring after I updated GNS3. I'm assuming it is python related?
 
Here is the error:
 

> Traceback (most recent call last):
> 
> File "./gns3-server\gns3server\web\route.py", line 195, in control_schema
> 
> File "./gns3-server\gns3server\handlers\api\controller\project_handler.py", line 111, in update
> 
> File "./gns3-server\gns3server\controller\project.py", line 144, in update
> 
> File "./gns3-server\gns3server\controller\compute.py", line 596, in put
> 
> File "./gns3-server\gns3server\controller\compute.py", line 388, in http_query
> 
> File "./gns3-server\gns3server\controller\compute.py", line 571, in _run_http_query
> 
> NotImplementedError: 405 status code is not supported

**Comment by jamesobradley** [comment]
Hello!
I am having the exact issue:
Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 195, in control_schema
  File "./gns3-server\gns3server\handlers\api\controller\project_handler.py", line 111, in update
  File "./gns3-server\gns3server\controller\project.py", line 144, in update
  File "./gns3-server\gns3server\controller\compute.py", line 596, in put
  File "./gns3-server\gns3server\controller\compute.py", line 388, in http_query
  File "./gns3-server\gns3server\controller\compute.py", line 571, in _run_http_query
NotImplementedError: 405 status code is not supported

**Comment by michaelstevensonn** [comment]
Same. Already took a screen record to YouTube here: https://www.youtube.com/watch?v=HK9GmzcG6gs

**Comment by snowykilla** [comment]
I am getting this too, has made it unusable, tried every compatibility version too. Happy to help anyway I can please please fix this.

**Comment by snowykilla** [comment]
Same Error

Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 195, in control_schema
  File "./gns3-server\gns3server\handlers\api\controller\project_handler.py", line 111, in update
  File "./gns3-server\gns3server\controller\project.py", line 144, in update
  File "./gns3-server\gns3server\controller\compute.py", line 596, in put
  File "./gns3-server\gns3server\controller\compute.py", line 388, in http_query
  File "./gns3-server\gns3server\controller\compute.py", line 571, in _run_http_query
NotImplementedError: 405 status code is not supported

**Comment by tatacyprian** [comment]
The problem is due to the fact that you are likely running different versions of GNS3 on GNS3 and GNS3 VM. I had the same issue and it was resolved when I downloaded the latest GNS3 VM 2.1.8 and installed. Try that and see if it works.

**Comment by snowykilla** [comment]
Thanks will try that now

**Comment by grossmj** [comment]
@michaelstevensonn I have watch your video, what is the version of the GNS3 VM?

**Comment by grossmj** [comment]
I found out we give no warning/info when a computer server like the GNS3 VM is not the same version of the GUI/local server. So @tatacyprian is correct, you must upgrade the GNS3 VM to be the same version as the GUI and things should work well.

I have added a check for our next release to prevent that situation to happen again.

Please re-open and comment if you still face that issue in the future.
