### ISSUE TITLE
GNS3 not working and not opening in Windows 10

### ISSUE THREAD

**Issue by subhajitck** [GNS3/gns3-gui#2558]
I have installed gns3 in win10 and its installed properly.But after double clicking on it its not opening.
showing message like "gns3 network simulator is stopped working".I have installed it also selecting the compatibility mode to windows 8.But still not working.

kindly help to resolve it.

![gns3 error](https://user-images.githubusercontent.com/42073138/43655509-7e7fb324-976c-11e8-8c98-79e62b626b29.jpg)
![gns3 error](https://user-images.githubusercontent.com/42073138/43655524-8928ebba-976c-11e8-9b24-3b4e86d95801.jpg)

**Comment by Fathurhoho** [comment]
I suggest you to follow this troubleshooting step: https://docs.gns3.com/1OB0_9M-_QyQZTlC1eY_Dc60BgwjU2bXGdnf-B7Uf_u4/index.html

**Comment by subhajitck** [comment]
I tried with troubleshooting steps but it was not worked.In my friends laptop gns3 is perfectly running in win10 only,but only in my laptop is not run..

**Comment by grossmj** [comment]
@subhajitck have you tried the version 2.2 I posted?

**Comment by subhajitck** [comment]
Just now install it and its opening..Thanks.But facing one problem that it can't connect to server after switching of windows firewall

**Comment by grossmj** [comment]
@subhajitck Can you post a screenshot please?

**Comment by subhajitck** [comment]
![image](https://user-images.githubusercontent.com/42073138/44416497-a6f8d880-a590-11e8-98f3-3b5aa98fab31.png)

**Comment by grossmj** [comment]
There was something broken with version 2.2 (don't forget this is a development version). Please try with the following build: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2018-08-22/2.2/GNS3-2.2.2018-08-22-all-in-one.exe/download

**Comment by subhajitck** [comment]
Hi i have downloaded and installed.BUT IT STILL NOT CONNECTING
![image](https://user-images.githubusercontent.com/42073138/44474223-ca368d00-a64f-11e8-8024-dac8b9b94d27.png)

**Comment by n3oxmind** [comment]
@grossmj , Here is the `gns3_server.log`  that I generated from [https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2018-08-22/2.2/GNS3-2.2.2018-08-22-all-in-one.exe/download](https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2018-08-22/2.2/GNS3-2.2.2018-08-22-all-in-one.exe/download) for the same issue that @subhajitck is facing.
20:31:51 INFO run.py:213 GNS3 server version 2.2.0dev3
2018-08-23 20:31:51 INFO run.py:215 Copyright (c) 2007-2018 GNS3 Technologies Inc.
2018-08-23 20:31:51 INFO run.py:218 Config file C:\Users\user1\AppData\Roaming\GNS3\gns3_server.ini loaded
2018-08-23 20:31:51 WARNING run.py:224 Local mode is enabled. Beware, clients will have full control on your filesystem
2018-08-23 20:31:51 INFO run.py:232 Running with Python 3.6.6 and has PID 2412
2018-08-23 20:31:51 CRITICAL run.py:256 Critical error while running the server: No directory exists at 'C:\Program Files\GNS3\python36.zip\gns3server\static'
Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\aiohttp\web_urldispatcher.py", line 481, in __init__
ValueError: Not a directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./gns3-server\gns3server\run.py", line 250, in run
  File "./gns3-server\gns3server\web\web_server.py", line 282, in run
  File "C:\Python36-x64\lib\site-packages\aiohttp\web_urldispatcher.py", line 926, in add_static
  File "C:\Python36-x64\lib\site-packages\aiohttp\web_urldispatcher.py", line 484, in __init__
ValueError: No directory exists at 'C:\Program Files\GNS3\python36.zip\gns3server\static'
2018-08-23 20:31:51 ERROR manager.py:78 'StaticResource' object has no attribute '_directory'
Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\aiohttp\web_urldispatcher.py", line 481, in __init__
ValueError: Not a directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./gns3-server\gns3server\run.py", line 250, in run
  File "./gns3-server\gns3server\web\web_server.py", line 282, in run
  File "C:\Python36-x64\lib\site-packages\aiohttp\web_urldispatcher.py", line 926, in add_static
  File "C:\Python36-x64\lib\site-packages\aiohttp\web_urldispatcher.py", line 484, in __init__
ValueError: No directory exists at 'C:\Program Files\GNS3\python36.zip\gns3server\static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\raven\utils\serializer\manager.py", line 76, in transform
  File "C:\Python36-x64\lib\site-packages\aiohttp\web_urldispatcher.py", line 644, in __repr__
AttributeError: 'StaticResource' object has no attribute '_directory'
2018-08-23 20:31:51 ERROR manager.py:78 'StaticResource' object has no attribute '_directory'
Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\aiohttp\web_urldispatcher.py", line 481, in __init__
ValueError: Not a directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./gns3-server\gns3server\run.py", line 250, in run
  File "./gns3-server\gns3server\web\web_server.py", line 282, in run
  File "C:\Python36-x64\lib\site-packages\aiohttp\web_urldispatcher.py", line 926, in add_static
  File "C:\Python36-x64\lib\site-packages\aiohttp\web_urldispatcher.py", line 484, in __init__
ValueError: No directory exists at 'C:\Program Files\GNS3\python36.zip\gns3server\static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\raven\utils\serializer\manager.py", line 76, in transform
  File "C:\Python36-x64\lib\site-packages\aiohttp\web_urldispatcher.py", line 644, in __repr__
AttributeError: 'StaticResource' object has no attribute '_directory'
2018-08-23 20:31:52 ERROR crash_report.py:112 Can't send crash report to Sentry: ('API key is disabled', 401)

P.S. I installed gns3-gui-2.1.9 on fresh Win10 VM and it work fine.

**Comment by subhajitck** [comment]
So is there any update on this to overcome this issue?

**Comment by grossmj** [comment]
I am going to fix this tomorrow.

**Comment by subhajitck** [comment]
Thanks a lot...

**Comment by grossmj** [comment]
This should have been fixed now, please test: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2018-08-30/2.2/GNS3-2.2.2018-08-30-all-in-one.exe/download

Thanks!

**Comment by n3oxmind** [comment]
I've tested it on my  Win10 VM and It works fine with no issues. 

P.S. I've tested the installation only and successfully connected to the local server, but I didn't run any lab.

**Comment by grossmj** [comment]
Better solution, you can download and run the dev version of 2.1.10: https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2018-09-01/2.1/GNS3-2.1.2018-09-01-all-in-one.exe/download

**Comment by it2020** [comment]
I have  this
![img_20181116_211454](https://user-images.githubusercontent.com/45105521/48638277-60771680-e9e5-11e8-9a65-d028bc635979.jpg)
 problem
I installed all version 2.1.1 and uper but worked jist 1.4.0 - 1.4.5 - 1.3.7
In windows 10

**Comment by n3oxmind** [comment]
@it2020, let say that your GNS3 exe package that you download is not corrupted what I would do is as follow:
1- Run the program as administrator
2- Change compatibility settings (by right-click on the program)
3- Check if there is  Win10 update (via Setting)
4- Scan the system for error and fix it.

cheers!

**Comment by it2020** [comment]
@n3oxmind , I do all item that you say but not working
In compatibility mode I haven't windows10?
![img_20181117_053011](https://user-images.githubusercontent.com/45105521/48655304-680cde80-ea2a-11e8-87a1-42623d979417.jpg)

**Comment by n3oxmind** [comment]
@it2020 ,back to your first screenshot. these kind of error messages triggered when installing 64bit on 32bit or the software you trying to installed is not compatible with the OS you running or you missing some libraries also happen with corrupted system. 

Are you running 64-bit or 32-bit ? 
if you running 64-bit try to check your installed programs and running processes and figure out what effect this installation.

This is as far as I can help. I hope grossmj read this and help you.

**Comment by grossmj** [comment]
@it2020 A few questions to help us understand where this could come from...

* Have you installed all the latest updates for your Windows?
* Do you have any security suite or similar running?
* Have you installed Python on your system?

**Comment by it2020** [comment]
@grossmj 
• No, I never updates my windows; but I question why 1.5.0 version and downer are installed and worked but upper version not worked.
• No I haven't running any security program, so I checkd windows defender off and firewall off, but not ok.
• No ever, but I install windows10 again.

**Comment by varunaggarwal94** [comment]
Hi,

I am facing a problem in GNS3 that it is not creating a new folder while using crating any new networking diagram ...??

Pls guide about it what is the issue ..

Uninstall & install many times but still the same....

Attaching the problem snap link :::: (https://user-images.githubusercontent.com/25582386/53698032-8a6e1080-3dfd-11e9-97d9-2dc6549d56b7.PNG)
