### ISSUE TITLE
2.2 : GNS3 doesn't create the missing values

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2639]
Hi

A script of LiveRaizo can add VM to GNS3.

- If GNS3 is running, the script uses your API

- If GNS3 is stopped, the script modifies your config files gns3_controller.conf

I have not problem if GNS3 is running, but when GNS3 is stopped.

Before your new code, if the json file doesn't have the "appliance_id" value , GNS3 creates and adds automaticaly this value.
In the new version, gns3-server crashs. Is it a bug ? (in the sense : could GNS3 create the missing values ?)

If you can't/want to create the missing values, how do you create the appliance id ?

**Comment by grossmj** [comment]
> In the new version, gns3-server crashs. Is it a bug ? (in the sense : could GNS3 create the missing values ?)

GNS3 should create the appliance_id if none is provided. Please provide the log if there is a crash.

> If you can't/want to create the missing values, how do you create the appliance id ?

I imagine you use shell scripts so if you are on Ubuntu you could call the `uuidgen` program or call Python itself `python3 -c "import uuid; print(uuid.uuid4())"`

One note, the appliance API will most likely have some modifications soon. Nothing too big, we plan to replace use the name `templates` instead of `appliances`

**Comment by Raizo62** [comment]
I start gns3. no bug. I close gns3.
I edit the file gns3_controller.conf and remove one line with appliance_id 
`"appliance_id": "1acc3bd6-a620-45aa-b8eb-9b7c6a884b56",`
I start gns3-server : gns3server -A --host 0.0.0.0
```
2018-11-26 19:37:09 INFO run.py:213 GNS3 server version 2.2.0dev5
2018-11-26 19:37:09 INFO run.py:215 Copyright (c) 2007-2018 GNS3 Technologies Inc.
2018-11-26 19:37:09 INFO run.py:218 Config file /home/user/.config/GNS3/gns3_server.conf loaded
2018-11-26 19:37:09 INFO run.py:232 Running with Python 3.5.3 and has PID 1507
2018-11-26 19:37:09 INFO run.py:79 Current locale is fr_FR.UTF-8
2018-11-26 19:37:09 WARNING port_manager.py:92 Remote console connections are allowed
2018-11-26 19:37:09 INFO web_server.py:290 Starting server on 0.0.0.0:3080
2018-11-26 19:37:09 INFO __init__.py:67 Load controller configuration file /home/user/.config/GNS3/gns3_controller.conf
2018-11-26 19:37:09 INFO __init__.py:221 Controller is starting
2018-11-26 19:37:09 INFO compute.py:64 Create compute local
2018-11-26 19:37:09 INFO compute.py:376 Connecting to compute 'local'
2018-11-26 19:37:09 INFO helpers.py:477 127.0.0.1 [26/Nov/2018:19:37:09 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 558 "-" "Python/3.5 aiohttp/3.2.1"
^C2018-11-26 19:37:26 WARNING web_server.py:143 Server has got signal SIGINT, exiting...
2018-11-26 19:37:28 INFO helpers.py:477 127.0.0.1 [26/Nov/2018:19:37:09 +0000] "GET /v2/compute/notifications/ws HTTP/1.1" 200 481 "-" "Python/3.5 aiohttp/3.2.1"
2018-11-26 19:37:28 INFO __init__.py:276 Controller is Stopping
user@raizo:~$ nano .config/GNS3/gns3_controller.conf
user@raizo:~$ gns3server -A --host 0.0.0.0
2018-11-26 19:37:56 INFO run.py:213 GNS3 server version 2.2.0dev5
2018-11-26 19:37:56 INFO run.py:215 Copyright (c) 2007-2018 GNS3 Technologies Inc.
2018-11-26 19:37:56 INFO run.py:218 Config file /home/user/.config/GNS3/gns3_server.conf loaded
2018-11-26 19:37:56 INFO run.py:232 Running with Python 3.5.3 and has PID 1512
2018-11-26 19:37:56 INFO run.py:79 Current locale is fr_FR.UTF-8
2018-11-26 19:37:56 WARNING port_manager.py:92 Remote console connections are allowed
2018-11-26 19:37:56 INFO web_server.py:290 Starting server on 0.0.0.0:3080
2018-11-26 19:37:56 INFO __init__.py:67 Load controller configuration file /home/user/.config/GNS3/gns3_controller.conf
2018-11-26 19:37:56 INFO __init__.py:221 Controller is starting
2018-11-26 19:37:56 CRITICAL run.py:256 Critical error while running the server: 'appliance_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gns3server/run.py", line 250, in run
    server.run()
  File "/usr/local/lib/python3.5/dist-packages/gns3server/web/web_server.py", line 293, in run
    if self._run_application(self._handler, ssl_context) is False:
  File "/usr/local/lib/python3.5/dist-packages/gns3server/web/web_server.py", line 87, in _run_application
    self._server, startup_res = self._loop.run_until_complete(asyncio.gather(srv, self._app.startup(), loop=self._loop))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_app.py", line 275, in startup
    await self.on_startup.send(self)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/signals.py", line 35, in send
    await receiver(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gns3server/web/web_server.py", line 208, in _on_startup
    await Controller.instance().start()
  File "/usr/local/lib/python3.5/dist-packages/gns3server/controller/__init__.py", line 238, in start
    computes = await self._load_controller_settings()
  File "/usr/local/lib/python3.5/dist-packages/gns3server/controller/__init__.py", line 344, in _load_controller_settings
    appliance = Appliance(appliance_settings["appliance_id"], appliance_settings)
KeyError: 'appliance_id'

```

**Comment by Raizo62** [comment]
> It wasn't really a bug since it is not expected users directly modify the gns3_controller.conf file

I know, then i didn't add the word "Bug" in the title ;-)
Thanks also for the patch and for the explains on "appliance_id"/templates
