### ISSUE TITLE
2.2 : Bug : 'MainWindow' object has no attribute '_newApplianceActionSlot'

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#2643]
Hi

I erase the config GNS3.
I start GNS3
After few questions, i have this error : 
```
=== GNS3 2.2.0dev5 traceback on 29 nov. 2018 07:45:23 ===
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gns3/main_window.py", line 1209, in startupLoading
    self._setupWizardActionSlot()
  File "/usr/local/lib/python3.5/dist-packages/gns3/main_window.py", line 944, in _setupWizardActionSlot
    self._newApplianceActionSlot()
AttributeError: 'MainWindow' object has no attribute '_newApplianceActionSlot'
```

**Comment by grossmj** [comment]
Fixed, thanks for catching this :+1:
