### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type QComboBox has been deleted

### ISSUE THREAD

**Issue by declan-marks** [GNS3/gns3-gui#2716]
****** Exception detected, traceback information saved in /home/declanmarks/.config/GNS3/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gns3/qt/__init__.py", line 247, in partial
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/gns3/http_client.py", line 718, in _processResponse
    callback(params, server=server, context=context, raw_body=raw_body)
  File "/usr/lib/python3.7/site-packages/gns3/qt/__init__.py", line 247, in partial
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/gns3/modules/qemu/pages/qemu_vm_configuration_page.py", line 277, in _getQemuBinariesFromServerCallback
    self.uiQemuListComboBox.clear()
RuntimeError: wrapped C/C++ object of type QComboBox has been deleted

**Comment by grossmj** [comment]
Will be fixed when we implement https://github.com/GNS3/gns3-gui/issues/2713
