### ISSUE TITLE
WinError 10014 in asyncio on Windows

### ISSUE THREAD

**Issue by handbye** [GNS3/gns3-gui#2721]
### the log in win 10 cmd:
```
2019-02-23 23:51:00 INFO run.py:213 GNS3 server version 2.1.12
2019-02-23 23:51:00 INFO run.py:215 Copyright (c) 2007-2019 GNS3 Technologies Inc.
2019-02-23 23:51:00 INFO run.py:218 Config file C:\Users\10103\AppData\Roaming\GNS3\gns3_server.ini loaded
2019-02-23 23:51:00 INFO run.py:232 Running with Python 3.6.6 and has PID 13492
2019-02-23 23:51:00 INFO web_server.py:283 Starting server on 127.0.0.1:3080
2019-02-23 23:51:00 INFO __init__.py:65 Load controller configuration file C:\Users\10103\AppData\Roaming\GNS3\gns3_controller.conf
2019-02-23 23:51:00 INFO __init__.py:168 Start controller
2019-02-23 23:51:00 INFO compute.py:79 Create compute local
2019-02-23 23:51:00 INFO compute.py:420 Connecting to compute 'local'
2019-02-23 23:51:00 ERROR base_events.py:1268 Accept failed on a socket
socket: <socket.socket fd=1088, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 3080)>
Traceback (most recent call last):
  File "C:\Python36-x64\lib\asyncio\proactor_events.py", line 502, in loop
  File "C:\Python36-x64\lib\asyncio\windows_events.py", line 702, in _poll
  File "C:\Python36-x64\lib\asyncio\windows_events.py", line 483, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2019-02-23 23:51:00 ERROR base_events.py:1268 Task exception was never retrieved
future: <Task finished coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at C:\Python36-x64\lib\asyncio\windows_events.py:485> exception=OSError(10014, '系统检测到在一个调用中尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "C:\Python36-x64\lib\asyncio\windows_events.py", line 489, in accept_coro
  File "C:\Python36-x64\lib\asyncio\proactor_events.py", line 502, in loop
  File "C:\Python36-x64\lib\asyncio\windows_events.py", line 702, in _poll
  File "C:\Python36-x64\lib\asyncio\windows_events.py", line 483, in finish_accept
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
```
I have reproduced the installation and Several versions have been tried。 but the problem remains。

I don't know what to do，i need help! Thanks!!

**Comment by handbye** [comment]
the firwall closed and No antivirus software installed.

**Comment by grossmj** [comment]
Hi,

Try to run this command with cmd.exe (run as an administrator): `netsh winsock reset` then launch GNS3 again.

**Comment by handbye** [comment]
thank you for replay. this method has try. but not useful. @grossmj

**Comment by grossmj** [comment]
This seems to be a bug with Python (maybe the asyncio module?)... The closest similar issue I found is https://twistedmatrix.com/trac/ticket/4669

Maybe you can try our 2.2 alpha 1 release available there: https://github.com/GNS3/gns3-gui/releases/tag/v2.2.0a1

Note that is version is not production ready but maybe the error won't come with some luck.

**Comment by grossmj** [comment]
Also, the error is described in https://qa-test.hachina.io/dwqa-question/7620.html

**Comment by handbye** [comment]
i didn't find "Python36-x64"  on disk C , and i didn't install python36。 I think it's because of this?  i will try install python36 and try 2.2 alpha 1 release。

**Comment by grossmj** [comment]
Python36-x64 is embedded in GNS3. You do not need to install Python.

Let us know if you have any success with 2.2 alpha 1. Thanks.

**Comment by handbye** [comment]
bad news,the problem persists. I am sure it worked a few days ago.

**Comment by handbye** [comment]
oh my god! I reinstallation win10, problem was solved !

**Comment by grossmj** [comment]
Indeed this is a weird issue. Thanks for the feedback! :+1:
