### ISSUE TITLE
GNS3 2.2.0a3 packet filter not working

### ISSUE THREAD

**Issue by fernandolcx** [GNS3/gns3-gui#2754]
When trying to apply a filter this message is thrown:

```
Error while updating link: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gns3server/web/route.py", line 196, in control_schema
    await func(request, response)
  File "/usr/local/lib/python3.6/dist-packages/gns3server/handlers/api/controller/link_handler.py", line 137, in update
    await link.update_filters(request.json["filters"])
  File "/usr/local/lib/python3.6/dist-packages/gns3server/controller/link.py", line 201, in update_filters
    await self.update()
  File "/usr/local/lib/python3.6/dist-packages/gns3server/controller/udp_link.py", line 120, in update
    await node1.put("/adapters/{adapter_number}/ports/{port_number}/nio".format(adapter_number=adapter_number1, port_number=port_number1), data=self._link_data[0], timeout=120)
  File "/usr/local/lib/python3.6/dist-packages/gns3server/controller/node.py", line 554, in put
    return (await self._compute.put(path, data=data, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/gns3server/controller/compute.py", line 553, in put
    response = await self.http_query("PUT", path, data, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/gns3server/controller/compute.py", line 333, in http_query
    response = await self._run_http_query(method, path, data=data, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/gns3server/controller/compute.py", line 531, in _run_http_query
    raise NotImplementedError("{} status code is not supported".format(response.status))
NotImplementedError: 405 status code is not supported
```

 - OS: GNS3 on Windows 10 + GNS3 VM on ESXi 6.7
 - GNS3 version: 2.2.0a3
 - Any use of the GNS3 VM or remote server (ESXi, bare metal etc.)

**Comment by grossmj** [comment]
Thanks for the report. What filter have your tried to use and between what nodes?

**Comment by fernandolcx** [comment]
> Thanks for the report. What filter have your tried to use and between what nodes?

Used the delay filter between a generic EtherSwitch and one RouterOS CHR.
Looks like any option I choose triggers this message.

Also, I think I've found another different bug for 2.1.15.
Should I open another issue or post here?

**Comment by grossmj** [comment]
Thanks for the details. Please open another issue for the bug in 2.1.15

**Comment by grossmj** [comment]
This should be fixed now. Thanks :+1:
