### ISSUE TITLE
[2.2.0b2] Configure IOU Device

### ISSUE THREAD

**Issue by gcasella** [GNS3/gns3-gui#2806]
Hey,

When I add a new IOU template to my GNS3 client and try to right click and press "Configure Template" i get the following traceback message;

****** Exception detected, traceback information saved in C:\Users\Gian-Luca Casella\AppData\Roaming\GNS3\2.2\exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "./gns3-gui\gns3\qt\__init__.py", line 257, in partial
  File "./gns3-gui\gns3\nodes_view.py", line 214, in _configurationSlot
  File "./gns3-gui\gns3\dialogs\configuration_dialog.py", line 48, in __init__
  File "./gns3-gui\gns3\modules\iou\pages\iou_device_configuration_page.py", line 229, in loadSettings
KeyError: 'usage'

**Comment by grossmj** [comment]
Fixed, thanks :+1:
