### ISSUE TITLE
GNS3 gui and server does not start on Python 3.8

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-gui#2895]
**Describe the bug**
GNS3 gui and server does not start on Python 3.8

**GNS3 version and operating system (please complete the following information):**
 - OS: ArchLinux
 - GNS3 version 2.2.2
 - installation on bare metal
 - Python 3.8

**To Reproduce**
1. Try to start gns3 or gns3server from shell
2. The following traceback is displayed

Traceback (most recent call last):
  File "/bin/gns3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gns3-gui===2.2.2-a4e9d6b8' distribution was not found and is required by the application

**Comment by grossmj** [comment]
This should work with version 2.2.3. Thanks for catching that :)
