### ISSUE TITLE
GNS3 Doesn't start

### ISSUE THREAD

**Issue by TangraM3** [GNS3/gns3-gui#2900]
**Describe the bug**
I try to start GNS3 and then it shows the following text:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (psutil 5.6.5 (/usr/lib/python3.8/site-packages), Requirement.parse('psutil==5.6.3'), {'gns3-gui'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gns3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psutil==5.6.3' distribution was not found and is required by gns3-gui

```

**GNS3 version and operating system (please complete the following information):**
 - OS: Arch Linux x64
 - GNS3 version: 2.2.3-1

**To Reproduce**
1. Try to start GNS3 in CLI.

**Comment by cioby23** [comment]
You need to downgrade psutil to version 5.6.3. 
I had this issue and I have removed psutil 5.6.5 (**sudo pacman -Rs python-psutil**) and then using pip command install version 5.6.3 
**sudo pip install psutil==5.6.3** and it should work fine then.
I'm not sure why GNS3 requirements locked psutil version to 5.6.3

**Comment by TangraM3** [comment]
Well, I did what you told me. I had to uninstall GNS3 because it didn't allow me to remove it because it was a dependency. Now he doesn't let me install GNS3 because he doesn't recognize python-psutil.

**Comment by cioby23** [comment]
You can manually remove dependencies for a package forcefully by using **sudo pacman -Rdd python-psutil**

**Comment by TangraM3** [comment]
Thank you!
