### ISSUE TITLE
No recovery after uBridge v0.9.17 stops

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#2951]
**Describe the bug**
ubridge v0.9.17 stops, if an error occurs, for example connection refused. But neither the GUI nor the server restarts ubridge, so the projects gets into an unstable state.

community posts:
https://gns3.com/community/discussion/ubridge-upgraded-to-0-9-17-this-
https://gns3.com/community/discussion/cloud-connection-stopped-working
https://gns3.com/community/discussion/last-sudo-apt-upgrade-broke-conn
https://gns3.com/community/discussion/ubridge-process-stops-working-af

**GNS3 version and operating system (please complete the following information):**
 - OS: Debian Linux
 - GNS3 version 2.2.6

**To Reproduce**

1. Create a project with 2 QEMU devices interconnected, for example
![project](https://user-images.githubusercontent.com/49040325/77647580-f40c1000-6f66-11ea-90f5-a9e5ba750489.png)
1. Start only one of them
1. Wait until the device is fully booted
1. The first packet send by this devices results in an ubridge error, here the gns3server log, the GUI shows it twice
    ```
    2020-03-26 13:23:04 ERROR hypervisor.py:195 uBridge process has stopped, return code: 1
    uBridge version 0.9.17 running with libpcap version 1.8.1
    Hypervisor TCP control server started (IP 0.0.0.0 port 40415).
    UDP tunnel connecting from local port 10011 to IPv4 address 127.0.0.1 on port 10010
    UDP tunnel connecting from local port 10001 to IPv4 address 192.168.1.99 on port 10000
    Source NIO listener thread for QEMU-5d45a178-f396-4928-b86b-40168e288b3d-0 has started
    Destination NIO listener thread for QEMU-5d45a178-f396-4928-b86b-40168e288b3d-0 has started
    recv: Connection refused
    Destination NIO listener thread for QEMU-5d45a178-f396-4928-b86b-40168e288b3d-0 has stopped because of an error: Invalid argument
    ```
1. Start the second one
1. Wait until the second device is fully booted
1. The first packet send by the second devices again results in this error, as the ubridge of the first device has stopped and is not restarted.
1. Trying to delete this link results in restarting the ubridge of the first device and then in this error:
    ```
    Error while deleting link: Error while sending command 'bridge delete QEMU-afcd1c0d-78d9-4a07-ba00-8a53276e8b32-0': bridge 'QEMU-afcd1c0d-78d9-4a07-ba00-8a53276e8b32-0' doesn't exist: uBridge version 0.9.17 running with libpcap version 1.8.1
    Hypervisor TCP control server started (IP 0.0.0.0 port 43841).

    Here the server log:

    2020-03-26 13:24:03 INFO qemu_vm.py:1124 Execute QEMU monitor command: set_link gns3-0 off
    2020-03-26 13:24:03 INFO qemu_vm.py:1109 Connected to QEMU monitor on 127.0.0.1:36235 after 0.0111 seconds
    2020-03-26 13:24:03 INFO base_node.py:565 Starting new uBridge hypervisor 0.0.0.0:43841
    2020-03-26 13:24:03 INFO hypervisor.py:169 starting ubridge: ['/usr/local/bin/ubridge', '-H', '0.0.0.0:43841']
    2020-03-26 13:24:03 INFO hypervisor.py:171 logging to /opt/gns3/projects/a61bdf93-d726-46a4-b245-f8b158defe49/project-files/qemu/afcd1c0d-78d9-4a07-ba00-8a53276e8b32/ubridge.log
    2020-03-26 13:24:03 INFO hypervisor.py:179 ubridge started PID=4018
    2020-03-26 13:24:03 INFO base_node.py:568 Hypervisor 0.0.0.0:43841 has successfully started
    2020-03-26 13:24:03 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on 127.0.0.1:43841 after 0.1024 seconds
    2020-03-26 13:24:03 ERROR route.py:212 Node error detected: UbridgeError
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/gns3server/compute/base_node.py", line 541, in _ubridge_send
        await self._ubridge_hypervisor.send(command)
      File "/usr/local/lib/python3.7/dist-packages/gns3server/utils/asyncio/__init__.py", line 163, in wrapper
        return await f(oself, *args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/gns3server/ubridge/ubridge_hypervisor.py", line 259, in send
        raise UbridgeError(data[-1][4:])
    gns3server.ubridge.ubridge_error.UbridgeError: bridge 'QEMU-afcd1c0d-78d9-4a07-ba00-8a53276e8b32-0' doesn't exist

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/gns3server/web/route.py", line 197, in control_schema
        await func(request, response)
      File "/usr/local/lib/python3.7/dist-packages/gns3server/handlers/api/compute/qemu_handler.py", line 374, in delete_nio
        await vm.adapter_remove_nio_binding(adapter_number)
      File "/usr/local/lib/python3.7/dist-packages/gns3server/compute/qemu/qemu_vm.py", line 1346, in adapter_remove_nio_binding
        await self._ubridge_send("bridge delete {name}".format(name="QEMU-{}-{}".format(self._id, adapter_number)))
      File "/usr/local/lib/python3.7/dist-packages/gns3server/compute/base_node.py", line 543, in _ubridge_send
        raise UbridgeError("Error while sending command '{}': {}: {}".format(command, e,  self._ubridge_hypervisor.read_stdout()))
    gns3server.ubridge.ubridge_error.UbridgeError: Error while sending command 'bridge delete QEMU-afcd1c0d-78d9-4a07-ba00-8a53276e8b32-0': bridge 'QEMU-afcd1c0d-78d9-4a07-ba00-8a53276e8b32-0' doesn't exist: uBridge version 0.9.17 running with libpcap version 1.8.1
    Hypervisor TCP control server started (IP 0.0.0.0 port 43841).
    2020-03-26 13:24:03 INFO web_log.py:233 192.168.1.10 [26/Mar/2020:12:24:03 +0000] "DELETE /v2/compute/projects/a61bdf93-d726-46a4-b245-f8b158defe49/qemu/nodes/afcd1c0d-78d9-4a07-ba00-8a53276e8b32/adapters/0/ports/0/nio HTTP/1.1" 409 641 "-" "Python/3.7 aiohttp/3.6.2"
    ```
1. After that the GUI thinks the link is gone, but it's still shown in the GUI. Another try to delete the link results in:
    ```
    Error while deleting link: Link ID 3893f5e6-9664-447f-859d-3c137e4732ea doesn't exist
    ```
1. During the whole time no communication is possible between both QEMU VMs

**Comment by grossmj** [comment]
Released uBridge version 0.9.18 which solves this problem. I will keep this issue open because we still have to decide what to do if uBridge stops/crashes. The easiest would just be to stop the node as well.

**Comment by b-ehlers** [comment]
I was wondering, why your changes to ubridge v0.9.18 are working. You just moved the perror() call down, this should only influence the logging.

After some debugging I found that the perror() call changes errno !!!

Here a test against 0.9.18:
```
--- a/src/ubridge.c
+++ b/src/ubridge.c
@@ -58,9 +58,11 @@ static int bridge_nios(nio_t *rx_nio, nio_t *tx_nio, bridge_t *bridge)
     drop_packet = FALSE;
     bytes_received = nio_recv(rx_nio, &pkt, NIO_MAX_PKT_SIZE);
     if (bytes_received == -1) {
+        perror("recv");
+        perror("recv");
         if (errno == ECONNREFUSED || errno == ENETDOWN)
            continue;
-        perror("recv");
+        /* perror("recv"); */
         return -1;
     }
```

This results in this output:
```
recv: Connection refused
recv: Invalid argument
```

So in all cases you want to use errno after a perror() call you must save errno and restore it afterwards. In function bridge_nios in ubridge.c you can remove the perror() call, because the errno is printed in the functions calling bridge_nios.

**Comment by grossmj** [comment]
> I was wondering, why your changes to ubridge v0.9.18 are working. You just moved the perror() call down, this should only influence the logging.

Yes I was surprised by this too and it was very unexpected consequence. Well, you learn something new everyday ;)

> So in all cases you want to use errno after a perror() call you must save errno and restore it afterwards. In function bridge_nios in ubridge.c you can remove the perror() call, because the errno is printed in the functions calling bridge_nios.

Right, I will remove the perror() calls :+1:

**Comment by b-ehlers** [comment]
Alternatively you could create a perror() function, that preserves errno:
```
void save_perror(const char *msg)
{
  int save_errno = errno;
  perror(msg);
  errno = save_errno;
}
```

**Comment by grossmj** [comment]
However, one advantage of leaving the perror() calls is you know exactly what function failed `send` or `recv`. This is a detail but it can help for debugging purposes...
