### ISSUE TITLE
gns3 not run with fedora 32

### ISSUE THREAD

**Issue by mbardoscia** [GNS3/gns3-gui#3012]
hi dears,
im new here
i have a problem after updated from fedora 30 to fedora 32. below is the output

gns3
Fail update installation: module 'platform' has no attribute 'linux_distribution'
Traceback (most recent call last):
  File "/usr/local/bin/gns3", line 11, in <module>
    load_entry_point('gns3-gui==2.1.21', 'gui_scripts', 'gns3')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/gns3/main.py", line 55, in <module>
    from gns3.main_window import MainWindow
  File "/usr/local/lib/python3.8/site-packages/gns3/main_window.py", line 27, in <module>
    from .local_config import LocalConfig
  File "/usr/local/lib/python3.8/site-packages/gns3/local_config.py", line 29, in <module>
    from .controller import Controller
  File "/usr/local/lib/python3.8/site-packages/gns3/controller.py", line 25, in <module>
    from .settings import LOCAL_SERVER_SETTINGS
  File "/usr/local/lib/python3.8/site-packages/gns3/settings.py", line 164, in <module>
    distro = platform.linux_distribution()[0]
AttributeError: module 'platform' has no attribute 'linux_distribution'

is there anyone with the same problem and fixed it?
thx

**Comment by grossmj** [comment]
Version 2.1.21 is not supported with Python 3.8. Please use an older version of Python or use the latest GNS3 v2.2.10 version.

Thanks.
