### ISSUE TITLE
Clicking "Refresh" with Virtualbox based GNS3 VM doesn't work

### ISSUE THREAD

**Issue by demonCoder95** [GNS3/gns3-gui#3022]
**Describe the bug**
When using Virtualbox as the hypervisor for my GNS3 VM hosted locally on the laptop, when I click the Refresh button to list VMs, I get the following error, and am unable to interface the GNS3VM with the GUI.

```bash
=> Error while listing vms: Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 198, in control_schema
  File "./gns3-server\gns3server\handlers\api\controller\gns3_vm_handler.py", line 52, in get_vms
  File "./gns3-server\gns3server\utils\asyncio\__init__.py", line 163, in wrapper
  File "./gns3-server\gns3server\controller\gns3vm\__init__.py", line 262, in list
  File "./gns3-server\gns3server\controller\gns3vm\virtualbox_gns3_vm.py", line 216, in list
  File "./gns3-server\gns3server\controller\gns3vm\virtualbox_gns3_vm.py", line 95, in _check_requirements
KeyError: 'vendor_id'
```

**GNS3 version and operating system (please complete the following information):**
 - OS: Windows 10
 - GNS3 version 2.2.11
 - Virtualbox 6.0.14 r133895 (Qt5.6.2)
 - GNS3 VM 2.2.11 Virtualbox

**To Reproduce**
1. Import the GNS3 VM in Virtualbox
2. Start GNS3 UI
3. Go to Edit -> Preferences -> GNS3 VM
4. Select Virtualbox as hypervisor
5. Click "Refresh" to get VM list

You should see the error above.

**Screenshots or videos**
Attached the screenshot to the issue.
![gns3-error-issue](https://user-images.githubusercontent.com/15079451/87289407-06aa5500-c516-11ea-9a65-f472cca6432b.PNG)

**Additional context**
I'm willing to help develop a patch for this, if I'm given the right direction.

**Comment by grossmj** [comment]
This error has been addressed in https://github.com/GNS3/gns3-gui/issues/3018
