### ISSUE TITLE
Unable to connect to Virtualbox GNS3 VM in GNS3 2.2.11

### ISSUE THREAD

**Issue by jtorri** [GNS3/gns3-gui#3030]
**Describe the bug**
Please provide a clear and detailed description of what the bug is.
When attempting to assign a specific Virtualbox GNS3 VM to GNS3 the following error is displayed.

GNS3 management console.
Running GNS3 version 2.2.11 on Windows (64-bit) with Python 3.6.8 Qt 5.12.1 and PyQt 5.12.
Copyright (c) 2006-2020 GNS3 Technologies.
Use Help -> GNS3 Doctor to detect common issues.

=> Could not find a VM named 'GNS3 VM', is it imported in VMware or VirtualBox?
Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 198, in control_schema
  File "./gns3-server\gns3server\handlers\api\controller\gns3_vm_handler.py", line 52, in get_vms
  File "./gns3-server\gns3server\utils\asyncio\__init__.py", line 163, in wrapper
  File "./gns3-server\gns3server\controller\gns3vm\__init__.py", line 262, in list
  File "./gns3-server\gns3server\controller\gns3vm\virtualbox_gns3_vm.py", line 216, in list
  File "./gns3-server\gns3server\controller\gns3vm\virtualbox_gns3_vm.py", line 95, in _check_requirements
KeyError: 'vendor_id'

**GNS3 version and operating system (please complete the following information):**
    OS: Windows 10 version 2004 OS Build 19041.388
    GNS3 version 2.2.11
    Virtualbox 6.1.12r13918 (Qt 5.6.2)

**To Reproduce**
1. Install GNS3 VM 2.2.11 VM in Virtualbox via import within Virtualbox
2. Apt install ntp and then configure time/date
3. Attempt to select the Virtualbox VM as the GNS3 VM

**Comment by grossmj** [comment]
This is fixed already, it will work in the next version to be released tomorrow.

**Comment by jtorri** [comment]
As always, thanks!!  Based on very limited testing GNS3-2.2.2020-08-06-all-in-one.exe solves this issue.

**Comment by jtorri** [comment]
After initial but not lengthy testing, problem solved with version 2.2.12.  Please feel free to close this one.  Thanks!
