### ISSUE TITLE
Cannot start GNS3 in Arch Linux

### ISSUE THREAD

**Issue by t0msk** [GNS3/gns3-gui#3071]
Hello,

when I start GNS3 I get python error like:

```
=> Local server process has stopped

Traceback (most recent call last):

File "/usr/bin/gns3server", line 33, in <module>

sys.exit(load_entry_point('gns3-server==2.2.14', 'console_scripts', 'gns3server')())

File "/usr/bin/gns3server", line 25, in importlib_load_entry_point

return next(matches).load()

File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load

module = import_module(match.group('module'))

File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

File "<frozen importlib._bootstrap>", line 991, in _find_and_load

File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 783, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "/usr/lib/python3.8/site-packages/gns3server/main.py", line 29, in <module>

import gns3server.utils.get_resource

File "/usr/lib/python3.8/site-packages/gns3server/utils/get_resource.py", line 19, in <module>

import pkg_resources

File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3268, in <module>

def _initialize_master_working_set():

File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in _call_aside

f(*args, **kwargs)

File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3280, in _initialize_master_working_set

working_set = WorkingSet._build_master()

File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 582, in _build_master

ws.require(__requires__)

File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 899, in require

needed = self.resolve(parse_requirements(requirements))

File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 785, in resolve

raise DistributionNotFound(req, requirers)

pkg_resources.DistributionNotFound: The 'async-timeout==3.0.1' distribution was not found and is required by gns3-server
```

I installed all required packages from AUR (which are listed on Arch wiki) like: **python-aiohttp-cors-gns3**, **python-yarl-gns3**, **gns3-gui**, **gns3-server**, **dynamips**

I checked async-timeout version:

```
[tomsk@tomsk-PC ~]$ pip freeze | grep async-timeout
async-timeout==3.0.1
```

Screenshot:
![Screenshot_20201013_110113](https://user-images.githubusercontent.com/7276200/95839747-a8bf2080-0d43-11eb-8152-9d4bf6295423.png)

**Comment by cristian-ciobanu** [comment]
I'm using the same GNS3 packages (gns3-gui and gns3-server) from AUR on Archlinux and it works fine.

This is not a GNS3 related issue rather than a package dependency problem so I suggest to uninstall all gns3 related packages and do a clean install again. The AUR packages are not maintained by GNS3 team.

Also try not to mix if possible package dependencies installed using pip with others installed with pacman from the official repositories.

**Comment by t0msk** [comment]
Thanks removed all packages from pip and installed it from AUR and it works :)
