### ISSUE TITLE
Problem not running GNS3 on Ubuntu 19.10 due to an error “ pkg_resources.DistributionNotFound: The 'psutil == 5.6.7' distribution was not found ”

### ISSUE THREAD

**Issue by devamir81** [GNS3/gns3-gui#3072]
Hi

I installed GNS3 software on Ubuntu 19.10 But it does not work. It gives this error from the terminal that I run

```
Traceback (most recent call last):
  File "/ usr / local / bin / gns3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f (* args, ** kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master ()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require (__ requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve (parse_requirements (requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound (req, requirers)
pkg_resources.DistributionNotFound: The 'psutil == 5.6.7' distribution was not found and is required by gns3-gui
```

I also installed `psutil == 5.6.7 `with the `pip install psutil == 5.6.7` command. The output is:
` Requirement already satisfied: psutil == 5.6.7 in /usr/local/lib/python2.7/dist-packages (5.6.7)`

What do you think is the problem?

**Comment by devamir81** [comment]
Solved

I am writing the steps that if someone gets into this problem later, he should use it ...

First I installed pip3 with the command `apt install python3-pip`

Then I installed psutil with the `pip3 install psutil ` command.

Then he wrote that gns3 needs these

```
gns3-server 2.2.15 requires aiofiles == 0.5.0, which is not installed.
gns3-server 2.2.15 requires aiohttp == 3.6.2, which is not installed.
gns3-server 2.2.15 requires aiohttp-cors == 0.7.0, which is not installed.
gns3-server 2.2.15 requires async-timeout == 3.0.1, which is not installed.
gns3-server 2.2.15 requires Jinja2> = 2.7.3, which is not installed.
gns3-server 2.2.15 requires jsonschema == 3.2.0, which is not installed.
gns3-gui 2.2.15 requires jsonschema == 3.2.0, which is not installed.
gns3-server 2.2.15 has requirement psutil == 5.6.7, but you'll have psutil 5.7.2 which is incompatible.
gns3-gui 2.2.15 has requirement psutil == 5.6.7, but you'll have psutil 5.7.2 which is incompatible.

```
Then I installed them all in order with the `pip3 install` command and then gns3 was run :)
