### ISSUE TITLE
Could not connect to 127.0.0.1 on port 3080: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by cortix** [GNS3/gns3-gui#3127]
I am a newbie at GNS3. 
I have installed the program as in the instruction steps but when I run the program, I am getting the errors as below; (By the way, I am using a Mac mini(M1 chip). I've installed Rosetta 2.)

`Could not connect to 127.0.0.1 on port 3080: [Errno 61] Connection refused`

`
Error when connecting to the GNS3 server:
Cannot connect to http://127.0.0.1:3080. Please check if GNS3 is allowed in your antivirus and firewall. And that server version is 2.2.17.
`

```
=> Local server process has stopped
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/usr/local/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "gns3-server/gns3server/main.py", line 87, in <module>
  File "gns3-server/gns3server/main.py", line 83, in main
  File "./gns3-server/gns3server/run.py", line 211, in run
  File "./gns3-server/gns3server/run.py", line 194, in kill_ghosts
  File "/usr/local/lib/python3.6/site-packages/psutil/__init__.py", line 738, in name
  File "/usr/local/lib/python3.6/site-packages/psutil/__init__.py", line 791, in cmdline
  File "/usr/local/lib/python3.6/site-packages/psutil/_psosx.py", line 338, in wrapper
  File "/usr/local/lib/python3.6/site-packages/psutil/_psosx.py", line 422, in cmdline
OSError: [Errno 5] Input/output error
```

By the way, I am getting these errors even though I have turned off the firewall. You can look at the screenshots below;

<img width="657" alt="Screen Shot 2021-02-08 at 16 41 58" src="https://user-images.githubusercontent.com/6178404/107375562-eec1a080-6af9-11eb-84a2-1c33245edd50.png">
<img width="657" alt="Screen Shot 2021-02-08 at 16 41 30" src="https://user-images.githubusercontent.com/6178404/107375571-f08b6400-6af9-11eb-834f-65f8fcefd9f9.png">
<img width="658" alt="Screen Shot 2021-02-09 at 17 20 35" src="https://user-images.githubusercontent.com/6178404/107376725-490f3100-6afb-11eb-9f68-d3924e656d4e.png">

![Screen Shot 2021-02-08 at 18 14 13](https://user-images.githubusercontent.com/6178404/107375626-01d47080-6afa-11eb-9bf1-16e0d705e95c.png)
![Screen Shot 2021-02-08 at 18 14 47](https://user-images.githubusercontent.com/6178404/107375622-ff721680-6af9-11eb-9b36-1a8830a25061.png)

**GNS3 version and operating system**
 - OS: macOS Big Sur Version 11.2
 - GNS3 version 2.2.17
 - GNS3.VM.VMware.Workstation.2.2.17

**Comment by grossmj** [comment]
Looks like the problem comes from the psutil package which isn't compatible with the M1 chip. I will try to fix this for the next release.

**Comment by grossmj** [comment]
This error is fixed now. Let me if everything works once we release version 2.2.18, I am interested to hear how GNS3 runs on the M1 chip. Thanks :+1:

**Comment by cortix** [comment]
Ok thanks.. I will let you know :)
