### ISSUE TITLE
Invalid version check request from GUI to server

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#3144]
**Describe the bug**
In gns3_server.log I found a traceback right after the GUI starts. It doesn't seem to have bad consequences, everything works fine after that.

```
2021-03-05 13:36:24 ERROR web_protocol.py:355 Error handling request
Traceback (most recent call last):
  File "/home/behlers/.local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "/home/behlers/.local/lib/python3.9/site-packages/aiohttp/http_parser.py", line 264, in feed_data
    msg = self.parse_message(self._lines)
  File "/home/behlers/.local/lib/python3.9/site-packages/aiohttp/http_parser.py", line 437, in parse_message
    raise BadStatusLine(method)
aiohttp.http_exceptions.BadStatusLine: /version
```

The GUI logs an error only in debug mode:

```
2021-03-05 13:36:24 DEBUG http_client:761 /version http://localhost:3080/v2<bound method Controller._versionGetSlot of <gns3.controller.Controller object at 0x7f38048b3670>>
2021-03-05 13:36:24 DEBUG http_client:788 Error while connecting to local server Error transferring http://admin@localhost:3080/v2%3Cbound method Controller._versionGetSlot of %3Cgns3.controller.Controller object at 0x7f38048b3670%3E%3E - server replied: Bad Request
```

The request in Wireshark:
![wireshark](https://user-images.githubusercontent.com/49040325/110118106-226eae00-7dba-11eb-8c12-db121ba46511.png)

**GNS3 version and operating system:**
 - OS: Deban Linux 11 (Bullseye)
 - GNS3 version 2.2.19
 - Python 3.9.1+ Qt 5.15.2 and PyQt 5.15.2
 - No GNS3 VM

**To Reproduce**
1. Start server
2. Start GUI in debug mode
3. Check log files

**Comment by b-ehlers** [comment]
I had a look into the sources of the GNS3 GUI. The call to getSynchronous in controller.py line 133

```
self.httpClient().getSynchronous('/version', self._versionGetSlot, timeout=60)
```

doesn't match the definition of getSynchronous in http_client.py line 752

```
def getSynchronous(self, method, endpoint, prefix="/v2", timeout=5)
```

Inserting the method "GET" as the first parameter is easy. But I have no idea what's the role of the parameter `self._versionGetSlot`.

**Comment by eknoes** [comment]
I changed the code to 

```
        status, json_data = self.httpClient().getSynchronous('GET', '/version', timeout=60)
        self._versionGetSlot(json_data, status >= 300)
```

This solves the error of the wrong request, but I do not know if this was the intended way.

**Comment by grossmj** [comment]
Should be fixed now. Thanks @b-ehlers @eknoes :+1:
