### ISSUE TITLE
Exception shown, when GNS3 is started with empty config

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#3188]
**Describe the bug**
When running GNS3 with an empty configuration directory, it shows two exceptions. It looks, like it hasn't any negative effects, it just doesn't look nice.

It also happens, when a new configuration profile is created. It doesn't happen, when GNS3 finds a config.

**GNS3 version and operating system (please complete the following information):**
 - OS: Debian Linux
 - GNS3 version 2.2.21
 - No GNS3 VM or remote server (ESXi, bare metal etc.)

**To Reproduce**
1. Remove configuration (after making a backup) `rm -r ~/.config/GNS3/2.2/*`
2. Starting GNS3
3. See error

**Additional context**
exception.log:

```
=== GNS3 2.2.21 traceback on 09 Jun 2021 17:20:57 ===
Traceback (most recent call last):
  File "/home/behlers/GNS3/venv/lib/python3.9/site-packages/gns3/qt/__init__.py", line 275, in func_wrapper
    return func(*args, **kwargs)
  File "/home/behlers/GNS3/venv/lib/python3.9/site-packages/gns3/main_window.py", line 524, in _projectChangedSlot
    self._refreshVisibleWidgets()
  File "/home/behlers/GNS3/venv/lib/python3.9/site-packages/gns3/main_window.py", line 543, in _refreshVisibleWidgets
    for widget in self.disableWhenRemoteContollerWidgets:
AttributeError: 'MainWindow' object has no attribute 'disableWhenRemoteContollerWidgets'
=== GNS3 2.2.21 traceback on 09 Jun 2021 17:20:57 ===
Traceback (most recent call last):
  File "/home/behlers/GNS3/venv/lib/python3.9/site-packages/gns3/qt/__init__.py", line 275, in func_wrapper
    return func(*args, **kwargs)
  File "/home/behlers/GNS3/venv/lib/python3.9/site-packages/gns3/main_window.py", line 524, in _projectChangedSlot
    self._refreshVisibleWidgets()
  File "/home/behlers/GNS3/venv/lib/python3.9/site-packages/gns3/main_window.py", line 543, in _refreshVisibleWidgets
    for widget in self.disableWhenRemoteContollerWidgets:
AttributeError: 'MainWindow' object has no attribute 'disableWhenRemoteContollerWidgets'
```

It looks, like _refreshVisibleWidgets is called before self.disableWhenNoProjectWidgets and self.disableWhenRemoteContollerWidgets are initialized.

**Comment by grossmj** [comment]
Should be fixed now. Thanks :+1:
