### ISSUE TITLE
Drawing tools stopped working

### ISSUE THREAD

**Issue by smart2128** [GNS3/gns3-gui#3276]
**Describe the bug**
Drawing tools (Text, Rectangle, Ellipse and Line) don't work anymore.

**GNS3 version and operating system:**
 - OS: Linux
 - GNS3 version 2.2.28
 - GNS3 on Arch Linux on bare metal
 - python 3.10.1

**Screenshots or videos**
A screen recording describing the issue:

![drawing_tools](https://user-images.githubusercontent.com/16859/146659338-cddf5909-145f-4c9c-a9bb-39bfab7c87d3.gif)

Partial exceptions.log's content follows:

```
=== GNS3 2.2.28 traceback on 17 dic 2021 17:27:50 ===
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 1444, in textEditActionSlot
    text_edit_dialog = TextEditorDialog(self._main_window, items)
  File "/usr/lib/python3.10/site-packages/gns3/dialogs/text_editor_dialog.py", line 47, in __init__
    self.uiRotationSpinBox.setValue(first_item.rotation())
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
=== GNS3 2.2.28 traceback on 18 dic 2021 16:50:47 ===
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 486, in mousePressEvent
    self.createDrawingItem("rect", pos.x(), pos.y(), 1)
  File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 1635, in createDrawingItem
    item = RectangleItem(pos=QtCore.QPoint(x, y), z=z, locked=locked, rotation=rotation, project=self._topology.project(), drawing_id=drawing_id, svg=svg)
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'float'
=== GNS3 2.2.28 traceback on 18 dic 2021 16:50:57 ===
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 486, in mousePressEvent
    self.createDrawingItem("rect", pos.x(), pos.y(), 1)
  File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 1635, in createDrawingItem
    item = RectangleItem(pos=QtCore.QPoint(x, y), z=z, locked=locked, rotation=rotation, project=self._topology.project(), drawing_id=drawing_id, svg=svg)
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'float'
```

**Comment by grossmj** [comment]
Thanks, looks like something has changed with PyQt itself...

**Comment by grossmj** [comment]
@smart2128 the problem appeared when using Python >=  3.10 (see https://github.com/GNS3/gns3-gui/pull/3277#issuecomment-1000497918 for details). We will fix this and release version 2.2.29 early January.

**Comment by smart2128** [comment]
@grossmj Thank you very much. Please, let me wish you all a merry Christmas and a happy new year.

**Comment by marvaen7** [comment]
The same with typing tool , bug reported in another thread , hop this got fixed soon !

**Comment by grossmj** [comment]
> The same with typing tool , bug reported in another thread , hop this got fixed soon !

Fixed on master branch :)
