### ISSUE TITLE
Text edit on a label causes error

### ISSUE THREAD

**Issue by ByteEater-pl** [GNS3/gns3-gui#3295]
**Describe the bug**
When I choose "Text edit" from a label's context menu, in the console I get the following:
```
****** Exception detected, traceback information saved in /home/km/.config/GNS3/2.2/exceptions.log ******

PLEASE REPORT ON https://www.gns3.com

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 1444, in textEditActionSlot
    text_edit_dialog = TextEditorDialog(self._main_window, items)
  File "/usr/lib/python3.10/site-packages/gns3/dialogs/text_editor_dialog.py", line 47, in __init__
    self.uiRotationSpinBox.setValue(first_item.rotation())
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
```

**GNS3 version and operating system (please complete the following information):**
 - OS: Manjaro Linux
 - GNS3 version 2.2.29
 - use of the GNS3 VM

**To Reproduce**
see "Describe the bug"

**Comment by grossmj** [comment]
This issue has been fixed. Version v2.2.30 which includes the fix will be released soon.
