### ISSUE TITLE
Cannot configure Docker container after being placed on the topology view GNS3 3.0.0 alpha 1

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-gui#3366]
**Describe the bug**
Cannot configure Docker container after being placed on the topology view

**GNS3 version and operating system (please complete the following information):**
 - OS: ArchLinux
 - GNS3 version: 3.0.0 alpha 1
 - GNS3 server and GUI are running on same machine (bare metal)

**To Reproduce**
1. Drag a Docker container from the All devices pane on the topology view
2. Right click on the Docker container and choose from **Configure** from the menu.
3. No configuration dialog box is being opened and the following exception is thrown:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 1046, in configureActionSlot
    self.configureSlot(items)
  File "/usr/lib/python3.10/site-packages/gns3/graphics_view.py", line 686, in configureSlot
    node_properties = NodePropertiesDialog(items, self._main_window)
  File "/usr/lib/python3.10/site-packages/gns3/dialogs/node_properties_dialog.py", line 54, in __init__
    self._loadNodeItems()
  File "/usr/lib/python3.10/site-packages/gns3/dialogs/node_properties_dialog.py", line 94, in _loadNodeItems
    self.showConfigurationPageSlot(item, 0)
  File "/usr/lib/python3.10/site-packages/gns3/dialogs/node_properties_dialog.py", line 132, in showConfigurationPageSlot
    page.loadSettings(item.settings(), item.node())
  File "/usr/lib/python3.10/site-packages/gns3/modules/docker/pages/docker_vm_configuration_page.py", line 115, in loadSettings
    self._custom_adapters = settings["custom_adapters"].copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Screenshots or videos**
None

**Additional context**
None

**Comment by grossmj** [comment]
Fixed
