### ISSUE TITLE
Couldn't connect to hypervisor on 127.0.0.1:xxxxx

### ISSUE THREAD

**Issue by alexove** [GNS3/gns3-gui#3428]
Hello, I'm having troubles with GNS3 and dynamips. I have GNS3-2.2.36 and dynamips-0.2.22 in Fedora 37.
I'm trying to add a switch into project and I'm getting the "Couldn't connect to hypervisor on 127.0.0.1:xxxxx" error.
I executed gns3server in another terminal and get this error:
`2023-01-17 17:53:58 INFO web_log.py:206 ::1 [17/Jan/2023:22:53:58 +0000] "GET /v2/computes HTTP/1.1" 200 1025 "-" "GNS3 QT Client v2.2.36"
2023-01-17 17:54:08 ERROR route.py:221 Node error detected: DynamipsError
Traceback (most recent call last):
 File "/usr/lib/python3.11/site-packages/gns3server/web/route.py", line 200, in control_schema
    await func(request, response)
  File "/usr/lib/python3.11/site-packages/gns3server/handlers/api/compute/ethernet_switch_handler.py", line 55, in create
    node = await dynamips_manager.create_node(request.json.pop("name"),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/gns3server/compute/base_manager.py", line 259, in create_node
    await node.create()
  File "/usr/lib/python3.11/site-packages/gns3server/compute/dynamips/nodes/ethernet_switch.py", line 184, in create
    self._hypervisor = await self.manager.start_new_hypervisor(working_dir=module_workdir)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/gns3server/compute/dynamips/__init__.py", line 310, in start_new_hypervisor
    await hypervisor.connect()
  File "/usr/lib/python3.11/site-packages/gns3server/compute/dynamips/dynamips_hypervisor.py", line 90, in connect
    raise DynamipsError("Couldn't connect to hypervisor on {}:{} :{}".format(host, self._port, last_exception))
gns3server.compute.dynamips.dynamips_error.DynamipsError: Couldn't connect to hypervisor on 127.0.0.1:46735 :[Errno 111] Connect call failed ('127.0.0.1', 46735)
2023-01-17 17:54:08 INFO web_log.py:206 127.0.0.1 [17/Jan/2023:22:53:58 +0000] "POST /v2/compute/projects/a55e005c-101f-4fd8-9e31-5be75ec09baf/ethernet_switch/nodes HTTP/1.1" 409 410 "-" "Python/3.11 aiohttp/3.8.3"`

**Comment by grossmj** [comment]
Please upgrade Dynamips to version 0.2.23 and things should work.

**Comment by grossmj** [comment]
@alexove have you managed to upgrade to dynamips-0.2.23?

**Comment by Powerock38** [comment]
I installed dynamips through the AUR and got this error, then removed it and compiled it from the git repo, and it worked.

**Comment by eantowne** [comment]
It is important to note that the GNS3 packages in the AUR and Fedora repositories are not maintained by the GNS3 team, which includes Dynamips. They are maintained by third parties.

- AUR Dynamips has not been updated since September last  year [0.2.22-1](https://aur.archlinux.org/packages/dynamips)
- Fedora 37 GNS3 server package is at 2.2.33.1, and Dynamips is not even listed
