### ISSUE TITLE
Cannot load symbols library when trying to change the symbol for a device GNS3 3.0.0 alpha 3

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-gui#3440]
Describe the bug
Cannot load symbols library when trying to change the symbol for a device

GNS3 version and operating system (please complete the following information):

- OS: ArchLinux
- GNS3 version: 3.0.0 alpha 3
- GNS3 server and GUI are running on same machine (bare metal)
- Python version: 3.10.9

To Reproduce

1. Drag a device from All devices list on the topology and then right click on the device and choose **Change symbol** option
2. The Symbol selection dialog box opens but the symbol list is empty.
3. An error is being displayed in the console window
```
Error transferring http://127.0.0.1:8080/v3/symbols - server replied: Internal Server Error (HTTP code 500)
Error while listing symbols: Error transferring http://127.0.0.1:8080/v3/symbols - server replied: Internal Server Error (HTTP code 500)
```
Additional context

Additionally an error is generated in the GNS3 server log.

```
ERROR httptools_impl.py:424 Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/us.r/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/lib/python3.10/site-packages/fastapi/routing.py", line 255, in app
    content = await serialize_response(
  File "/usr/lib/python3.10/site-packages/fastapi/routing.py", line 141, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: <unprintable ValidationError object>
```

**Comment by grossmj** [comment]
Seems this has been fixed. Maybe due to an upgrade of FastAPI
