### ISSUE TITLE
2.2 : SyntaxError: f-string: unmatched '['

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-gui#3639]
Hi

Here : f21a53072980b027b256510d164f638943201791

With Python 3.11.2 (Debian stable backport), I have this error message : 

```
Traceback (most recent call last):
  File "/usr/bin/gns3", line 5, in <module>
    from gns3.main import main
  File "/usr/local/lib/python3.11/dist-packages/gns3/main.py", line 45, in <module>
    from gns3.main_window import MainWindow
  File "/usr/local/lib/python3.11/dist-packages/gns3/main_window.py", line 52, in <module>
    from .dialogs.appliance_wizard import ApplianceWizard
  File "/usr/local/lib/python3.11/dist-packages/gns3/dialogs/appliance_wizard.py", line 552
    f"expected:\t{disk["md5sum"]}\n\n"
                        ^^^^^^
SyntaxError: f-string: unmatched '['
```

**Comment by grossmj** [comment]
This should be fixed now. Thanks for catching this.
