### ISSUE TITLE
Can't save preferences, KeyError: 'ubridge_path'

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#432]
GNS3 management console. Running GNS3 version 1.3.5 on Darwin (64-bit).
Copyright (c) 2006-2015 GNS3 Technologies.

****** Exception detected, traceback information saved in /Users/behlers/.config/gns3.net/exceptions.log ******

PLEASE REPORT ON https://community.gns3.com/community/software/bug

Traceback (most recent call last):
  File "gns3/dialogs/preferences_dialog.pyo", line 156, in accept
  File "gns3/dialogs/preferences_dialog.pyo", line 131, in _applyPreferences
  File "gns3/pages/server_preferences_page.pyo", line 248, in savePreferences
KeyError: 'ubridge_path'

**Comment by grossmj** [comment]
Arghh... ok fixed in https://github.com/GNS3/gns3-gui/commit/1b5c6757115abf068085705e3ca4af754af0479c
