### ISSUE TITLE
GNS3VM with VMware doesn't start on OSX

### ISSUE THREAD

**Issue by noplay** [GNS3/gns3-gui#467]
```
***** Exception detected, traceback information saved in /Users/noplay/.config/gns3.net/exceptions.log ******

PLEASE REPORT ON https://community.gns3.com/community/software/bug

Traceback (most recent call last):
  File "/Users/noplay/code/gns3/gns3-gui/gns3/utils/wait_for_vm_worker.py", line 152, in run
    self._vm.execute_vmrun("start", args)
  File "/Users/noplay/code/gns3/gns3-gui/gns3/gns3_vm.py", line 68, in execute_vmrun
    output = subprocess.check_output(command)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 607, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/subprocess.py", line 1395, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by noplay** [comment]
The start command is
```
2015-06-24 14:43:01 DEBUG gns3_vm.py:67 Executing vmrun with command: ['/Applications/VMware Fusion.app/Contents/Library/vmrun', '-T', None, 'start',
```

**Comment by noplay** [comment]
I dropped the -T we never fill the settings and it's work without it.

**Comment by grossmj** [comment]
We need -T because we can have Player or Worstation (the default) on other platforms. You should remove the -T only on OSX or if host_type is None.

**Comment by noplay** [comment]
This mean the settings should be set in the VMware section and after that
we use it in the GNS3 VM section? What happen if the user didn't configure
it or use a wrong config?

I will change it for supporting the None

**Comment by noplay** [comment]
Finally I force it to fusion type.

**Comment by grossmj** [comment]
> This mean the settings should be set in the VMware section and after that we use it in the GNS3 VM section? What happen if the user didn't configure it or use a wrong config?

The host type was not set in the VMware section because we don't support VMware VMs in GNS3 on Mac OS X. Anyway, glad you found a fix.
