### ISSUE TITLE
1.4: GUI crashs on unset vmrun_path variable

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#507]
GNS3: 1.4.0.dev1, GNS3-unstable.2015-07-07.dmg OS: Mac OS X 10.9.5

If the vmrun_path variable (in VMware preference) is unset in gns3_gui.conf, e.g. because gns3_gui.conf doesn't exist, the GUI crashes. In case of a non existing gns3_gui.conf file, a new one is created. But this doesn't contain the vmrun_path, so the GUI keeps crashing.

```
****** Exception detected, traceback information saved in /Users/behlers/.config/GNS3/exceptions.log ******

PLEASE REPORT ON https://community.gns3.com/community/software/bug

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "gns3-gui/gns3/main.py", line 273, in <module>
  File "gns3-gui/gns3/main.py", line 258, in main
  File "./gns3-gui/gns3/main_window.py", line 91, in __init__
  File "./gns3-gui/gns3/ui/main_window_ui.py", line 129, in setupUi
  File "./gns3-gui/gns3/console_view.py", line 64, in __init__
  File "./gns3-gui/gns3/modules/vmware/__init__.py", line 374, in instance
  File "./gns3-gui/gns3/modules/vmware/__init__.py", line 54, in __init__
  File "./gns3-gui/gns3/modules/vmware/__init__.py", line 58, in configChangedSlot
  File "./gns3-gui/gns3/modules/vmware/__init__.py", line 121, in _loadSettings
  File "./gns3-gui/gns3/modules/vmware/__init__.py", line 84, in _findVmrun
UnboundLocalError: local variable 'vmrun_path' referenced before assignment

2015-07-07 10:07:35 INFO crash_report.py:102 Crash report sent with event ID: bcdcd42f1eb74bfeb01dc21eaed5d6b1
```

**Comment by ehlers** [comment]
Also crashes on empty vmrun_path ("vmrun_path": "")

**Comment by grossmj** [comment]
I couldn't test on Mac, hopefully this is ok this time ;)

**Comment by ehlers** [comment]
Works (as expect) :thumbsup:

I wanted to be able to better follow the development also on my mac, so I finally installed gns-gui/gns3-server from git source (goodbye nightly builds).
