### ISSUE TITLE
PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\GNS3\\updates'

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#564]
Upgrade to alpha2 failed. By default Windows forbid you to change files in C:\Program File
```
GNS3 management console. Running GNS3 version 1.4.0.dev1 on Windows (64-bit) with Qt 5.4.2.
Copyright (c) 2006-2015 GNS3 Technologies.

=> ****** Exception detected, traceback information saved in C:\Users\Vbox\AppData\Roaming\GNS3\exceptions.log ******

PLEASE REPORT ON https://community.gns3.com/community/software/bug

Traceback (most recent call last):
  File "./gns3-gui\gns3\update_manager.py", line 132, in _pypiReplySlot
  File "./gns3-gui\gns3\update_manager.py", line 163, in downloadUpdates
  File "c:\Python\64-bit\3.4\lib\os.py", line 237, in makedirs
PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\GNS3\\updates'
```

**Comment by noplay** [comment]
What the best location for that APPLICATION DATA ?

**Comment by grossmj** [comment]
%APPDATA%\GNS3 or %TEMP% depending if this is temporary.

**Comment by noplay** [comment]
Fix but not tested

**Comment by noplay** [comment]
We need also to check if installler correclty uninstall previous updates
