### ISSUE TITLE
Latest unstable version of GNS3 gui does not load

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-gui#642]
When trying to run the gns3-gui using the latest code from the unstable git repo it does not start. Below is the traceback

Traceback (most recent call last):
  File "/usr/bin/gns3", line 9, in <module>
    load_entry_point('gns3-gui==1.4.0.dev6', 'gui_scripts', 'gns3')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/gns3_gui-1.4.0.dev6-py3.4.egg/gns3/main.py", line 53, in <module>
    from gns3.main_window import MainWindow
  File "/usr/lib/python3.4/site-packages/gns3_gui-1.4.0.dev6-py3.4.egg/gns3/main_window.py", line 33, in <module>
    from .modules import MODULES
  File "/usr/lib/python3.4/site-packages/gns3_gui-1.4.0.dev6-py3.4.egg/gns3/modules/__init__.py", line 18, in <module>
    from gns3.modules.builtin import Builtin
  File "/usr/lib/python3.4/site-packages/gns3_gui-1.4.0.dev6-py3.4.egg/gns3/modules/builtin/__init__.py", line 23, in <module>
    from gns3.servers import Servers
  File "/usr/lib/python3.4/site-packages/gns3_gui-1.4.0.dev6-py3.4.egg/gns3/servers.py", line 37, in <module>
    from .settings import SERVERS_SETTINGS
  File "/usr/lib/python3.4/site-packages/gns3_gui-1.4.0.dev6-py3.4.egg/gns3/settings.py", line 240, in <module>
    "shell_console_command": DEFAULT_SHELL_CONSOLE_COMMAND,
NameError: name 'DEFAULT_SHELL_CONSOLE_COMMAND' is not defined

**Comment by noplay** [comment]
It should be fixed can you test?

Thanks a lot

**Comment by cioby23** [comment]
Yes it works now. Issue can be closed.
Thanks.
