### ISSUE TITLE
Cannot create a Qemu VM on GNS3 VM.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#703]
```
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/http_client.py", line 708, in _processResponse
    callback(params, server=self, context=context)
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/dialogs/vm_with_images_wizard.py", line 166, in _getImagesFromServerCallback
    combo_box.addItem(vm["path"], vm)
KeyError: 'path'

Crash report sent with event ID: 43aa32a57c2f4aa4b78b3ede88872ffd

```

**Comment by noplay** [comment]
You need to upgrade the server on the VM

**Comment by grossmj** [comment]
Confirmed, upgrading the VM to the correct version fixed the problem.
