### ISSUE TITLE
Exception when closing the GUI

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#705]
Sometimes I get this exception when closing GNS3. I don't know where it comes from...

```
2015-10-07 08:10:49 INFO project.py:337 Project a1399980-55ae-423d-baae-e142ffce1fb2 closed
Project a1399980-55ae-423d-baae-e142ffce1fb2 closed
2015-10-07 08:10:49 INFO servers.py:512 Stopping local server (PID=10514)
Stopping local server (PID=10514)
Exception ignored in: <bound method Task.__del__ of <Task pending coro=<get() running at /usr/lib/python3.4/asyncio/queues.py:198> wait_for=<Future pending cb=[Task._wakeup()]> cb=[_release_waiter(<Future cancelled>)() at /usr/lib/python3.4/asyncio/tasks.py:335]>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 93, in __del__
  File "/usr/lib/python3.4/asyncio/base_events.py", line 1037, in call_exception_handler
  File "/usr/lib/python3.4/logging/__init__.py", line 1303, in error
  File "/usr/lib/python3.4/logging/__init__.py", line 1409, in _log
  File "/usr/lib/python3.4/logging/__init__.py", line 1419, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 1481, in callHandlers
  File "/usr/lib/python3.4/logging/__init__.py", line 853, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 1040, in emit
  File "/usr/lib/python3.4/logging/__init__.py", line 1030, in _open
NameError: name 'open' is not defined

Process finished with exit code 0
```

**Comment by grossmj** [comment]
I get this error after adding Dynamips or Qemu nodes when the server shutdowns.

```
2015-10-11 15:40:56 ERROR base_events.py:1008 Task was destroyed but it is pending!
task: <Task pending coro=<start() running at /usr/local/lib/python3.4/dist-packages/aiohttp/server.py:272> wait_for=<Future cancelled>>
```

Looks like it is similar to https://github.com/GNS3/gns3-server/issues/310

**Comment by grossmj** [comment]
This is a consistent error and a regression because I don't remember seeing it in previous betas.

**Comment by noplay** [comment]
You still have it ? Because since my server fix https://github.com/GNS3/gns3-server/commit/0a536278fcd2975a60ff02862f37869b8b7e3ddf I no longer see this kind of error.

I think it's not a regression because we got the first report with beta 1:
https://github.com/GNS3/gns3-server/issues/310

**Comment by noplay** [comment]
And error was in 1.3.X also

**Comment by grossmj** [comment]
Confirmed, seems to have fixed the issue.

**Comment by grossmj** [comment]
Actually I still see the issue. I had a manually started server when I did the tests.

```
Exception ignored in: <bound method Task.__del__ of <Task pending coro=<get() running at /usr/lib/python3.4/asyncio/queues.py:198> wait_for=<Future pending cb=[Task._wakeup()] created at /usr/lib/python3.4/asyncio/queues.py:195> cb=[_release_waiter(<Future cance.../tasks.py:360>)() at /usr/lib/python3.4/asyncio/tasks.py:335] created at /usr/lib/python3.4/asyncio/tasks.py:364>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 93, in __del__
  File "/usr/lib/python3.4/asyncio/base_events.py", line 1037, in call_exception_handler
  File "/usr/lib/python3.4/logging/__init__.py", line 1303, in error
  File "/usr/lib/python3.4/logging/__init__.py", line 1409, in _log
  File "/usr/lib/python3.4/logging/__init__.py", line 1419, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 1481, in callHandlers
  File "/usr/lib/python3.4/logging/__init__.py", line 853, in handle
  File "/usr/lib/python3.4/logging/__init__.py", line 1040, in emit
  File "/usr/lib/python3.4/logging/__init__.py", line 1030, in _open
NameError: name 'open' is not defined

```

**Comment by noplay** [comment]
With 1.4?  Wich emulator was running?

It seem they have a similar issue:
https://github.com/tdryer/hangups/issues/36

The problem is asyncio try to log but due to the fact the logger start in the destructor he can't:
https://github.com/python/asyncio/blob/3.4.3/asyncio/base_events.py#L1037

And we lost the original exception :(

**Comment by noplay** [comment]
Ok a shell script for crashing:

```
curl -i -X POST 'http://localhost:8000/v1/projects' -d '{"name": "test", "project_id": "2547d75b-6059-4cff-a2ff-ac78ad5b98c7"}'

curl 'http://localhost:8000/v1/projects/2547d75b-6059-4cff-a2ff-ac78ad5b98c7/notifications' &

curl -XPOST "http://localhost:8000/v1/server/shutdown"
```

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/2fbc391319310fd22450ab863eeab3df91ee0030
