### ISSUE TITLE
Traceback when closing GUI

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-gui#726]
```
2015-10-17 11:26:56 INFO project.py:337 Project 1d1ff37f-6508-48d2-aabc-28a9fed7e353 closed
Project 1d1ff37f-6508-48d2-aabc-28a9fed7e353 closed
2015-10-17 11:26:56 INFO servers.py:512 Stopping local server (PID=8855)
Stopping local server (PID=8855)
Exception ignored in: <bound method ProgressDialog.__del__ of <gns3.utils.progress_dialog.ProgressDialog object at 0x7f064b05b4c8>>
Traceback (most recent call last):
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/utils/progress_dialog.py", line 72, in __del__
    self._cleanup()
  File "/home/grossmj/PycharmProjects/gns3-gui/gns3/utils/progress_dialog.py", line 78, in _cleanup
    if self._thread.isRunning():
```

**Comment by noplay** [comment]
I think I fixed the issue. Could you check on your side. I don't have the problem at each test. Since my patch I never saw the error.

**Comment by grossmj** [comment]
Seems to have fixed the problem. Cannot reproduce.
