### ISSUE TITLE
doctor crashes

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#967]
GNS3 version 1.4.1dev2 on Darwin (64-bit) with Python 3.5.1 Qt 5.5.1.

Use of doctor causes an exception:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gns3_gui-1.4.1.dev2-py3.5.egg/gns3/main_window.py", line 927, in _doctorSlot
    dialog = DoctorDialog(self)
  File "/usr/local/lib/python3.5/site-packages/gns3_gui-1.4.1.dev2-py3.5.egg/gns3/dialogs/doctor_dialog.py", line 51, in __init__
    (res, msg) = getattr(self, method)()
  File "/usr/local/lib/python3.5/site-packages/gns3_gui-1.4.1.dev2-py3.5.egg/gns3/dialogs/doctor_dialog.py", line 132, in checkUbridgePermission
    if sys.platform.startswith("linux") and "security.capability" in os.listxattr(path):
NameError: name 'sys' is not defined
```

Adding an "import sys" to dialogs/doctor_dialog.py helps

**Comment by noplay** [comment]
I fixed it. I need to reinstall a linux to test. My VM die this morning:
[image: Capture d’écran 2016-01-27 à 14.34.40.png]

**Comment by cioby23** [comment]
Another traceback appears now:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/gns3_gui-1.4.1.dev2-py3.5.egg/gns3/main_window.py", line 927, in _doctorSlot
    dialog = DoctorDialog(self)
  File "/usr/lib/python3.5/site-packages/gns3_gui-1.4.1.dev2-py3.5.egg/gns3/dialogs/doctor_dialog.py", line 52, in __init__
    (res, msg) = getattr(self, method)()
  File "/usr/lib/python3.5/site-packages/gns3_gui-1.4.1.dev2-py3.5.egg/gns3/dialogs/doctor_dialog.py", line 136, in checkUbridgePermission
    if not struct.unpack("<IIIII", caps)[1] & 1 << 13:
NameError: name 'struct' is not defined

**Comment by ehlers** [comment]
On OS X it works now, on Linux it also get same crash as @cioby23 . For that an "import struct" helps.

Now I start checking the logic.

**Comment by noplay** [comment]
ISO download in progress I should be able to test in few hours

**Comment by ehlers** [comment]
This is my current patch for linux. Previously the else part for capabilities not supported was choosen, when the capabilities were OK.

```
diff --git a/gns3/dialogs/doctor_dialog.py b/gns3/dialogs/doctor_dialog.py
index ae0809a..fc08025 100644
--- a/gns3/dialogs/doctor_dialog.py
+++ b/gns3/dialogs/doctor_dialog.py
@@ -120,7 +121,7 @@ class DoctorDialog(QtWidgets.QDialog, Ui_DoctorDialog):
         return (0, None)
 
     def checkUbridgePermission(self):
-        """Check if ubridge as the correct permission"""
+        """Check if ubridge has the correct permission"""
         if os.geteuid() == 0:
             # we are root, so we should have privileged access.
             return (0, None)
@@ -130,21 +131,23 @@ class DoctorDialog(QtWidgets.QDialog, Ui_DoctorDialog):
             return (0, None)
 
         request_setuid = False
-        if sys.platform.startswith("linux") and "security.capability" in os.listxattr(path):
-            caps = os.getxattr(path, "security.capability")
-            # test the 2nd byte and check if the 13th bit (CAP_NET_RAW) is set
-            if not struct.unpack("<IIIII", caps)[1] & 1 << 13:
-                return(2, "Ubridge require CAP_NET_RAW. Run sudo setcap cap_net_admin,cap_net_raw=ep {path}".format(path=path))
+        if sys.platform.startswith("linux"):
+            if "security.capability" in os.listxattr(path):
+                caps = os.getxattr(path, "security.capability")
+                # test the 2nd byte and check if the 13th bit (CAP_NET_RAW) is set
+                if not struct.unpack("<IIIII", caps)[1] & 1 << 13:
+                    return(2, "Ubridge require CAP_NET_RAW. Run sudo setcap cap_net_admin,cap_net_raw=ep {path}".format(path=path))
             else:
                 # capabilities not supported
                 request_setuid = True
+
         if sys.platform.startswith("darwin") or request_setuid:
              if os.stat(path).st_uid != 0 or not os.stat(path).st_mode & stat.S_ISUID:
                 return (2, "Ubridge should be setuid. Run sudo chown root {path} and sudo chmod 4755 {path}".format(path=path))
         return (0, None)
 
     def checkDynamipsPermission(self):
-        """Check if dynamips as the correct permission"""
+        """Check if dynamips has the correct permission"""
         if os.geteuid() == 0:
             # we are root, so we should have privileged access.
             return (0, None)
```

**Comment by noplay** [comment]
Apply, thanks
